### ISSUE TITLE
Python 3.4

### ISSUE THREAD

**Issue by vadimkara** [ponyorm/pony#114]
from pony.orm import *
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 2218, in _find_and_load_unlocked
AttributeError: 'module' object has no attribute '__path__'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<pyshell#0>", line 1, in <module>
    from pony.orm import *
  File "C:\Python34\pony.py", line 1, in <module>
    from pony.orm import *
ImportError: No module named 'pony.orm'; 'pony' is not a package
>>>

**Comment by vadimkara** [comment]
solved

**Comment by amalashkevich** [comment]
try to rename your file from ``pony.py`` to something else
