### ISSUE TITLE
ValueError: Attribute .user is required

### ISSUE THREAD

**Issue by interneteur** [ponyorm/pony#135]
So I'm trying to add in a favorite.  
Here is the models
```
class Favorite(db.Entity):
    game = Required(Game)
    user = Required(User)
    date_favorited = Required(datetime)
    PrimaryKey(user, game)
```
and here is the route

```
@app.route('/favorites/<path:path>', methods=['POST', 'GET'])
@pny.db_session
@login_required
def favorite(path):
    game = request.args.get('game')
    user = g.user._get_current_object()
    user = user.id
    if game is None or user is None:
        return 'missing arguments'
    if path == 'add':
        if Favorite.exists(user=User[user], game=Game[game]):
            return "fav already exists"
        Favorite(user=User[user], game=Game[game], date_favorited=datetime.now())
        return "success added"
```

Not particularly sure why it is giving me the error.  I have tried
```
Favorite(user=user, game=game, date_favorited=datetime.now())
```
as well but I still keep getting this error.  Which also makes no sense because the game id I am passing is not 44, diffrent every time.
```
127.0.0.1 - - [10/Jul/2015 14:35:22] "GET /favorites/add?game=7 HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/john/.virtualenvs/juegoapi/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/john/.virtualenvs/juegoapi/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/john/.virtualenvs/juegoapi/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/john/.virtualenvs/juegoapi/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/john/.virtualenvs/juegoapi/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/john/.virtualenvs/juegoapi/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/john/.virtualenvs/juegoapi/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/john/.virtualenvs/juegoapi/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "<auto generated wrapper of favorite() function>", line 2, in favorite
    
  File "/home/john/.virtualenvs/juegoapi/lib/python2.7/site-packages/pony/orm/core.py", line 347, in new_func
    try: return func(*args, **kwargs)
  File "/home/john/.virtualenvs/juegoapi/lib/python2.7/site-packages/flask_login.py", line 758, in decorated_view
    return func(*args, **kwargs)
  File "/home/john/Scripts/Python/games/views.py", line 162, in favorite
    Favorite(user=user, game=game, date_favorited=datetime.now())
  File "<auto generated wrapper of __new__() function>", line 2, in __new__
    
  File "/home/john/.virtualenvs/juegoapi/lib/python2.7/site-packages/pony/utils.py", line 88, in cut_traceback
    return func(*args, **kwargs)
  File "/home/john/.virtualenvs/juegoapi/lib/python2.7/site-packages/pony/orm/core.py", line 3565, in __new__
    obj = entity._new_(pkval, 'created', undo_funcs=undo_funcs)
  File "/home/john/.virtualenvs/juegoapi/lib/python2.7/site-packages/pony/orm/core.py", line 3360, in _new_
    if attr.reverse: attr.update_reverse(obj, NOT_LOADED, val, undo_funcs)
  File "/home/john/.virtualenvs/juegoapi/lib/python2.7/site-packages/pony/orm/core.py", line 1520, in update_reverse
    if new_val is not None: reverse.__set__(new_val, obj, undo_funcs)
  File "<auto generated wrapper of __set__() function>", line 2, in __set__
    
  File "/home/john/.virtualenvs/juegoapi/lib/python2.7/site-packages/pony/utils.py", line 88, in cut_traceback
    return func(*args, **kwargs)
  File "/home/john/.virtualenvs/juegoapi/lib/python2.7/site-packages/pony/orm/core.py", line 1457, in __set__
    if new_val is not None: reverse.__set__(old_val, None, undo_funcs)
  File "<auto generated wrapper of __set__() function>", line 2, in __set__
    
  File "/home/john/.virtualenvs/juegoapi/lib/python2.7/site-packages/pony/utils.py", line 88, in cut_traceback
    return func(*args, **kwargs)
  File "/home/john/.virtualenvs/juegoapi/lib/python2.7/site-packages/pony/orm/core.py", line 1395, in __set__
    new_val = attr.validate(new_val, obj, from_db=False)
  File "/home/john/.virtualenvs/juegoapi/lib/python2.7/site-packages/pony/orm/core.py", line 1612, in validate
    throw(ValueError, 'Attribute %r.%s is required' % (obj, attr.name))
  File "/home/john/.virtualenvs/juegoapi/lib/python2.7/site-packages/pony/utils.py", line 126, in throw
    raise exc
ValueError: Attribute Favorite[<User u'mofoparrot'>,Game[44]].user is required
```

**Comment by kozlovsky** [comment]
Can you show how `User` class is defined? I think that the error is in `User` entity definition.

**Comment by interneteur** [comment]
```
class User(UserMixin, db.Entity):
    username = Required(unicode, 20, unique=True)
    email = Required(unicode, 255, unique=True)
    password_hash = Optional(unicode, 255)
    main = Optional("User", reverse="alts")
    alts = Set("User", reverse="main")
    roles = Set("Role")
    permissions = Set("Permission")
    profile = Optional("UserProfile")
    is_confirmed = Required(bool, default=0)
    is_active = Required(bool, default=0)
    is_main = Required(bool, default=0)
    confirmed_at = Required(datetime, default=lambda: datetime.now())
    last_login = Required(datetime, default=lambda: datetime.now())
    current_login = Required(datetime, default=lambda: datetime.now())
    ips = Set("User_IP")
    favorites = Optional("Favorite")
    upvotes = Optional("Game_Upvote")
    downvotes = Optional("Game_Downvote")

    def hash_password(self, password):
        self.password_hash = pwd_context.encrypt(password)

    def verify_password(self, password):
        return pwd_context.verify(password, self.password_hash)

    def is_authenticated(self):
        return True

    def is_active(self):
        return True

    def is_anonymous(self):
        return False

    def get_id(self):
        try:
            return unicode(self.id)  # python 2
        except NameError:
            return str(self.id)  # python 3


    def __repr__(self):
        return '<User %r>' % (self.username)
```

**Comment by kozlovsky** [comment]
Inside the traceback you can locate the line of your code which causes the error:
```python
File "/home/john/Scripts/Python/games/views.py", line 162, in favorite
    Favorite(user=user, game=game, date_favorited=datetime.now())
```

The reason of the error is incorrect `User` entity definition. In `User` class you have a `favorites` attribute:
```python
    favorites = Optional("Favorite")
```
`Optional` means that each user can be linked to at most one favorite. When your program executes the line:
```python
    Favorite(user=User[user], game=Game[game], date_favorited=datetime.now())
```
It tries to link a user to a new favorite object. If that user was already linked to another favorite object, it is necessary to Pony to unlink the user from the previous favorite object, because the `Optional` `User.favorites` attribute cannot be linked to more than one favorite object. But, when Pony unlinks the user from the previous favorite object it encounters an error, because `Favorite.user` attribute is required and cannot be set to `None`.

In order to fix an error you need to define `User.favorites` attribute as a `Set`:
```python
class User(db.Entity):
    ...
    favorites = Set("Favorite")
    ...
```
Then each user can be linked to more than one favorite object, and your function will work without an error.

**Comment by kozlovsky** [comment]
By the same logic, your attributes `User.upvotes` and `User.downvotes` should be probably defined as a `Set` instead of `Optional`, because attribute name is in plural form.

**Comment by interneteur** [comment]
Yeah I changed that as well, thank you so much!
