### ISSUE TITLE
cascade delete foreign key error

### ISSUE THREAD

**Issue by gabriel-ilie** [ponyorm/pony#136]
I'm trying to use cascade_delete as detailed in the documentation (http://doc.ponyorm.com/working_with_entity_instances.html#cascade-delete).
I'm using pony 0.6.1 and python2.7

```python
####################################################################
from pony.orm import *
db = Database("sqlite", ":memory:", create_db=True)

class Person(db.Entity):
    name = Required(str)
    passport = Optional("Passport", cascade_delete=True)

class Passport(db.Entity):
    number = Required(str)
    person = Required("Person")

sql_debug(True)
db.generate_mapping(create_tables=True)

with db_session:
    pers = Person(name='John')
    passport = Passport(number='1234', person=pers)

with db_session:
    p = Person.get(name='John')
    p.delete()

####################################################################
```

Output:
```python
>>> 
GET CONNECTION FROM THE LOCAL POOL
PRAGMA foreign_keys = false
BEGIN IMMEDIATE TRANSACTION
CREATE TABLE "Person" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "name" TEXT NOT NULL
)

CREATE TABLE "Passport" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "number" TEXT NOT NULL,
  "person" INTEGER NOT NULL REFERENCES "Person" ("id")
)

CREATE INDEX "idx_passport__person" ON "Passport" ("person")

SELECT "Passport"."id", "Passport"."number", "Passport"."person"
FROM "Passport" "Passport"
WHERE 0 = 1

SELECT "Person"."id", "Person"."name"
FROM "Person" "Person"
WHERE 0 = 1

COMMIT
PRAGMA foreign_keys = true
CLOSE CONNECTION
GET CONNECTION FROM THE LOCAL POOL
BEGIN IMMEDIATE TRANSACTION
INSERT INTO "Person" ("name") VALUES (?)
[u'John']

INSERT INTO "Passport" ("number", "person") VALUES (?, ?)
[u'1234', 1]

COMMIT
RELEASE CONNECTION
GET CONNECTION FROM THE LOCAL POOL
SWITCH TO AUTOCOMMIT MODE
SELECT "id", "name"
FROM "Person"
WHERE "name" = ?
LIMIT 2
[u'John']

SELECT "id", "number", "person"
FROM "Passport"
WHERE "person" = ?
LIMIT 2
[1]

BEGIN IMMEDIATE TRANSACTION
DELETE FROM "Person"
WHERE "id" = ?
  AND "name" = ?
[1, u'John']

ROLLBACK
RELEASE CONNECTION

Traceback (most recent call last):
  File "/mnt/hgfs/share/code_repo/PassCon/Server/cascade_delete_issue.py", line 22, in <module>
    p.delete()
  File "/usr/local/lib/python2.7/site-packages/pony/orm/core.py", line 388, in __exit__
    commit()
  File "<auto generated wrapper of commit() function>", line 2, in commit
  File "/usr/local/lib/python2.7/site-packages/pony/utils.py", line 88, in cut_traceback
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/pony/orm/core.py", line 284, in commit
    transact_reraise(CommitException, exceptions)
  File "/usr/local/lib/python2.7/site-packages/pony/orm/core.py", line 268, in transact_reraise
    reraise(exc_class, new_exc, tb)
  File "/usr/local/lib/python2.7/site-packages/pony/orm/core.py", line 278, in commit
    try: primary_cache.commit()
  File "/usr/local/lib/python2.7/site-packages/pony/orm/core.py", line 965, in commit
    if cache.modified: cache.flush()
  File "/usr/local/lib/python2.7/site-packages/pony/orm/core.py", line 1030, in flush
    if obj is not None: obj._save_()
  File "/usr/local/lib/python2.7/site-packages/pony/orm/core.py", line 4146, in _save_
    elif status == 'marked_to_delete': obj._save_deleted_()
  File "/usr/local/lib/python2.7/site-packages/pony/orm/core.py", line 4131, in _save_deleted_
    database._exec_sql(sql, arguments)
  File "/usr/local/lib/python2.7/site-packages/pony/orm/core.py", line 599, in _exec_sql
    connection = cache.reconnect(e)
  File "/usr/local/lib/python2.7/site-packages/pony/orm/core.py", line 932, in reconnect
    if not provider.should_reconnect(exc): reraise(*sys.exc_info())
  File "/usr/local/lib/python2.7/site-packages/pony/orm/core.py", line 597, in _exec_sql
    try: new_id = provider.execute(cursor, sql, arguments, returning_id)
  File "<auto generated wrapper of execute() function>", line 2, in execute
  File "/usr/local/lib/python2.7/site-packages/pony/orm/dbapiprovider.py", line 52, in wrap_dbapi_exceptions
    except dbapi_module.IntegrityError as e: raise IntegrityError(e)
CommitException: IntegrityError: foreign key constraint failed
>>> 
```

**Comment by kozlovsky** [comment]
Thanks for the reporting! This is a bug, I'll try to fix it today.
