### ISSUE TITLE
Entity.select_random() AssertionError

### ISSUE THREAD

**Issue by angru** [ponyorm/pony#142]
```python
from pony.orm import Database, Required, PrimaryKey, db_session, show, select


db = Database()


class Some(db.Entity):
    id = PrimaryKey(int, auto=True)
    value = Required(int)


if __name__ == '__main__':
    db.bind('sqlite', ':memory:')
    db.generate_mapping(create_tables=True)

    with db_session:
        for i in range(10):
            s = Some(value=i)

        show(Some.select_random(limit=1))  # works fine here

    with db_session:
        show(Some.select_random(limit=1))  # error here if Entity is not "warmed"
```

```
Traceback (most recent call last):
  File "D:\projects\Python\quotebot\test2.py", line 24, in <module>
    print(Some.select_random(limit=1))
  File "<string>", line 2, in select_random
  File "C:\dev\Python34\lib\site-packages\pony\utils.py", line 88, in cut_traceback
    return func(*args, **kwargs)
  File "C:\dev\Python34\lib\site-packages\pony\orm\core.py", line 3015, in select_random
    arguments = adapter([ (id,) for id in ids ])
  File "C:\dev\Python34\lib\site-packages\pony\orm\sqlbuilding.py", line 161, in adapter
    return tuple(convert(values, params))
  File "C:\dev\Python34\lib\site-packages\pony\orm\sqlbuilding.py", line 137, in convert
    assert type(type(value)).__name__ == 'EntityMeta'
AssertionError
```

But in works fine after we "warm up" Entity like:
```python
    with db_session:
        show(select(s for s in Some))
        show(Some.select_random(limit=1))
```

```
[Some[4]]
```

**Comment by kozlovsky** [comment]
Thanks, fixed!

**Comment by angru** [comment]
wow, fixed so quickly, thanks.
