### ISSUE TITLE
Pony ORM is partially broken in Python 3.5

### ISSUE THREAD

**Issue by andreymal** [ponyorm/pony#147]
I use Arch Linux with latest updates and Pony 0.6.1 from pip. Example code:

```
from pony.orm import *

db = Database('sqlite', ':memory:')

class Foo(db.Entity):
    name = Required(str)
    bar = Optional('Bar')

class Bar(db.Entity):
    foos = Set(Foo)

db.generate_mapping(create_tables=True)

# fail: Foo.select().order_by('1')
# fail: Bar().foos.select()[:]
```

Traceback (full [here](http://pastebin.com/MizTcRLx)):

```
>>> Bar().foos.select()[:]
Traceback (most recent call last):
[...]
File "/usr/lib/python3.5/site-packages/pony/orm/core.py", line 4672, in filter
    return query._process_lambda(func, globals, locals, order_by=False)
  File "/usr/lib/python3.5/site-packages/pony/orm/core.py", line 4601, in _process_lambda
    func_ast = string2ast(func)
  File "/usr/lib/python3.5/site-packages/pony/orm/core.py", line 4192, in string2ast
    module_node = parse('(%s)' % s)
  File "/usr/lib/python3.5/site-packages/pony/thirdparty/compiler/transformer.py", line 60, in parse
    return Transformer().parsesuite(buf)
[...]
  File "/usr/lib/python3.5/site-packages/pony/thirdparty/compiler/transformer.py", line 824, in com_node
    return self._dispatch[node[0]](node[1:])
  File "/usr/lib/python3.5/site-packages/pony/thirdparty/compiler/transformer.py", line 734, in factor
    node = self.lookup_node(nodelist[-1])(nodelist[-1][1:])
  File "/usr/lib/python3.5/site-packages/pony/thirdparty/compiler/transformer.py", line 746, in power
    node = self.com_node(nodelist[0])
  File "/usr/lib/python3.5/site-packages/pony/thirdparty/compiler/transformer.py", line 824, in com_node
    return self._dispatch[node[0]](node[1:])
KeyError: 322
```

Python 2.7 and 3.4 works fine

**Comment by kozlovsky** [comment]
Thanks for the reporting! Should work now.

**Comment by andreymal** [comment]
It works, thanks. Don't forget update [setup.py](https://github.com/ponyorm/pony/blob/orm/setup.py#L94) :)

**Comment by kozlovsky** [comment]
Thanks, updated in 776d5e02

**Comment by andreymal** [comment]
How about 0.6.2 release? It's uncomfortable to install from github instead of pypi (and #118 is very bothered on my little production)

**Comment by amalashkevich** [comment]
At the moment we are working on 0.6.2 and going to release it on Monday, January 11. 
Thank you for asking :)
