### ISSUE TITLE
Autostripped string is not validated before insert/update

### ISSUE THREAD

**Issue by andreymal** [ponyorm/pony#176]
```python
from pony.orm import *

db = Database()

class TestPost(db.Entity):
    title = Required(str)

db.bind('sqlite', ':memory:')
db.generate_mapping(create_tables=True)
sql_debug(True)

with db_session:
    post = TestPost(title=' ')


with db_session:
    TestPost.select().first()
```

```
$ python ponyfail.py
GET CONNECTION FROM THE LOCAL POOL
BEGIN IMMEDIATE TRANSACTION
INSERT INTO "TestPost" ("title") VALUES (?)
['']

COMMIT
RELEASE CONNECTION
GET CONNECTION FROM THE LOCAL POOL
SWITCH TO AUTOCOMMIT MODE
SELECT "tp"."id", "tp"."title"
FROM "TestPost" "tp"
ORDER BY 1
LIMIT 1

ROLLBACK
RELEASE CONNECTION
Traceback (most recent call last):
...
  File "/usr/lib/python3.5/site-packages/pony/orm/core.py", line 2186, in validate
    if obj is None: throw(ValueError, 'Attribute %s is required' % attr)
  File "/usr/lib/python3.5/site-packages/pony/utils.py", line 103, in throw
    raise exc
ValueError: Attribute TestPost.title is required
```

**Comment by andreymal** [comment]
Oops, fixed typo at last line, but bug still exists

**Comment by kozlovsky** [comment]
Fixed
