### ISSUE TITLE
CacheIndexError: Cannot update Language.source_lang: Language[1] with key en already exists

### ISSUE THREAD

**Issue by nadermx** [ponyorm/pony#181]
I'm trying to run this function 

```
@db_session
def static_proxy(path=None):
    lang = str(get_locale())[:2]
    text = Language.get(source_lang=lang)
    english = Language.get(source_lang='en')
    if not text:
        text = Language(source_lang=lang)
        for k in Language._columns_:
            if k != 'id':
                setattr(text, k, goog_translate_meta('en', lang, getattr(english, k)))
                commit()
    text = {k : getattr(english, k) for k in Language._columns_}
    return render_template('index.html',text = json.dumps(text))
```

problem I'm having is it keeps returning that the index already exists.  But when it's checking if it exists it's clearly not recogizing it.  Here is the traceroute.

```
Traceback (most recent call last):
  File "/home/fucked/.virtualenvs/yout/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/fucked/.virtualenvs/yout/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/fucked/.virtualenvs/yout/lib/python2.7/site-packages/flask_cors/extension.py", line 188, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/fucked/.virtualenvs/yout/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/fucked/.virtualenvs/yout/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/fucked/.virtualenvs/yout/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/fucked/.virtualenvs/yout/lib/python2.7/site-packages/flask_cors/extension.py", line 188, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/fucked/.virtualenvs/yout/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/fucked/.virtualenvs/yout/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/fucked/.virtualenvs/yout/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "<auto generated wrapper of static_proxy() function>", line 2, in static_proxy
    
  File "/home/fucked/.virtualenvs/yout/lib/python2.7/site-packages/pony/orm/core.py", line 396, in new_func
    try: return func(*args, **kwargs)
  File "/home/fucked/PycharmProjects/youtstream/app.py", line 404, in static_proxy
    setattr(text, k, goog_translate_meta('en', lang, getattr(english, k)))
  File "<auto generated wrapper of __set__() function>", line 2, in __set__
    
  File "/home/fucked/.virtualenvs/yout/lib/python2.7/site-packages/pony/utils.py", line 65, in cut_traceback
    return func(*args, **kwargs)
  File "/home/fucked/.virtualenvs/yout/lib/python2.7/site-packages/pony/orm/core.py", line 2008, in __set__
    cache.update_simple_index(obj, attr, old_val, new_val, undo)
  File "/home/fucked/.virtualenvs/yout/lib/python2.7/site-packages/pony/orm/core.py", line 1631, in update_simple_index
    % (obj.__class__.__name__, attr.name, obj2, new_val))
  File "/home/fucked/.virtualenvs/yout/lib/python2.7/site-packages/pony/utils.py", line 103, in throw
    raise exc
CacheIndexError: Cannot update Language.source_lang: Language[1] with key en already exists

```

**Comment by amalashkevich** [comment]
Seems the problem here is that you are trying to copy the value of all attributes, including the `source_lang` value. The value of `source_lang` is equal to 'en' and this way you're trying to create another object with the `source_lang='en'`.
You can try to replace the following line:

```if k != 'id':```

with this one:

```if k not in ('id', 'source_lang'):```

This way you won't copy the attributes that should be unique, and the exception should go away.
Please let me know if it helps.

Also, it would be better to iterate the attributes, not columns of an entity. One attribute can be mapped to more than one column. So you can replace this line:

```for k in Language._columns_:```

with this one:

```for attr in Language._attrs_:```

and then replace `k` with `attr.name`:

```   
    ...
        ...    
        for attr in Language._attrs_:
            if attr.name not in ('id', 'source_lang`):
                setattr(text, attr.name, goog_translate_meta('en', lang, getattr(english, attr.name)))
                commit()
    text = {attr.name : getattr(english, attr.name) for attr in Language._attrs_}
    return render_template('index.html',text = json.dumps(text))
```
