### ISSUE TITLE
CommitException: Object was updated outside of current transaction

### ISSUE THREAD

**Issue by nadermx** [ponyorm/pony#200]
Hi, I'm currently getting this error 

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask_cors/extension.py", line 188, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "<auto generated wrapper of highscore() function>", line 2, in highscore
  File "/usr/local/lib/python2.7/dist-packages/pony/orm/core.py", line 406, in new_func
    reraise(exc_type, exc, tb)
  File "/usr/local/lib/python2.7/dist-packages/pony/orm/core.py", line 396, in new_func
    try: return func(*args, **kwargs)
  File "/home/www/youtstream/app.py", line 619, in highscore
    commit()
  File "<auto generated wrapper of commit() function>", line 2, in commit
  File "/usr/local/lib/python2.7/dist-packages/pony/utils.py", line 65, in cut_traceback
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pony/orm/core.py", line 292, in commit
    transact_reraise(CommitException, exceptions)
  File "/usr/local/lib/python2.7/dist-packages/pony/orm/core.py", line 276, in transact_reraise
    reraise(exc_class, new_exc, tb)
  File "/usr/local/lib/python2.7/dist-packages/pony/orm/core.py", line 286, in commit
    try: primary_cache.commit()
  File "/usr/local/lib/python2.7/dist-packages/pony/orm/core.py", line 1518, in commit
    if cache.modified: cache.flush()
  File "/usr/local/lib/python2.7/dist-packages/pony/orm/core.py", line 1583, in flush
    if obj is not None: obj._save_()
  File "/usr/local/lib/python2.7/dist-packages/pony/orm/core.py", line 4732, in _save_
    elif status == 'modified': obj._save_updated_()
  File "/usr/local/lib/python2.7/dist-packages/pony/orm/core.py", line 4692, in _save_updated_
    throw(OptimisticCheckError, 'Object %s was updated outside of current transaction' % safe_repr(obj))
  File "/usr/local/lib/python2.7/dist-packages/pony/utils.py", line 103, in throw
    raise exc
CommitException: Object RunTime[64753] was updated outside of current transaction
```

But not sure why it's throwing the error on the commit()

Here is the code

```
@app.route('/highscore', methods=['GET'])
@db_session
def highscore():
    current = select(v for v in RunTime if v.status == True)[:]
    if len(current) == 0:
        setCurrent()
        flush()
        current = select(v for v in RunTime if v.status == True)[:]
        return jsonify(current[0].promoted_video.to_dict(), bid=(current[0].bid * 1440) / 100)
    else:
        if not datetime.utcnow() > current[0].end_time:
            return jsonify(current[0].promoted_video.to_dict(), bid=(current[0].bid * 1440) / 100)
        else:
            current[0].status = not current[0].status
            commit() #this is where it is throwing the error
            setCurrent()
            current = select(v for v in RunTime if v.status == True)[:]
            return jsonify(current[0].promoted_video.to_dict(), bid=(current[0].bid * 1440) / 100)

```

**Comment by kozlovsky** [comment]
What database do you use?

**Comment by nadermx** [comment]
postgres

**Comment by kozlovsky** [comment]
I think that you have several processes which try to update the same row concurrently. After the first process successfully updated `current[0].status`, the other process got the error, because the value in the database was changed.

In order to avoid this error you can do `SELECT FOR UPDATE` instead of just `SELECT` in your first query. Then only first process will process the object, while others will wait until the transaction is finished.

Try to change the first query to:

```python
current = select(v for v in RunTime if v.status == True).for_update()[:]
```

**Comment by kozlovsky** [comment]
By the way, you can use `.first()` or `.get()` instead of `[:]` if you want to get a single object from a query. The result will be an object or `None`. If the query returns more than one object, `.first()` discards other objects while `.get()` throws an exception `TooManyObjectsFound`.

**Comment by nadermx** [comment]
Thank you, that seemed to the fix the issue.  And I will update the others.

**Comment by nadermx** [comment]
So I ended up doing this, but now it's locking the database on postgres.

Here is the complete function, but I'm still unsure how to get around the db lock.


```
class PromotedVideo(db.Entity):
    video_id = Optional(unicode, 11)
    title = Optional(unicode, 255)
    created_at = Required(datetime, default=datetime.utcnow())
    user = Required(lambda: User)
    video_budget = Optional(float)
    max_bid = Optional(float)
    mp3 = Optional(int)
    mp4 = Optional(int)
    plays = Optional(int)
    impressions = Optional(int)
    clicks = Optional(int)
    expires = Optional(datetime)
    photo_url = Optional(unicode, 255)
    run_time = Set(lambda: RunTime)
    status = Optional(bool, default=False)
    running = Optional(bool, default=False)
    location = Optional(unicode, 255)


class RunTime(db.Entity):
    promoted_video = Optional(lambda: PromotedVideo)
    status = Optional(bool)
    start_time = Optional(datetime)
    end_time = Optional(datetime)
    bid = Optional(float)


@db_session
def setCurrent():
    for v in select(v for v in PromotedVideo):
        if datetime.utcnow() > v.expires:
            v.status = False
            v.running = False
            commit()
    videos = select(v for v in PromotedVideo if
                    v.status == True and v.max_bid > 0 and v.video_budget / 1440 < v.user.budget and v.max_bid / 1440 < v.video_budget).order_by(
        lambda v: desc(v.max_bid))[:]
    first = videos[0]
    second = videos[1]
    if (second.max_bid + 1) <= first.max_bid:
        minute_high_bid = (second.max_bid + 1) / 1440
    else:
        minute_high_bid = first.max_bid / 1440
    first.user_budget = first.user.budget - minute_high_bid
    RunTime(promoted_video=first, status=True, start_time=datetime.utcnow(),
            end_time=datetime.utcnow() + timedelta(seconds=60), bid=minute_high_bid)
    commit()
    if not first.running:
        first.running = True
        commit()
    for v in videos:
        if not first:
            v.running = False
            commit()


@app.route('/highscore', methods=['GET'])
@db_session
def highscore():
    try:
        current = select(v for v in RunTime if v.status).for_update().first()
        if len(current) == 0:
            setCurrent()
            flush()
            current = select(v for v in RunTime if v.status)[:]
            return jsonify(current[0].promoted_video.to_dict(), bid=(current[0].bid * 1440) / 100)
        else:
            if not datetime.utcnow() > current[0].end_time:
                return jsonify(current[0].promoted_video.to_dict(), bid=(current[0].bid * 1440) / 100)
            else:
                current[0].status = not current[0].status
                commit()
                setCurrent()
                current = select(v for v in RunTime if v.status)[:]
                return jsonify(current[0].promoted_video.to_dict(), bid=(current[0].bid * 1440) / 100)
    except:
        return jsonify(error="something went wrong")
```

and in the postgres error log it shows this 

```
2017-01-07 06:54:10 EST ERROR:  deadlock detected
2017-01-07 06:54:10 EST DETAIL:  Process 21740 waits for AccessExclusiveLock on tuple (5775,219) of relation 66159 of database 16652; blocked by process 21746.
        Process 21746 waits for ShareLock on transaction 117945268; blocked by process 21745.
        Process 21745 waits for ShareLock on transaction 117945267; blocked by process 21737.
        Process 21737 waits for AccessExclusiveLock on tuple (5775,219) of relation 66159 of database 16652; blocked by process 21740.
        Process 21740: SELECT "v"."id", "v"."promoted_video", "v"."status", "v"."start_time", "v"."end_time", "v"."bid"
        FROM "runtime" "v"
        WHERE "v"."status"
        FOR UPDATE
        Process 21746: SELECT "v"."id", "v"."promoted_video", "v"."status", "v"."start_time", "v"."end_time", "v"."bid"
        FROM "runtime" "v"
        WHERE "v"."status"
        FOR UPDATE
        Process 21745: SELECT "v"."id", "v"."promoted_video", "v"."status", "v"."start_time", "v"."end_time", "v"."bid"
        FROM "runtime" "v"
        WHERE "v"."status"
        FOR UPDATE
        Process 21737: SELECT "v"."id", "v"."promoted_video", "v"."status", "v"."start_time", "v"."end_time", "v"."bid"
        FROM "runtime" "v"
        WHERE "v"."status"
        FOR UPDATE
2017-01-07 06:54:10 EST HINT:  See server log for query details.
```
