### ISSUE TITLE
 ExprEvalError(src, cause) raised when using lambdas in expression after upgrade to 4.8

### ISSUE THREAD

**Issue by steinster** [ponyorm/pony#21]
```
job = models.Job.get(lambda j: j.id == id and j.user.id == user.id) or abort(404)
```

  File "<string>", line 2, in get

  File "/usr/local/lib/python2.7/dist-packages/pony/utils.py", line 95, in cut_traceback
    return func(_args, *_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pony/orm/core.py", line 2262, in get
    return entity._query_from_lambda_(first_arg, globals, locals).get()
  File "/usr/local/lib/python2.7/dist-packages/pony/orm/core.py", line 2574, in _query_from_lambda_
    return Query(code_key, inner_expr, globals, locals)
  File "/usr/local/lib/python2.7/dist-packages/pony/orm/core.py", line 3763, in **init**
    vars, vartypes = extract_vars(extractors, globals, locals)
  File "/usr/local/lib/python2.7/dist-packages/pony/orm/core.py", line 3737, in extract_vars
    except Exception, cause: raise ExprEvalError(src, cause)
ExprEvalError: user.id raises NameError: name 'user' is not defined

And here is the relevant code:

user = theuser
job = models.Job.get(lambda j: j.id == id and j.user.id == user.id) or abort(404)

user is a valid orm object.  I have had this same bug in a couple places now.  I can fix it in code by changing it to something like:
models.select(j for j in models.Job if ... ) or abort(404)

**Comment by stevennic** [comment]
I'm getting the same error in 0.7.14.

```python
cls.get(lambda s: s.url == str(search_url.with_suffix('.html')) and s.is_official == True)
```
```
Traceback (most recent call last):
  File "E:\Python\3.8.6\lib\site-packages\pony\utils\utils.py", line 78, in cut_traceback
    reraise(exc_type, exc, full_tb)
  File "E:\Python\3.8.6\lib\site-packages\pony\utils\utils.py", line 95, in reraise
    try: raise exc.with_traceback(tb)
  File "E:\Python\3.8.6\lib\site-packages\pony\utils\utils.py", line 61, in cut_traceback
    try: return func(*args, **kwargs)
  File "E:\Python\3.8.6\lib\site-packages\pony\orm\core.py", line 4013, in get
    if args: return entity._query_from_args_(args, kwargs, frame_depth=cut_traceback_depth+1).get()
  File "E:\Python\3.8.6\lib\site-packages\pony\orm\core.py", line 4407, in _query_from_args_
    return Query(code_key, inner_expr, globals, locals, cells)
  File "E:\Python\3.8.6\lib\site-packages\pony\orm\core.py", line 5689, in __init__
    tree, extractors = create_extractors(code_key, tree, globals, locals, special_functions, const_functions)
  File "E:\Python\3.8.6\lib\site-packages\pony\orm\asttranslation.py", line 360, in create_extractors
    pretranslator = PreTranslator(tree, globals, locals, special_functions, const_functions, outer_names)
  File "E:\Python\3.8.6\lib\site-packages\pony\orm\asttranslation.py", line 276, in __init__
    translator.dispatch(tree)
  File "E:\Python\3.8.6\lib\site-packages\pony\orm\asttranslation.py", line 285, in dispatch
    ASTTranslator.dispatch(translator, node)
  File "E:\Python\3.8.6\lib\site-packages\pony\orm\asttranslation.py", line 32, in dispatch
    stop = translator.call(pre_method, node)
  File "E:\Python\3.8.6\lib\site-packages\pony\orm\asttranslation.py", line 44, in call
    return method(translator, node)
  File "E:\Python\3.8.6\lib\site-packages\pony\orm\asttranslation.py", line 300, in preGenExprInner
    for if_ in qual.ifs: dispatch(if_.test)
  File "E:\Python\3.8.6\lib\site-packages\pony\orm\asttranslation.py", line 285, in dispatch
    ASTTranslator.dispatch(translator, node)
  File "E:\Python\3.8.6\lib\site-packages\pony\orm\asttranslation.py", line 36, in dispatch
    translator.dispatch(child)
  File "E:\Python\3.8.6\lib\site-packages\pony\orm\asttranslation.py", line 285, in dispatch
    ASTTranslator.dispatch(translator, node)
  File "E:\Python\3.8.6\lib\site-packages\pony\orm\asttranslation.py", line 36, in dispatch
    translator.dispatch(child)
  File "E:\Python\3.8.6\lib\site-packages\pony\orm\asttranslation.py", line 285, in dispatch
    ASTTranslator.dispatch(translator, node)
  File "E:\Python\3.8.6\lib\site-packages\pony\orm\asttranslation.py", line 36, in dispatch
    translator.dispatch(child)
  File "E:\Python\3.8.6\lib\site-packages\pony\orm\asttranslation.py", line 285, in dispatch
    ASTTranslator.dispatch(translator, node)
  File "E:\Python\3.8.6\lib\site-packages\pony\orm\asttranslation.py", line 42, in dispatch
    translator.call(post_method, node)
  File "E:\Python\3.8.6\lib\site-packages\pony\orm\asttranslation.py", line 44, in call
    return method(translator, node)
  File "E:\Python\3.8.6\lib\site-packages\pony\orm\asttranslation.py", line 338, in postCallFunc
    x = eval(expr, translator.globals, translator.locals)
  File "<string>", line 1, in <module>
NameError: name 'search_url' is not defined
```
At the point where this line is about to run, search_url resolves fine:
```
search_url
Out[1]: URL('https://www.mysite.com/page1.html')
```
