### ISSUE TITLE
add support for python 3.6

### ISSUE THREAD

**Issue by pingf** [ponyorm/pony#216]
when I use pip install with python 3.6, it says,

```    
Sorry, but pony 0.7 requires Python of one of the following versions: 2.7, 3.3, 3.4 and 3.5. You have version 3.6.0
```

**Comment by willzfarmer** [comment]
Bumping

I installed pony with python3.6 (I never got the error that @pingf got, it just worked for me), however I think something in Python3.6 broke queries.

Using the following dummy test file:

```python
#!/usr/bin/env python3.6

from pony import orm

db = orm.Database()

class Foo(db.Entity):
    name = orm.Required(str)

db.bind('sqlite', ':memory:')

db.generate_mapping(create_tables=True)

with orm.db_session:
    Foo(name="foo")

print(orm.select(_ for _ in Foo))
```

With python3.5 the output is as expected (a Query object) however with python 3.6 the output is the following:

```
Traceback (most recent call last):
  File "./tmp.py", line 17, in <module>
    print(orm.select(_ for _ in Foo))
  File "<string>", line 2, in select
  File "/home/william/.local/lib/python3.6/site-packages/pony/utils/utils.py", line 58, in cut_traceback
    return func(*args, **kwargs)
  File "/home/william/.local/lib/python3.6/site-packages/pony/orm/core.py", line 4930, in select
    return make_query(args, frame_depth=3)
  File "/home/william/.local/lib/python3.6/site-packages/pony/orm/core.py", line 4917, in make_query
    tree, external_names, cells = decompile(gen)
  File "/home/william/.local/lib/python3.6/site-packages/pony/orm/decompiling.py", line 35, in decompile
    decompiler = Decompiler(codeobject)
  File "/home/william/.local/lib/python3.6/site-packages/pony/orm/decompiling.py", line 75, in __init__
    decompiler.decompile()
  File "/home/william/.local/lib/python3.6/site-packages/pony/orm/decompiling.py", line 100, in decompile
    elif op in haslocal: arg = [code.co_varnames[oparg]]
IndexError: tuple index out of range
```

**Comment by kozlovsky** [comment]
Thanks for reporting, should be fixed now!
