### ISSUE TITLE
to_json(Entity.select()) - ValueError: invalid literal for int() with base 10: ''

### ISSUE THREAD

**Issue by joagovi** [ponyorm/pony#220]
Im using Pony with Python 2.7, I get this error, Maybe this is because a version of python. I get this error:

>>> to_json(Pais.select().show())
id|nombre   
--+---------
1 |ARGENTINA
2 |BOLIVIA  
3 |BRASIL   
4 |CHILE    
5 |COLOMBIA 
6 |ECUADOR  
7 |PERU     
8 |URUGUAY  
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/pony/orm/serialization.py", line 109, in to_json
    return json.dumps(to_dict(objects), default=json_converter, indent=2, sort_keys=True)
  File "/usr/local/lib/python2.7/dist-packages/pony/orm/serialization.py", line 97, in to_dict
    objects = iter(objects)
TypeError: 'NoneType' object is not iterable
>>> to_json(Pais.select())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/pony/orm/serialization.py", line 109, in to_json
    return json.dumps(to_dict(objects), default=json_converter, indent=2, sort_keys=True)
  File "/usr/local/lib/python2.7/dist-packages/pony/orm/serialization.py", line 106, in to_dict
    return dict(bag.to_dict())
  File "<auto generated wrapper of to_dict() function>", line 2, in to_dict
  File "/usr/local/lib/python2.7/dist-packages/pony/utils/utils.py", line 75, in cut_traceback
    raise exc  # Set "pony.options.CUT_TRACEBACK = False" to see full traceback
ValueError: invalid literal for int() with base 10: ''

I would like to know if this is an issue of pony or I just need update python. When I try to do the same with other entitys retrieves the entity that I dont ask with to_json.

Sorry for my poor english
Thanks in advance

**Comment by micaiahparker** [comment]
`to_json` is going to be reworked, I believe it is suggested to use `to_dict` until then.

**Comment by andreshg112** [comment]
Same here using `to_dict()`. I think the problem it's because I'm using a foreign key different than `id`. I've tried adding and removing `fk_name` and `reverse_fk_name`.

```python
class MovementAlarm(AuditMixin, db.Entity):
    _table_ = 'movement_alarms'
    
    # Campos
    id = PrimaryKey(int, auto=True)
    # license_plate = Required(str)
    
    # Relaciones
    vehicle = Required(lambda: Vehicle, column='license_plate', fk_name='license_plate')

class Vehicle(AuditMixin, db.Entity):
    _table_ = 'vehicles'
    
    # Campos
    id = PrimaryKey(int, auto=True)
    license_plate = Optional(str, unique=True)
    
    # Relaciones
    movement_alarms = Set(lambda: MovementAlarm, reverse_fk_name='license_plate')
```

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-24-b10ac7e1d7b5> in <module>()
----> 1 model = MovementAlarm.get(id=100)
      2 
      3 print(model.to_dict())

~/anaconda3/lib/python3.5/site-packages/pony/orm/core.py in get(entity, *args, **kwargs)

~/anaconda3/lib/python3.5/site-packages/pony/utils/utils.py in cut_traceback(func, *args, **kwargs)
     76             if module_name.startswith('pony.utils') and tb.tb_frame.f_code.co_name == 'throw':
     77                 reraise(exc_type, exc, last_pony_tb)
---> 78             reraise(exc_type, exc, full_tb)
     79         finally:
     80             del exc, full_tb, tb, last_pony_tb

~/anaconda3/lib/python3.5/site-packages/pony/utils/utils.py in reraise(***failed resolving arguments***)
     93 else:
     94     def reraise(exc_type, exc, tb):
---> 95         try: raise exc.with_traceback(tb)
     96         finally: del exc, tb
     97 

~/anaconda3/lib/python3.5/site-packages/pony/utils/utils.py in cut_traceback(func, *args, **kwargs)
     59         return func(*args, **kwargs)
     60 
---> 61     try: return func(*args, **kwargs)
     62     except AssertionError: raise
     63     except Exception:

~/anaconda3/lib/python3.5/site-packages/pony/orm/core.py in get(entity, *args, **kwargs)
   3999     def get(entity, *args, **kwargs):
   4000         if args: return entity._query_from_args_(args, kwargs, frame_depth=cut_traceback_depth+1).get()
-> 4001         try: return entity._find_one_(kwargs)  # can throw MultipleObjectsFoundError
   4002         except ObjectNotFound: return None
   4003     @cut_traceback

~/anaconda3/lib/python3.5/site-packages/pony/orm/core.py in _find_one_(entity, kwargs, for_update, nowait, skip_locked)
   4102                 throw(TypeError, 'Collection attribute %s cannot be specified as search criteria' % attr)
   4103         obj, unique = entity._find_in_cache_(pkval, avdict, for_update)
-> 4104         if obj is None: obj = entity._find_in_db_(avdict, unique, for_update, nowait, skip_locked)
   4105         if obj is None: throw(ObjectNotFound, entity, pkval)
   4106         return obj

~/anaconda3/lib/python3.5/site-packages/pony/orm/core.py in _find_in_db_(entity, avdict, unique, for_update, nowait, skip_locked)
   4162         if for_update: database._get_cache().immediate = True
   4163         cursor = database._exec_sql(sql, arguments)
-> 4164         objects = entity._fetch_objects(cursor, attr_offsets, 1, for_update, avdict)
   4165         return objects[0] if objects else None
   4166     def _find_by_sql_(entity, max_fetch_count, sql, globals, locals, frame_depth):

~/anaconda3/lib/python3.5/site-packages/pony/orm/core.py in _fetch_objects(entity, cursor, attr_offsets, max_fetch_count, for_update, used_attrs)
   4293         else:
   4294             for row in rows:
-> 4295                 real_entity_subclass, pkval, avdict = entity._parse_row_(row, attr_offsets)
   4296                 obj = real_entity_subclass._get_from_identity_map_(pkval, 'loaded', for_update)
   4297                 if obj._status_ in del_statuses: continue

~/anaconda3/lib/python3.5/site-packages/pony/orm/core.py in _parse_row_(entity, row, attr_offsets)
   4333                 avdict[attr] = discr_value
   4334             else:
-> 4335                 avdict[attr] = attr.parse_value(row, offsets, cache.dbvals_deduplication_cache)
   4336 
   4337         pkval = tuple(avdict.pop(attr) for attr in entity._pk_attrs_)

~/anaconda3/lib/python3.5/site-packages/pony/orm/core.py in parse_value(attr, row, offsets, dbvals_deduplication_cache)
   2237                 assert len(set(dbvals)) == 1
   2238                 dbval = None
-> 2239             else: dbval = attr.py_type._get_by_raw_pkval_(dbvals)
   2240         return dbval
   2241     def load(attr, obj):

~/anaconda3/lib/python3.5/site-packages/pony/orm/core.py in _get_by_raw_pkval_(entity, raw_pkval, for_update, from_db, seed)
   4453                 val = raw_pkval[i]
   4454                 i += 1
-> 4455                 if not attr.reverse: val = attr.validate(val, None, entity, from_db=from_db)
   4456                 else: val = attr.py_type._get_by_raw_pkval_((val,), from_db=from_db, seed=seed)
   4457             else:

~/anaconda3/lib/python3.5/site-packages/pony/orm/core.py in validate(attr, val, obj, entity, from_db)
   2532     __slots__ = []
   2533     def validate(attr, val, obj=None, entity=None, from_db=False):
-> 2534         val = Attribute.validate(attr, val, obj, entity, from_db)
   2535         if val == '' or (val is None and not (attr.auto or attr.is_volatile or attr.sql_default)):
   2536             if not from_db:

~/anaconda3/lib/python3.5/site-packages/pony/orm/core.py in validate(attr, val, obj, entity, from_db)
   2202             if converter is not None:
   2203                 try:
-> 2204                     if from_db: return converter.sql2py(val)
   2205                     val = converter.validate(val, obj)
   2206                 except UnicodeDecodeError as e:

~/anaconda3/lib/python3.5/site-packages/pony/orm/dbapiprovider.py in sql2py(converter, val)
    548         return val
    549     def sql2py(converter, val):
--> 550         return int(val)
    551     def sql_type(converter):
    552         if not converter.unsigned:

ValueError: invalid literal for int() with base 10: 'SAT0001'
