### ISSUE TITLE
pony.orm.core.DBSchemaError because caseinsensitive Postgres

### ISSUE THREAD

**Issue by luckydonald** [ponyorm/pony#222]
DB
```python
class Pack(db.Entity):
    _table_ = 'StickerPack'
    # more stuff would be here.

db.bind("postgres", host="asdads", user="sakljdfhsdkjhf", password="sljdhfjdshf", database="sdjfjsjdfb")
db.generate_mapping(create_tables=True)
```
Stacktrace:
```python
Traceback (most recent call last):
  File "./main.py", line 32, in <module>
    from database import State, Sticker, StickerMessage, Tag, PackTag, StickerTag, User, WebSession
  File "./database.py", line 107, in <module>
    db.generate_mapping(create_tables=True)
  File "<string>", line 2, in generate_mapping
  File "/app/src/pony/pony/utils/utils.py", line 58, in cut_traceback
    return func(*args, **kwargs)
  File "/app/src/pony/pony/orm/core.py", line 875, in generate_mapping
    if create_tables: database.create_tables(check_tables)
  File "<string>", line 2, in create_tables
  File "/app/src/pony/pony/utils/utils.py", line 58, in cut_traceback
    return func(*args, **kwargs)
  File "<string>", line 2, in create_tables
  File "/app/src/pony/pony/orm/core.py", line 406, in new_func
    try: return func(*args, **kwargs)
  File "/app/src/pony/pony/orm/core.py", line 933, in create_tables
    database.schema.create_tables(database.provider, connection)
  File "/app/src/pony/pony/orm/dbschema.py", line 63, in create_tables
    'Try to delete %s %s first.' % (tn1, n1, tn2, n2, n2, tn2))
  File "/app/src/pony/pony/utils/utils.py", line 96, in throw
    raise exc

pony.orm.core.DBSchemaError: Table "StickerPack" cannot be created, because table "stickerpack" (with a different letter case) already exists in the database. Try to delete "stickerpack" table first.
```

**Comment by kozlovsky** [comment]
It's expected behavior, why do you think this is a bug?
