### ISSUE TITLE
TypeError: string argument without an encoding

### ISSUE THREAD

**Issue by WilliamMayor** [ponyorm/pony#235]
I'm new to Pony so apologies if this is a silly problem.

I have a user object with a password field. Like this:

```
class User(db.Entity):
    email = orm.Required(str)
    password = orm.Required(bytes)

    def __init__(self, password, *args, **kwargs):
        kwargs["password"] = bcrypt.hashpw(
            base64.b64encode(hashlib.sha256(password.encode('utf-8')).digest()),
            bcrypt.gensalt())
        super().__init__(*args, **kwargs)
```

I can create objects just fine (and I get a blob in the DB), but I can't query them.

```
>>> u = User.get(email='test@example.com')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<string>", line 2, in get
  File "/usr/local/lib/python3.6/site-packages/pony/utils/utils.py", line 75, in cut_traceback
    raise exc  # Set "pony.options.CUT_TRACEBACK = False" to see full traceback
  File "/usr/local/lib/python3.6/site-packages/pony/utils/utils.py", line 60, in cut_traceback
    try: return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pony/orm/core.py", line 3580, in get
    try: return entity._find_one_(kwargs)  # can throw MultipleObjectsFoundError
  File "/usr/local/lib/python3.6/site-packages/pony/orm/core.py", line 3670, in _find_one_
    if obj is None: obj = entity._find_in_db_(avdict, unique, for_update, nowait)
  File "/usr/local/lib/python3.6/site-packages/pony/orm/core.py", line 3730, in _find_in_db_
    objects = entity._fetch_objects(cursor, attr_offsets, 1, for_update, avdict)
  File "/usr/local/lib/python3.6/site-packages/pony/orm/core.py", line 3859, in _fetch_objects
    real_entity_subclass, pkval, avdict = entity._parse_row_(row, attr_offsets)
  File "/usr/local/lib/python3.6/site-packages/pony/orm/core.py", line 3889, in _parse_row_
    avdict[attr] = attr.parse_value(row, offsets)
  File "/usr/local/lib/python3.6/site-packages/pony/orm/core.py", line 1922, in parse_value
    val = attr.validate(row[offset], None, attr.entity, from_db=True)
  File "/usr/local/lib/python3.6/site-packages/pony/orm/core.py", line 2218, in validate
    val = Attribute.validate(attr, val, obj, entity, from_db)
  File "/usr/local/lib/python3.6/site-packages/pony/orm/core.py", line 1894, in validate
    if from_db: return converter.sql2py(val)
  File "/usr/local/lib/python3.6/site-packages/pony/orm/dbapiprovider.py", line 619, in sql2py
    if not isinstance(val, buffer): val = buffer(val)
TypeError: string argument without an encoding
```

So it's a bytes problem?

**Comment by nadermx** [comment]
Can you try with 
```

class User(db.Entity):
    email = orm.Required(unicode)
```
and then 
`u = User.get(email='test@example.com')`

**Comment by WilliamMayor** [comment]
I tried `email = orm.Required(orm.unicode)` but then I can't add things to the DB because of this error:

    TypeError: Value type for attribute User.password must be str. Got: <class 'bytes'>

I'm using Python 3.6 so I can't use `unicode` directly. It looks like `orm.unicode` is py2 and py3 compatible. Or should I try something else?

**Comment by andreymal** [comment]
How about `password = orm.Required(str)` and just `bcrypt.hashpw(...).decode()`? I have not seen non-ascii characters in bcrypt result.

**Comment by WilliamMayor** [comment]
I suspect that's what I'll do. Because bcrypt spits out bytes I thought I'd just store them as bytes. It looks like it's going to be a hassle so I'll stringify them instead.

Thanks for the help!
