### ISSUE TITLE
ProgrammingError: operator does not exist: json = unknown

### ISSUE THREAD

**Issue by nadermx** [ponyorm/pony#237]
Hi all, I'm having a issue where I get this trackback

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/sync.py", line 135, in handle
    self.handle_request(listener, req, client, addr)
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/sync.py", line 176, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1994, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/pony/utils/utils.py", line 36, in pony_wrapper
    return caller(func, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pony/orm/core.py", line 423, in new_func
    finally: db_session.__exit__(exc_type, exc, tb)
  File "/usr/local/lib/python2.7/dist-packages/pony/orm/core.py", line 394, in __exit__
    commit()
  File "<auto generated wrapper of commit() function>", line 2, in commit
  File "/usr/local/lib/python2.7/dist-packages/pony/utils/utils.py", line 58, in cut_traceback
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pony/orm/core.py", line 293, in commit
    cache.flush()
  File "/usr/local/lib/python2.7/dist-packages/pony/orm/core.py", line 1610, in flush
    if obj is not None: obj._save_()
  File "/usr/local/lib/python2.7/dist-packages/pony/orm/core.py", line 4808, in _save_
    elif status == 'modified': obj._save_updated_()
  File "/usr/local/lib/python2.7/dist-packages/pony/orm/core.py", line 4766, in _save_updated_
    cursor = database._exec_sql(sql, arguments, start_transaction=True)
  File "/usr/local/lib/python2.7/dist-packages/pony/orm/core.py", line 703, in _exec_sql
    connection = cache.reconnect(e)
  File "/usr/local/lib/python2.7/dist-packages/pony/orm/core.py", line 1511, in reconnect
    if not provider.should_reconnect(exc): reraise(*sys.exc_info())
  File "/usr/local/lib/python2.7/dist-packages/pony/orm/core.py", line 701, in _exec_sql
    try: new_id = provider.execute(cursor, sql, arguments, returning_id)
  File "<auto generated wrapper of execute() function>", line 2, in execute
  File "/usr/local/lib/python2.7/dist-packages/pony/orm/dbapiprovider.py", line 50, in wrap_dbapi_exceptions
    except dbapi_module.ProgrammingError as e: raise ProgrammingError(e)
ProgrammingError: operator does not exist: json = unknown
LINE 5:   AND "info" = '{"medium": false}'
                     ^
HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts.
```

When I initially set the json I do this,
```
class User(db.Entity):
        info = Optional(Json)


medium = {'medium': False}
user = models.User(username=username, email=email, info=medium)
```

I then later update the query in another route by doing this

```
user.info['medium'] = True
models.commit()
```

I'm using `pony==0.7.1` and `psql (PostgreSQL) 9.3.15`

**Comment by nadermx** [comment]
So it seems the `jsonb` was added after postgres, so I went ahead and upgraded database to 9.6.  Will reopen if error happens again

**Comment by nadermx** [comment]
Note I also had to upgrade the column, I used 
`alter table t alter column j type jsonb using j::text::jsonb;`
