### ISSUE TITLE
AttributeError: 'str' object has no attribute 'split'

### ISSUE THREAD

**Issue by nadermx** [ponyorm/pony#247]
I'm getting this when trying to apply a `split` to a object I have stored in the database

the code is 

```
class Domain(db.Entity):
    name = Required(unicode, unique=True)

q = models.select(d for d in models.Domain)
q = q.filter(lambda d: c in d.name.split('.')[0])
```
but the erro I'm getting is this

```
Traceback (most recent call last):
  File "/home/fucked/.virtualenvs/expired/lib/python3.5/site-packages/flask/app.py", line 1994, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/fucked/.virtualenvs/expired/lib/python3.5/site-packages/pony/utils/utils.py", line 36, in pony_wrapper
    return caller(func, *args, **kwargs)
  File "/home/fucked/.virtualenvs/expired/lib/python3.5/site-packages/pony/orm/core.py", line 413, in new_func
    try: return func(*args, **kwargs)
  File "/home/fucked/.virtualenvs/expired/lib/python3.5/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/home/fucked/.virtualenvs/expired/lib/python3.5/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/fucked/.virtualenvs/expired/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/fucked/.virtualenvs/expired/lib/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/fucked/.virtualenvs/expired/lib/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/fucked/.virtualenvs/expired/lib/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/fucked/.virtualenvs/expired/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/fucked/.virtualenvs/expired/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/fucked/.virtualenvs/expired/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/fucked/PycharmProjects/expired/app/frontend/views.py", line 24, in index
    pronounceability=pronounceability)
  File "/home/fucked/PycharmProjects/expired/app/utilities.py", line 25, in get_domains
    q = q.filter(lambda d: c in d.name.split('.')[0])
  File "<string>", line 2, in filter
    from pony.py23compat import PY2, izip, imap, iteritems, itervalues, items_list, values_list, xrange, cmp, \
  File "/home/fucked/.virtualenvs/expired/lib/python3.5/site-packages/pony/utils/utils.py", line 58, in cut_traceback
    return func(*args, **kwargs)
  File "/home/fucked/.virtualenvs/expired/lib/python3.5/site-packages/pony/orm/core.py", line 5431, in filter
    return query._process_lambda(func, globals, locals, order_by=False)
  File "/home/fucked/.virtualenvs/expired/lib/python3.5/site-packages/pony/orm/core.py", line 5395, in _process_lambda
    new_translator = prev_translator.apply_lambda(filter_num, order_by, func_ast, argnames, extractors, vartypes)
  File "/home/fucked/.virtualenvs/expired/lib/python3.5/site-packages/pony/orm/sqltranslation.py", line 608, in apply_lambda
    translator.dispatch(func_ast)
  File "/home/fucked/.virtualenvs/expired/lib/python3.5/site-packages/pony/orm/sqltranslation.py", line 82, in dispatch
    return ASTTranslator.dispatch(translator, node)  # default route
  File "/home/fucked/.virtualenvs/expired/lib/python3.5/site-packages/pony/orm/asttranslation.py", line 24, in dispatch
    stop = translator.call(pre_method, node)
  File "/home/fucked/.virtualenvs/expired/lib/python3.5/site-packages/pony/orm/sqltranslation.py", line 135, in call
    reraise(exc_class, exc, tb)
  File "/home/fucked/.virtualenvs/expired/lib/python3.5/site-packages/pony/utils/utils.py", line 85, in reraise
    try: raise exc.with_traceback(tb)
  File "/home/fucked/.virtualenvs/expired/lib/python3.5/site-packages/pony/orm/sqltranslation.py", line 125, in call
    try: monad = method(node)
  File "/home/fucked/.virtualenvs/expired/lib/python3.5/site-packages/pony/orm/sqltranslation.py", line 649, in preCompare
    translator.dispatch(right)
  File "/home/fucked/.virtualenvs/expired/lib/python3.5/site-packages/pony/orm/sqltranslation.py", line 82, in dispatch
    return ASTTranslator.dispatch(translator, node)  # default route
  File "/home/fucked/.virtualenvs/expired/lib/python3.5/site-packages/pony/orm/asttranslation.py", line 29, in dispatch
    translator.dispatch(child)
  File "/home/fucked/.virtualenvs/expired/lib/python3.5/site-packages/pony/orm/sqltranslation.py", line 82, in dispatch
    return ASTTranslator.dispatch(translator, node)  # default route
  File "/home/fucked/.virtualenvs/expired/lib/python3.5/site-packages/pony/orm/asttranslation.py", line 29, in dispatch
    translator.dispatch(child)
  File "/home/fucked/.virtualenvs/expired/lib/python3.5/site-packages/pony/orm/sqltranslation.py", line 82, in dispatch
    return ASTTranslator.dispatch(translator, node)  # default route
  File "/home/fucked/.virtualenvs/expired/lib/python3.5/site-packages/pony/orm/asttranslation.py", line 35, in dispatch
    translator.call(post_method, node)
  File "/home/fucked/.virtualenvs/expired/lib/python3.5/site-packages/pony/orm/sqltranslation.py", line 135, in call
    reraise(exc_class, exc, tb)
  File "/home/fucked/.virtualenvs/expired/lib/python3.5/site-packages/pony/utils/utils.py", line 85, in reraise
    try: raise exc.with_traceback(tb)
  File "/home/fucked/.virtualenvs/expired/lib/python3.5/site-packages/pony/orm/sqltranslation.py", line 125, in call
    try: monad = method(node)
  File "/home/fucked/.virtualenvs/expired/lib/python3.5/site-packages/pony/orm/sqltranslation.py", line 703, in postGetattr
    return node.expr.monad.getattr(node.attrname)
  File "/home/fucked/.virtualenvs/expired/lib/python3.5/site-packages/pony/orm/sqltranslation.py", line 986, in wrapper
    return method(monad, *args, **kwargs)
  File "/home/fucked/.virtualenvs/expired/lib/python3.5/site-packages/pony/orm/sqltranslation.py", line 1019, in getattr
    throw(AttributeError, '%r object has no attribute %r' % (type2str(monad.type), attrname))
  File "/home/fucked/.virtualenvs/expired/lib/python3.5/site-packages/pony/utils/utils.py", line 96, in throw

```

**Comment by kozlovsky** [comment]
It is a non-trivial task to universally translate Python `str.split()` method to SQL. I suggest you to use raw SQL fragment (in the following example I assume you use PostgreSQL):
```python
q = q.filter(lambda d: raw_sql("""
   position($c in split_part("d"."name", '.', 1)) > 0
"""))
```
