### ISSUE TITLE
Incorrect working with float (PostgreSQL)

### ISSUE THREAD

**Issue by andreymal** [ponyorm/pony#256]
```python
from pony.orm import *

db = Database()

class PiValue(db.Entity):
    digits = Required(int)
    value = Required(float)

db.bind('postgres', user='user', password='123456', database='testdb')
db.generate_mapping(create_tables=True)

# prepare database for test
with db_session:
    PiValue.select().delete()
with db_session:
    PiValue(id=1, digits=0, value=3.141592653589793).flush()
    # alternative:
    # db.execute('delete from pivalue')
    # db.execute('insert into pivalue values(1, 0, 3.141592653589793)')

sql_debug(True)

# test it!
with db_session:
    m = PiValue.get(id=1)
    print(m.value)  # required to reproduce problem
    m.digits = 20
```

```
Traceback (most recent call last):
  File "./pony_float_fail.py", line 27, in <module>
    m.digits = 20
  File "/home/andreymal/.local/lib/python3.6/site-packages/pony/orm/core.py", line 394, in __exit__
    commit()
pony.orm.core.OptimisticCheckError: Object PiValue[1] was updated outside of current transaction
```

But, as you can see, there is only one transaction.

You can also try other pi values:

- `3.14159265358979` works
- `3.141592653589793` fails

This is similar to #200, but I think I found true reason of this problem.

@nadermx you worked with floats `video_budget` and `max_bid`, it might be interesting for you

**Comment by andreymal** [comment]
Oops, already fixed by https://github.com/ponyorm/pony/commit/a00e4072962c90d4e257863a8dd1baa300851953
