### ISSUE TITLE
Exception while installing PonyORM

### ISSUE THREAD

**Issue by AbhishekBhattacharya** [ponyorm/pony#271]
$ **pip install pony**
Collecting pony
Installing collected packages: pony
**Exception:
Traceback (most recent call last):**
  File "/home/abhishek/.local/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/home/abhishek/.local/lib/python2.7/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/home/abhishek/.local/lib/python2.7/site-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/home/abhishek/.local/lib/python2.7/site-packages/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/home/abhishek/.local/lib/python2.7/site-packages/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/home/abhishek/.local/lib/python2.7/site-packages/pip/wheel.py", line 345, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/home/abhishek/.local/lib/python2.7/site-packages/pip/wheel.py", line 316, in clobber
    ensure_dir(destdir)
  File "/home/abhishek/.local/lib/python2.7/site-packages/pip/utils/__init__.py", line 83, in ensure_dir
    os.makedirs(path)
  File "/usr/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/pony-0.7.1.dist-info'

**Comment by AbhishekBhattacharya** [comment]
Using Ubuntu 32 bit

**Comment by andreymal** [comment]
`pip install --user pony` or `sudo pip install pony` or `virtualenv env; source env/bin/activate; pip install pony`
https://stackoverflow.com/questions/19471972

**Comment by AbhishekBhattacharya** [comment]
Done, using **sudo pip install pony**
Thanks for the help @andreymal

**Comment by AbhishekBhattacharya** [comment]
Exception while installing PonyORM #271
