### ISSUE TITLE
Cannot select on a table that hasn't id column.

### ISSUE THREAD

**Issue by forlayo** [ponyorm/pony#272]
I've getting the same error with some of my select as I'm getting the data from views on mysql database and mine doesn't have id column or primary key. After expending long time looking on documentation I cannot find a way to avoid this behavior.

Example:
```
class OpenCloseRatesViewEntry(db.Entity):
    _table_ = "openclose_rates_view"

    year = Required(int,column="year")
    month = Required(int,column="month")
    open = Required(int,column="OpenCount")
    closed = Required(int,column="ClosedCount")
    closed_same_month = Required(int,column="ClosedSameMonth")
```
[... some code later...]
```
    all_entries = OpenCloseRatesViewEntry.select()
    for entry in all_entries:
        entry.show()
```
Then I got this error
```
SELECT `openclose_rates_view`.`id`, `openclose_rates_view`.`year`, `openclose_rates_view`.`month`, `openclose_rates_view`.`OpenCount`, `openclose_rates_view`.`ClosedCount`, `openclose_rates_view`.`ClosedSameMonth`
FROM `openclose_rates_view` `openclose_rates_view`
WHERE 0 = 1

ROLLBACK
RELEASE CONNECTION
Traceback (most recent call last):
  File "/home/mike/workspace/aiolos/bugs/graphs_generator.py", line 69, in <module>
    db.generate_mapping(create_tables=False)
  File "<auto generated wrapper of generate_mapping() function>", line 2, in generate_mapping
  File "/usr/local/lib/python2.7/dist-packages/pony/utils/utils.py", line 58, in cut_traceback
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pony/orm/core.py", line 883, in generate_mapping
    elif check_tables: database.check_tables()
  File "<auto generated wrapper of check_tables() function>", line 2, in check_tables
  File "/usr/local/lib/python2.7/dist-packages/pony/utils/utils.py", line 58, in cut_traceback
    return func(*args, **kwargs)
  File "<auto generated wrapper of check_tables() function>", line 2, in check_tables
  File "/usr/local/lib/python2.7/dist-packages/pony/orm/core.py", line 413, in new_func
    try: return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pony/orm/core.py", line 948, in check_tables
    database.schema.check_tables(database.provider, connection)
  File "/usr/local/lib/python2.7/dist-packages/pony/orm/dbschema.py", line 77, in check_tables
    provider.execute(cursor, sql)
  File "<auto generated wrapper of execute() function>", line 2, in execute
  File "/usr/local/lib/python2.7/dist-packages/pony/orm/dbapiprovider.py", line 53, in wrap_dbapi_exceptions
    except dbapi_module.OperationalError as e: raise OperationalError(e)
pony.orm.dbapiprovider.OperationalError: (1054, "Unknown column 'openclose_rates_view.id' in 'field list'")
```
As you can see the problem comes in the select clause as there's not column called "id".

**Comment by sashaaero** [comment]
In Pony each entity should have a primary key. If primary key is not specified explicitly then Pony adds `id` column as primary key. You can't create entity without a primary key, but primary key can be composite. In your case you can define composite primary key from `year` and `month` attributes.
Like this
```python
class OpenCloseRatesViewEntry(db.Entity):
    _table_ = "openclose_rates_view"

    year = Required(int, column="year")
    month = Required(int, column="month")
    open = Required(int, column="OpenCount")
    closed = Required(int, column="ClosedCount")
    closed_same_month = Required(int, column="ClosedSameMonth")
    PrimaryKey(year, months)
```
Sometimes primary key for view should consist of all columns, but it's better if you can define some minimal set of columns which are unique together.

**Comment by forlayo** [comment]
Thanks for the clarifying :)
