### ISSUE TITLE
[BUG] InterfaceError: (0, '')

### ISSUE THREAD

**Issue by xunto** [ponyorm/pony#277]
```traceback
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "<string>", line 2, in application_list
  File "/usr/local/lib/python3.6/dist-packages/pony/orm/core.py", line 423, in new_func
    finally: db_session.__exit__(exc_type, exc, tb)
  File "/usr/local/lib/python3.6/dist-packages/pony/orm/core.py", line 397, in __exit__
    else: rollback()
  File "<string>", line 2, in rollback
  File "/usr/local/lib/python3.6/dist-packages/pony/utils/utils.py", line 58, in cut_traceback
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pony/orm/core.py", line 326, in rollback
    transact_reraise(RollbackException, exceptions)
  File "/usr/local/lib/python3.6/dist-packages/pony/orm/core.py", line 283, in transact_reraise
    reraise(exc_class, new_exc, tb)
  File "/usr/local/lib/python3.6/dist-packages/pony/utils/utils.py", line 85, in reraise
    try: raise exc.with_traceback(tb)
  File "/usr/local/lib/python3.6/dist-packages/pony/orm/core.py", line 323, in rollback
    try: cache.rollback()
  File "/usr/local/lib/python3.6/dist-packages/pony/orm/core.py", line 1559, in rollback
    cache.close(rollback=True)
  File "/usr/local/lib/python3.6/dist-packages/pony/orm/core.py", line 1573, in close
    try: provider.rollback(connection, cache)
  File "<string>", line 2, in rollback
  File "/usr/local/lib/python3.6/dist-packages/pony/orm/dbapiprovider.py", line 59, in wrap_dbapi_exceptions
    raise InterfaceError(e)
pony.orm.core.RollbackException: InterfaceError: (0, '')
```
Looks like it happen when you do nothing to db for some time and then do something. For example, when script waits for http request and when it get it, pony throws the exception. If you do another request after that, everything will be ok.

I had this issue with aiohttp (but i thought that it's related to threadpool that i used) and flask.

**Comment by xunto** [comment]
pony version is 0.7.1

**Comment by xunto** [comment]
Database... I had this issue with sqlite and postges.

**Comment by Achillesxu** [comment]
i got the same error, someone find some way to solve it?

**Comment by xunto** [comment]
No. But I heard that it is related to mysql driver and global cursor usage.

**Comment by Achillesxu** [comment]
how to test this? i planed to switch to sqlalchemy

**Comment by Achillesxu** [comment]
incredibly, i replace the PyMySQl using the MySQL-python, the bug had gone!

**Comment by xunto** [comment]
@Achillesxu could you provide some code? This bug driving me crazy! Did you replaced mysql driver? I didn't know there is such option. :D

**Comment by xunto** [comment]
I mean that I didn't know there is option to choose specific driver. What should I do? Just remove PyMySQl and install MySQL-python?

**Comment by xunto** [comment]
Meh, MySQL-python doesn't seem to work with python3.6. :(

**Comment by kozlovsky** [comment]
Hi @xunto , I think this issue is related to #219. You can check Pony version from GitHub, the bug should be already fixed in 1146ff1f. Before the fix, `RollbackException` masked the real problem caused by database driver, now you should be able to see the real reason for the error. I plan to make new Pony release at Monday with this fix.

**Comment by xunto** [comment]
@kozlovsky wow, new release is good news. I'll check today if problem is fixed on the lastest commit of the orm branch and will let you know.

**Comment by xunto** [comment]
```
pony.orm.dbapiprovider.OperationalError: (2013, 'Lost connection to MySQL server during query')
```

Now I caught this. Is it something with Mysql configuration or what?

**Comment by kozlovsky** [comment]
I think probably so. Some of the following links may help:
https://github.com/rstats-db/RMySQL/issues/190
https://stackoverflow.com/questions/6516943/lost-connection-to-mysql-server-during-query
https://serverfault.com/questions/739137/lost-connection-to-mysql-server-during-query

If you discover a reason for the issue, then please leave a comment here for other MySQL users.

**Comment by xunto** [comment]
Oh, that legacy. :) But it doesn't look like there are such problems with php app.

**Comment by Achillesxu** [comment]
Pony tries to use the MySQLdb driver for working with MySQL. If this module cannot be imported, Pony tries to use pymysql. See the MySQLdb and pymysql documentation for more information regarding these drivers.   from 'https://docs.ponyorm.com/api_reference.html#mysql' 
i just pip install MySQL-python, restart my program, and uninstall PyMySQL, my error dont occur again.
my error is that multiprocess(python 2.7 using PyMySQL driver) write records to mysql(5.5) database, then commit error occur frequently, the error is same as that you encounter.

**Comment by xunto** [comment]
```
max_connections = 400
max_allowed_packet = 1G
wait_timeout = 31536000
```
I'm not the one who is administrating database but asked this man to give me that. This configuration seem to solve the problem.

**Comment by xunto** [comment]
I think everything is OK now. But I have more mysql related problems! I close this one for now.
