### ISSUE TITLE
ProgrammingError with many to many relationship

### ISSUE THREAD

**Issue by NiklasRosenstein** [ponyorm/pony#290]
```python
from pony.orm import *


sql_debug(True)
db = Database()


class Artist(db.Entity):
    id = PrimaryKey(int, auto=True)
    songs = Set('Song')


class Song(db.Entity):
    id = PrimaryKey(int, auto=True)
    artists = Set(Artist)
    albums = Set('Album')


class Album(db.Entity):
    id = PrimaryKey(int, auto=True)
    songs = Set(Song)


db.generate_mapping()
```

Gives me

```
GET NEW CONNECTION
RELEASE CONNECTION
GET CONNECTION FROM THE LOCAL POOL
SWITCH TO AUTOCOMMIT MODE
SELECT "album"."id"
FROM "album" "album"
WHERE 0 = 1

ROLLBACK
RELEASE CONNECTION
Traceback (most recent call last):
  File "/home/niklas/Desktop/test/nodepy_modules/.pip/lib/python3.6/site-packages/pony/orm/dbapiprovider.py", line 48, in wrap_dbapi_exceptions
    try: return func(provider, *args, **kwargs)
  File "/home/niklas/Desktop/test/nodepy_modules/.pip/lib/python3.6/site-packages/pony/orm/dbproviders/postgres.py", line 215, in execute
    if arguments is None: cursor.execute(sql)
psycopg2.ProgrammingError: relation "album" does not exist
LINE 2: FROM "album" "album"
             ^


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/niklas/repos/nodepy/nodepy.py", line 1977, in _main
    module.exec_()
  File "/home/niklas/repos/nodepy/nodepy.py", line 857, in exec_
    self.loader.exec_(self)
  File "/home/niklas/repos/nodepy/nodepy.py", line 772, in exec_
    exec(code, vars(module.namespace))
  File "/home/niklas/Desktop/test/models.py", line 23, in <module>
    db.generate_mapping()
  File "<string>", line 2, in generate_mapping
  File "/home/niklas/Desktop/test/nodepy_modules/.pip/lib/python3.6/site-packages/pony/utils/utils.py", line 58, in cut_traceback
    return func(*args, **kwargs)
  File "/home/niklas/Desktop/test/nodepy_modules/.pip/lib/python3.6/site-packages/pony/orm/core.py", line 886, in generate_mapping
    elif check_tables: database.check_tables()
  File "<string>", line 2, in check_tables
  File "/home/niklas/Desktop/test/nodepy_modules/.pip/lib/python3.6/site-packages/pony/utils/utils.py", line 58, in cut_traceback
    return func(*args, **kwargs)
  File "<string>", line 2, in check_tables
  File "/home/niklas/Desktop/test/nodepy_modules/.pip/lib/python3.6/site-packages/pony/orm/core.py", line 417, in new_func
    try: return func(*args, **kwargs)
  File "/home/niklas/Desktop/test/nodepy_modules/.pip/lib/python3.6/site-packages/pony/orm/core.py", line 951, in check_tables
    database.schema.check_tables(database.provider, connection)
  File "/home/niklas/Desktop/test/nodepy_modules/.pip/lib/python3.6/site-packages/pony/orm/dbschema.py", line 77, in check_tables
    provider.execute(cursor, sql)
  File "<string>", line 2, in execute
  File "/home/niklas/Desktop/test/nodepy_modules/.pip/lib/python3.6/site-packages/pony/orm/dbapiprovider.py", line 50, in wrap_dbapi_exceptions
    except dbapi_module.ProgrammingError as e: raise ProgrammingError(e)
pony.orm.dbapiprovider.ProgrammingError: relation "album" does not exist
LINE 2: FROM "album" "album"
             ^
```

Using PostgreSQL as a provider. Any idea what's going on?

**Comment by kozlovsky** [comment]
By default, `db.generate_mapping()` executed with options `create_tables=False` and `check_tables=True`. It sees that the table is not exists in the database and generate this error. See the documentation [here](https://docs.ponyorm.com/api_reference.html?highlight=create_tables#Database.generate_mapping).

You need to specify `create_tables=True` option at least during the first start in order to create tables.

**Comment by NiklasRosenstein** [comment]
Thanks, I forgot about that. Should have followed the tutorial for a second time. :) Sorry for the troubles.

**Comment by chakgou** [comment]
Catch error like this:
```
try:
    db.generate_mapping(create_tables=True)
except Exception as ex:
    pass
```
if already exists entity in bdd; it pass without application crash
