### ISSUE TITLE
pony.orm.dbapiprovider.OperationalError: no such table: 

### ISSUE THREAD

**Issue by nadermx** [ponyorm/pony#354]
Referencing this issue https://github.com/ponyorm/pony/issues/336 using the exact same set up, pony migration now spits out this error when trying to make the first `migrate.py make`

```python migrate.py make
Traceback (most recent call last):
  File "/home/john/.virtualenvs/hw/lib/python3.5/site-packages/pony/orm/dbapiprovider.py", line 56, in wrap_dbapi_exceptions
    try: return func(provider, *args, **kwargs)
  File "/home/john/.virtualenvs/hw/lib/python3.5/site-packages/pony/orm/dbapiprovider.py", line 316, in execute
    new_id = provider._execute(cursor, sql, arguments, returning_id)
  File "/home/john/.virtualenvs/hw/lib/python3.5/site-packages/pony/orm/dbapiprovider.py", line 324, in _execute
    if arguments is None: cursor.execute(sql)
sqlite3.OperationalError: no such table: answer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "migrate.py", line 2, in <module>
    from app import models
  File "/home/john/PycharmProjects/hospedajeweb/app/__init__.py", line 28, in <module>
    models.db.generate_mapping(allow_auto_upgrade=True)
  File "<string>", line 2, in generate_mapping
  File "/home/john/.virtualenvs/hw/lib/python3.5/site-packages/pony/orm/core.py", line 464, in new_func
    result = func(*args, **kwargs)
  File "/home/john/.virtualenvs/hw/lib/python3.5/site-packages/pony/orm/core.py", line 950, in generate_mapping
    if check_tables: schema.check_tables(connection)
  File "/home/john/.virtualenvs/hw/lib/python3.5/site-packages/pony/orm/dbschema.py", line 102, in check_tables
    provider.execute(cursor, sql)
  File "<string>", line 2, in execute
  File "/home/john/.virtualenvs/hw/lib/python3.5/site-packages/pony/orm/dbapiprovider.py", line 64, in wrap_dbapi_exceptions
    raise OperationalError(e)
pony.orm.dbapiprovider.OperationalError: no such table: answer
(hw) john@john-XPS-13-9343:~/PycharmProjects/hospedajeweb$ python migrate.py make
Traceback (most recent call last):
  File "/home/john/.virtualenvs/hw/lib/python3.5/site-packages/pony/orm/dbapiprovider.py", line 56, in wrap_dbapi_exceptions
    try: return func(provider, *args, **kwargs)
  File "/home/john/.virtualenvs/hw/lib/python3.5/site-packages/pony/orm/dbapiprovider.py", line 316, in execute
    new_id = provider._execute(cursor, sql, arguments, returning_id)
  File "/home/john/.virtualenvs/hw/lib/python3.5/site-packages/pony/orm/dbapiprovider.py", line 324, in _execute
    if arguments is None: cursor.execute(sql)
sqlite3.OperationalError: no such table: answer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "migrate.py", line 2, in <module>
    from app import models
  File "/home/john/PycharmProjects/hospedajeweb/app/__init__.py", line 28, in <module>
    models.db.generate_mapping(allow_auto_upgrade=True)
  File "<string>", line 2, in generate_mapping
  File "/home/john/.virtualenvs/hw/lib/python3.5/site-packages/pony/orm/core.py", line 464, in new_func
    result = func(*args, **kwargs)
  File "/home/john/.virtualenvs/hw/lib/python3.5/site-packages/pony/orm/core.py", line 950, in generate_mapping
    if check_tables: schema.check_tables(connection)
  File "/home/john/.virtualenvs/hw/lib/python3.5/site-packages/pony/orm/dbschema.py", line 102, in check_tables
    provider.execute(cursor, sql)
  File "<string>", line 2, in execute
  File "/home/john/.virtualenvs/hw/lib/python3.5/site-packages/pony/orm/dbapiprovider.py", line 64, in wrap_dbapi_exceptions
    raise OperationalError(e)
pony.orm.dbapiprovider.OperationalError: no such table: answer
(hw) john@john-XPS-13-9343:~/PycharmProjects/hospedajeweb$ python migrate.py make
Traceback (most recent call last):
  File "/home/john/.virtualenvs/hw/lib/python3.5/site-packages/pony/orm/dbapiprovider.py", line 56, in wrap_dbapi_exceptions
    try: return func(provider, *args, **kwargs)
  File "/home/john/.virtualenvs/hw/lib/python3.5/site-packages/pony/orm/dbapiprovider.py", line 316, in execute
    new_id = provider._execute(cursor, sql, arguments, returning_id)
  File "/home/john/.virtualenvs/hw/lib/python3.5/site-packages/pony/orm/dbapiprovider.py", line 324, in _execute
    if arguments is None: cursor.execute(sql)
sqlite3.OperationalError: no such table: answer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "migrate.py", line 2, in <module>
    from app import models
  File "/home/john/PycharmProjects/hospedajeweb/app/__init__.py", line 28, in <module>
    models.db.generate_mapping(allow_auto_upgrade=True)
  File "<string>", line 2, in generate_mapping
  File "/home/john/.virtualenvs/hw/lib/python3.5/site-packages/pony/orm/core.py", line 464, in new_func
    result = func(*args, **kwargs)
  File "/home/john/.virtualenvs/hw/lib/python3.5/site-packages/pony/orm/core.py", line 950, in generate_mapping
    if check_tables: schema.check_tables(connection)
  File "/home/john/.virtualenvs/hw/lib/python3.5/site-packages/pony/orm/dbschema.py", line 102, in check_tables
    provider.execute(cursor, sql)
  File "<string>", line 2, in execute
  File "/home/john/.virtualenvs/hw/lib/python3.5/site-packages/pony/orm/dbapiprovider.py", line 64, in wrap_dbapi_exceptions
    raise OperationalError(e)
pony.orm.dbapiprovider.OperationalError: no such table: answer
```

**Comment by kozlovsky** [comment]
Hi Nader!

When using Pony with migrations, you should use two separate API calls to connect to the database:

1) From the `migrate.py` script you need to call `db.migrate(**params)` to connect to potentially empty database and create or alter database tables.

2) From the main application, you need to use `db.connect(**params)` method to connect to the database which already has tables created by `migrate.py` script. The `db.connect(**params)` call is equivalent to calling sequentially `db.bind(**params)` and then `db.generate_mapping()`

The problem in your code is in the following lines:
```python
# migrate.py
from app import models

# app/__init__.py
models.db.generate_mapping(allow_auto_upgrade=True)
```

When your `migrate.py` imports `models`, it executes `app/__init__.py` as well. So, `db.generate_maping` is called during the execution of `migrate.py`, which is incorrect.

To solve the problem, you should move `generate_mapping` call from `app/__init__.py` to some submodule like `app/main.py` which is not imported when `from app import models` line of `migrate.py` module is executed

**Comment by nadermx** [comment]
@kozlovsky I actually tried moving it outside, it still returns the error 
```
python run.py
GET NEW CONNECTION
RELEASE CONNECTION
GET CONNECTION FROM THE LOCAL POOL
PRAGMA foreign_keys = false
BEGIN IMMEDIATE TRANSACTION
CREATE TABLE pony_version (id INT PRIMARY KEY, pony_version VARCHAR(20) NOT NULL)

insert into pony_version values (1, '0.8-dev')

SELECT "answer"."id", "answer"."user", "answer"."question", "answer"."correct"
FROM "answer" "answer"
WHERE 0 = 1

ROLLBACK
PRAGMA foreign_keys = true
CLOSE CONNECTION
Traceback (most recent call last):
  File "/home/john/.virtualenvs/hw/lib/python3.5/site-packages/pony/orm/dbapiprovider.py", line 56, in wrap_dbapi_exceptions
    try: return func(provider, *args, **kwargs)
  File "/home/john/.virtualenvs/hw/lib/python3.5/site-packages/pony/orm/dbapiprovider.py", line 316, in execute
    new_id = provider._execute(cursor, sql, arguments, returning_id)
  File "/home/john/.virtualenvs/hw/lib/python3.5/site-packages/pony/orm/dbapiprovider.py", line 324, in _execute
    if arguments is None: cursor.execute(sql)
sqlite3.OperationalError: no such table: answer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run.py", line 5, in <module>
    models.db.generate_mapping(allow_auto_upgrade=True)
  File "<string>", line 2, in generate_mapping
  File "/home/john/.virtualenvs/hw/lib/python3.5/site-packages/pony/orm/core.py", line 464, in new_func
    result = func(*args, **kwargs)
  File "/home/john/.virtualenvs/hw/lib/python3.5/site-packages/pony/orm/core.py", line 950, in generate_mapping
    if check_tables: schema.check_tables(connection)
  File "/home/john/.virtualenvs/hw/lib/python3.5/site-packages/pony/orm/dbschema.py", line 102, in check_tables
    provider.execute(cursor, sql)
  File "<string>", line 2, in execute
  File "/home/john/.virtualenvs/hw/lib/python3.5/site-packages/pony/orm/dbapiprovider.py", line 64, in wrap_dbapi_exceptions
    raise OperationalError(e)
pony.orm.dbapiprovider.OperationalError: no such table: answer

```

I also tried a new database, and ran migartions first.  This problem also seems to show up.

```
python migrate.py make
GET NEW CONNECTION
RELEASE CONNECTION
Written: migrations/0001_initial.py
DISCONNECT
```
Then I apply the migrations
```
python migrate.py apply
GET NEW CONNECTION
RELEASE CONNECTION
GET NEW CONNECTION
RELEASE CONNECTION
GET CONNECTION FROM THE LOCAL POOL
PRAGMA foreign_keys = false
BEGIN IMMEDIATE TRANSACTION
SELECT "migration"."id", "migration"."name", "migration"."applied"
FROM "migration" "migration"
WHERE 0 = 1

COMMIT
PRAGMA foreign_keys = true
CLOSE CONNECTION
GET NEW CONNECTION
SWITCH TO AUTOCOMMIT MODE
SELECT DISTINCT "m"."name"
FROM "migration" "m"

RELEASE CONNECTION

All migrations are applied.
DISCONNECT
DISCONNECT
```
But when when I try and list it says nothing exists

```
python migrate.py list
GET NEW CONNECTION
RELEASE CONNECTION
GET CONNECTION FROM THE LOCAL POOL
SWITCH TO AUTOCOMMIT MODE
SELECT "m"."id", "m"."name", "m"."applied"
FROM "migration" "m"
LIMIT 1

No Migration table. Please apply the initial migration.
RELEASE CONNECTION
DISCONNECT
```

**Comment by kozlovsky** [comment]
It looks strange. This is how I understand what is happened:

1) When you executed `python run.py`, the database was still empty, so the `answer` table was not found. This is normal.

2) After `python migrate.py make`, migration file with initial entity definitions should be created. You can look this file in order to see is it empty or contains entity definitions.

3) `python migrate.py apply` command should execute initial migration and create tables. Here we can see that for some strange reason no unapplied migrations were found. But anyway, the `migration` table exists in the database, and the query `SELECT ... FROM "migration"` does not produce any error.

4) `python migrate.py list` should read rows from `migration` table and display the names of successfully applied migrations. We can see the error that `migration` table does not exist. But previous `apply` command was able to successfully access `migration` table.

Is it possible that between calling `python migrate.py apply` and `python migrate.py list` some database settings were changed and the last command connected to another empty database?

**Comment by nadermx** [comment]
Fixed, didn't realize I only needed to now run `db.connect` and not `db.connect` and then `db.bind`
