### ISSUE TITLE
TypeError: Unsupported type 'Migration'

### ISSUE THREAD

**Issue by nadermx** [ponyorm/pony#356]
Trying out migrations still, this time instead of trying it since it was not working with sqlite, trying it with psql 
When trying to run migration after running make, and apply, trying to run list outputs this
```
python migrate.py list
GET NEW CONNECTION
RELEASE CONNECTION
GET CONNECTION FROM THE LOCAL POOL
COMMIT
CLOSE CONNECTION
GET NEW CONNECTION
SWITCH TO AUTOCOMMIT MODE
SELECT "m"."id", "m"."name", "m"."applied"
FROM "migration" "m"
LIMIT 1

ROLLBACK
RELEASE CONNECTION
DISCONNECT
Traceback (most recent call last):
  File "migrate.py", line 5, in <module>
    models.db.migrate(allow_auto_upgrade=True, provider=app.config['DB_PROVIDER'], **app.config['DB_CONFIG'])
  File "/home/john/.virtualenvs/hw/lib/python3.5/site-packages/pony/orm/core.py", line 684, in migrate
    return migrate(self, command)
  File "/home/john/.virtualenvs/hw/lib/python3.5/site-packages/pony/migrate/command.py", line 61, in migrate
    return _migrate(db, cmd, **kwargs)
  File "/home/john/.virtualenvs/hw/lib/python3.5/site-packages/pony/migrate/command.py", line 98, in _migrate
    show_migrations(db=db)
  File "<string>", line 2, in show_migrations
  File "/home/john/.virtualenvs/hw/lib/python3.5/site-packages/pony/orm/core.py", line 464, in new_func
    result = func(*args, **kwargs)
  File "/home/john/.virtualenvs/hw/lib/python3.5/site-packages/pony/migrate/command.py", line 153, in show_migrations
    saved = orm.select((m.name, m.applied) for m in db.Migration if m.name in names).order_by(2)[:]
  File "/home/john/.virtualenvs/hw/lib/python3.5/site-packages/pony/orm/core.py", line 5507, in select
    return make_query(args, frame_depth=cut_traceback_depth+1)
  File "/home/john/.virtualenvs/hw/lib/python3.5/site-packages/pony/orm/core.py", line 5503, in make_query
    return Query(code_key, tree.code, globals, locals, cells, left_join)
  File "/home/john/.virtualenvs/hw/lib/python3.5/site-packages/pony/orm/core.py", line 5606, in __init__
    vars, vartypes = extract_vars(filter_num, extractors, globals, locals, cells)
  File "/home/john/.virtualenvs/hw/lib/python3.5/site-packages/pony/orm/core.py", line 5593, in extract_vars
    vartypes[key] = get_normalized_type_of(value)
  File "/home/john/.virtualenvs/hw/lib/python3.5/site-packages/pony/orm/ormtypes.py", line 135, in get_normalized_type_of
    if t is tuple: return tuple(get_normalized_type_of(item) for item in value)
  File "/home/john/.virtualenvs/hw/lib/python3.5/site-packages/pony/orm/ormtypes.py", line 135, in <genexpr>
    if t is tuple: return tuple(get_normalized_type_of(item) for item in value)
  File "/home/john/.virtualenvs/hw/lib/python3.5/site-packages/pony/orm/ormtypes.py", line 148, in get_normalized_type_of
    return normalize_type(t)
  File "/home/john/.virtualenvs/hw/lib/python3.5/site-packages/pony/orm/ormtypes.py", line 161, in normalize_type
    throw(TypeError, 'Unsupported type %r' % t.__name__)
  File "/home/john/.virtualenvs/hw/lib/python3.5/site-packages/pony/utils/utils.py", line 106, in throw
    raise exc
TypeError: Unsupported type 'Migration'

```

Here is the following models

```
#models.py
# -*- coding: utf-8 -*-
from flask import current_app
from datetime import datetime
from pony.orm import *
from passlib.hash import bcrypt_sha256
from itsdangerous import (TimedJSONWebSignatureSerializer
as Serializer, BadSignature, SignatureExpired)
from flask_login import UserMixin

db = Database()

class User(UserMixin, db.Entity):
    username = Optional(unicode)
    password_hash = Optional(unicode)
    email = Optional(unicode)
    dt_registered = Optional(datetime, default=datetime.now)
    dt_last_visit = Optional(datetime, default=datetime.now)
    verified = Optional(bool, default=False)
    failed_login = Optional(int)
    last_failed_login = Optional(datetime, default=datetime.now)
    tickets = Set(lambda: Ticket)
    ticket_comentarios = Set(lambda: TicketComentarios)
    servidores = Set(lambda: Servidor)
    pagos = Set(lambda: Pago)
    credito = Optional(float)
    nombre = Optional(unicode)
    apellido = Optional(unicode)
    telefono = Optional(unicode)
    direccion = Optional(unicode)
    dirrecion_extra = Optional(unicode)
    cuidad = Optional(unicode)
    codigo_postal = Optional(unicode)
    estado = Optional(unicode)
    empresa = Optional(unicode)
    networking = Set(lambda: Dns)
    snapshots = Set(lambda: Snapshot)
    ssh_llaves = Set(lambda: SshLlaves)
    def hash_password(self, password):
        self.password_hash = bcrypt_sha256.hash(password)

    def verify_password(self, password):
        return bcrypt_sha256.verify(password, self.password_hash)

    def generate_auth_email_token(self):
        s = Serializer(current_app.config['SECRET_KEY'], expires_in=60 * 60 * 24)
        return s.dumps({'id': self.id})

    @staticmethod
    def verify_auth_token(token):
        s = Serializer(current_app.config['SECRET_KEY'])
        try:
            data = s.loads(token)
        except SignatureExpired:
            return None  # valid token, but expired
        except BadSignature:
            return None  # invalid token
        if not data['id']:
            return None
        user = User[data['id']]
        return user

class Ticket(db.Entity):
    user = Optional(lambda: User)
    tema = Optional(unicode)
    contenido = Optional(unicode)
    status = Optional(unicode)
    dia_creado = Optional(datetime, default=datetime.now)
    servidor = Optional(lambda:Servidor)
    snapshot = Optional(lambda:Snapshot)
    categoria = Optional(unicode)
    cometarios = Set(lambda: TicketComentarios)
    archivo = Optional(unicode)

class TicketComentarios(db.Entity):
    user = Optional(lambda: User)
    ticket = Optional(lambda:Ticket)
    comentario = Optional(unicode)
    dia_creado = Optional(datetime, default=datetime.now)
    archivo = Optional(unicode)

class Servidor(db.Entity):
    user = Optional(lambda: User)
    ubicacion = Optional(unicode)
    tipo = Optional(unicode)
    tamano = Optional(unicode)
    ipvseis = Optional(unicode)
    ipvcuatro = Optional(unicode)
    sshkeys = Optional(unicode)
    hostname = Optional(unicode)
    nombre = Optional(unicode)
    tickets = Set(lambda:Ticket)
    dia_creado = Optional(datetime, default=datetime.now)

class Snapshot(db.Entity):
    user = Optional(lambda: User)
    ubicacion = Optional(unicode)
    tipo = Optional(unicode)
    tamano = Optional(unicode)
    ipvseis = Optional(unicode)
    ipvcuatro = Optional(unicode)
    sshkeys = Optional(unicode)
    hostname = Optional(unicode)
    nombre = Optional(unicode)
    tickets = Set(lambda:Ticket)
    dia_creado = Optional(datetime, default=datetime.now)

class SshLlaves(db.Entity):
    user = Optional(lambda: User)
    nombre = Optional(unicode)

class Pago(db.Entity):
    user = Optional(lambda: User)
    stripe = Optional(Json)
    paypal = Optional(Json)
    dia = Optional(datetime, default=datetime.now)


class Dns(db.Entity):
    user = Optional(lambda: User)

sql_debug(True)
```

As suggested in another issue, I put the `db.connect` in run.py vs the `__init__.py`

```
# -*- coding: utf-8 -*-
# Run a test server.
from app import app, models


models.db.connect(allow_auto_upgrade=True, provider=app.config['DB_PROVIDER'], **app.config['DB_CONFIG'])
app.wsgi_app = models.db_session(app.wsgi_app)

if __name__ == '__main__':
    app.run(host='0.0.0.0', port=5000, debug=True, threaded=True)
    # app.run(debug=True)
```

And my migrate.py file is 
```
#!/usr/bin/env python
from app import models, app
import config

models.db.migrate(allow_auto_upgrade=True, provider=app.config['DB_PROVIDER'], **app.config['DB_CONFIG'])
```

And of course the config.py
```
DB_PROVIDER = 'postgres'
DB_CONFIG = {
  'user': 'john',
  'password': 'password',
  'database' :'hw',
  'host' : 'localhost'
}
```

**Comment by kozlovsky** [comment]
Johnathan, thanks for reporting!
The `list` command should work now!
