### ISSUE TITLE
pony.orm.dbapiprovider.ProgrammingError: column "ubicacion" cannot be cast automatically to type jsonb

### ISSUE THREAD

**Issue by nadermx** [ponyorm/pony#362]
Hey Pony, once again thanks for everything you're doing, this is turning out awesome.

I'm trying to use the migration tool, and it's working fine, but when I changed a unicode to a json it spit this out

```
Applied:
Traceback (most recent call last):
  File "/home/john/.virtualenvs/hw/lib/python3.6/site-packages/pony/orm/dbapiprovider.py", line 53, in wrap_dbapi_exceptions
    return func(provider, *args, **kwargs)
  File "/home/john/.virtualenvs/hw/lib/python3.6/site-packages/pony/orm/dbapiprovider.py", line 316, in execute
    new_id = provider._execute(cursor, sql, arguments, returning_id)
  File "/home/john/.virtualenvs/hw/lib/python3.6/site-packages/pony/orm/dbproviders/postgres.py", line 279, in _execute
    if arguments is None: cursor.execute(sql)
psycopg2.ProgrammingError: column "ubicacion" cannot be cast automatically to type jsonb
HINT:  You might need to specify "USING ubicacion::jsonb".


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "migrate.py", line 5, in <module>
    models.db.migrate(**app.config['DB_PARAMS'])
  File "/home/john/.virtualenvs/hw/lib/python3.6/site-packages/pony/orm/core.py", line 684, in migrate
    return migrate(self, command)
  File "/home/john/.virtualenvs/hw/lib/python3.6/site-packages/pony/migrate/command.py", line 61, in migrate
    return _migrate(db, cmd, **kwargs)
  File "/home/john/.virtualenvs/hw/lib/python3.6/site-packages/pony/migrate/command.py", line 102, in _migrate
    graph.apply(db=db, is_fake=fake_initial, dry_run=dry, name_start=start, name_end=end)
  File "/home/john/.virtualenvs/hw/lib/python3.6/site-packages/pony/migrate/migration.py", line 408, in apply
    prev_db.execute(sql)
  File "/home/john/.virtualenvs/hw/lib/python3.6/site-packages/pony/orm/core.py", line 838, in execute
    return database._exec_raw_sql(sql, globals, locals, frame_depth=cut_traceback_depth+1, start_transaction=True)
  File "/home/john/.virtualenvs/hw/lib/python3.6/site-packages/pony/orm/core.py", line 850, in _exec_raw_sql
    return database._exec_sql(adapted_sql, arguments, False, start_transaction)
  File "/home/john/.virtualenvs/hw/lib/python3.6/site-packages/pony/orm/core.py", line 911, in _exec_sql
    connection = cache.reconnect(e)
  File "/home/john/.virtualenvs/hw/lib/python3.6/site-packages/pony/orm/core.py", line 1613, in reconnect
    if not provider.should_reconnect(exc): reraise(*sys.exc_info())
  File "/home/john/.virtualenvs/hw/lib/python3.6/site-packages/pony/utils/utils.py", line 95, in reraise
    try: raise exc.with_traceback(tb)
  File "/home/john/.virtualenvs/hw/lib/python3.6/site-packages/pony/orm/core.py", line 909, in _exec_sql
    try: new_id, duration = provider.execute(cursor, sql, arguments, returning_id)
  File "<string>", line 2, in execute
  File "/home/john/.virtualenvs/hw/lib/python3.6/site-packages/pony/orm/dbapiprovider.py", line 59, in wrap_dbapi_exceptions
    except dbapi_module.ProgrammingError as e: raise ProgrammingError(e)
pony.orm.dbapiprovider.ProgrammingError: column "ubicacion" cannot be cast automatically to type jsonb
HINT:  You might need to specify "USING ubicacion::jsonb".

```

**Comment by kozlovsky** [comment]
Hi Johnathan! Thank you for testing migrations! We found the reason of the error, and will fix it soon

**Comment by kozlovsky** [comment]
Should work now
