### ISSUE TITLE
NameError: name 'PayPal' is not defined

### ISSUE THREAD

**Issue by nadermx** [ponyorm/pony#368]
Trying to add two classes wth lambda via migrations.  
```
class Pago(db.Entity):
    user = Optional(lambda: User)
    stripe = Set(lambda: Stripe)
    paypal = Set(lambda: PayPal)
    dia = Optional(datetime, default=datetime.utcnow())

class Stripe(db.Entity):
    pago = Optional(lambda: Pago)
    customer = Optional(Json)
    cargo = Optional(Json)

class PayPal(db.Entity):
    pago = Required(lambda: Pago)

```
And I get this error

```
GET NEW CONNECTION
RELEASE CONNECTION
GET NEW CONNECTION
RELEASE CONNECTION
DISCONNECT
DISCONNECT
Traceback (most recent call last):
  File "migrate.py", line 5, in <module>
    models.db.migrate(**app.config['DB_PARAMS'])
  File "/home/john/.virtualenvs/hw/lib/python3.6/site-packages/pony/orm/core.py", line 684, in migrate
    return migrate(self, command)
  File "/home/john/.virtualenvs/hw/lib/python3.6/site-packages/pony/migrate/command.py", line 61, in migrate
    return _migrate(db, cmd, **kwargs)
  File "/home/john/.virtualenvs/hw/lib/python3.6/site-packages/pony/migrate/command.py", line 96, in _migrate
    return graph.make(db=db, empty=empty, custom=custom, description=name)
  File "/home/john/.virtualenvs/hw/lib/python3.6/site-packages/pony/migrate/migration.py", line 242, in make
    upgrade_db(prev_db, namespace)
  File "/home/john/.virtualenvs/hw/lib/python3.6/site-packages/pony/migrate/migration.py", line 53, in upgrade_db
    op.apply(db)
  File "/home/john/.virtualenvs/hw/lib/python3.6/site-packages/pony/migrate/diagram_ops.py", line 127, in apply
    rentity = op._get_rentity(db)
  File "/home/john/.virtualenvs/hw/lib/python3.6/site-packages/pony/migrate/diagram_ops.py", line 119, in _get_rentity
    rentity = rentity()
  File "<string>", line 16, in <lambda>
NameError: name 'PayPal' is not defined


```

**Comment by sashaaero** [comment]
Hi, @nadermx ! These two classes you mean `Stripe` and `PayPal`?

**Comment by nadermx** [comment]
@sashaaero correct

**Comment by sashaaero** [comment]
Ok. I was able to reproduce this. Working on it.
Btw your usage of `default=datetime.utcnow()` seems incorrect, you probably need to remove the parenthesises.

**Comment by sashaaero** [comment]
Hello! Fix is already on GitHub.
You should delete your last migration file and make new one.
