### ISSUE TITLE
pony.orm.dbapiprovider.ProgrammingError: cannot cast type jsonb to integer

### ISSUE THREAD

**Issue by nadermx** [ponyorm/pony#379]
Trying to change a json blob to another record.  

Before it looked like this

```
class Dns(db.Entity):
    user = Optional(lambda: User)
    dominio = Optional(unicode, unique=True)
    records = Optional(Json)
    dia_creado = Optional(datetime, default=datetime.utcnow())

```

And I'm trying to change it too
```
class Dns(db.Entity):
    user = Optional(lambda: User)
    dominio = Optional(unicode, unique=True)
    records = Optional(lambda: Record)
    dia_creado = Optional(datetime, default=datetime.utcnow())

class Record(db.Entity):
    dns = Optional(lambda: Dns)
    type = Optional(unicode)
    hostname = Optional(unicode)
    value = Optional(unicode)
    ttl = Optional(unicode)
```

but I'm getting the following error when trying to run my `migrate apply`

```
python migrate.py apply
GET NEW CONNECTION
RELEASE CONNECTION
GET NEW CONNECTION
RELEASE CONNECTION
GET CONNECTION FROM THE LOCAL POOL
SELECT "migration"."id", "migration"."name", "migration"."applied"
FROM "migration" "migration"
WHERE 0 = 1

COMMIT
CLOSE CONNECTION
GET NEW CONNECTION
SWITCH TO AUTOCOMMIT MODE
SELECT DISTINCT "m"."name"
FROM "migration" "m"

RELEASE CONNECTION
GET NEW CONNECTION
RELEASE CONNECTION
GET NEW CONNECTION
RELEASE CONNECTION
Applied:
GET CONNECTION FROM THE LOCAL POOL
CREATE TABLE "record" (
  "hostname" TEXT NOT NULL,
  "id" SERIAL CONSTRAINT "pk_record" PRIMARY KEY,
  "ttl" TEXT NOT NULL,
  "type" TEXT NOT NULL,
  "value" TEXT NOT NULL
)

ALTER TABLE "dns" ALTER COLUMN "records" TYPE INTEGER USING "records"::INTEGER

ROLLBACK
CLOSE CONNECTION
DISCONNECT
DISCONNECT
DISCONNECT
DISCONNECT
Traceback (most recent call last):
  File "/home/john/.virtualenvs/hw/lib/python3.6/site-packages/pony/orm/dbapiprovider.py", line 53, in wrap_dbapi_exceptions
    return func(provider, *args, **kwargs)
  File "/home/john/.virtualenvs/hw/lib/python3.6/site-packages/pony/orm/dbapiprovider.py", line 319, in execute
    new_id = provider._execute(cursor, sql, arguments, returning_id)
  File "/home/john/.virtualenvs/hw/lib/python3.6/site-packages/pony/orm/dbproviders/postgres.py", line 290, in _execute
    if arguments is None: cursor.execute(sql)
psycopg2.ProgrammingError: cannot cast type jsonb to integer
LINE 1: ...ALTER COLUMN "records" TYPE INTEGER USING "records"::INTEGER
                                                              ^


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "migrate.py", line 5, in <module>
    models.db.migrate(**app.config['DB_PARAMS'])
  File "/home/john/.virtualenvs/hw/lib/python3.6/site-packages/pony/orm/core.py", line 690, in migrate
    return migrate(self, command)
  File "/home/john/.virtualenvs/hw/lib/python3.6/site-packages/pony/migrate/command.py", line 61, in migrate
    return _migrate(db, cmd, **kwargs)
  File "/home/john/.virtualenvs/hw/lib/python3.6/site-packages/pony/migrate/command.py", line 102, in _migrate
    graph.apply(db=db, is_fake=fake_initial, dry_run=dry, name_start=start, name_end=end)
  File "/home/john/.virtualenvs/hw/lib/python3.6/site-packages/pony/migrate/migration.py", line 408, in apply
    prev_db.execute(sql)
  File "/home/john/.virtualenvs/hw/lib/python3.6/site-packages/pony/orm/core.py", line 844, in execute
    return database._exec_raw_sql(sql, globals, locals, frame_depth=cut_traceback_depth+1, start_transaction=True)
  File "/home/john/.virtualenvs/hw/lib/python3.6/site-packages/pony/orm/core.py", line 856, in _exec_raw_sql
    return database._exec_sql(adapted_sql, arguments, False, start_transaction)
  File "/home/john/.virtualenvs/hw/lib/python3.6/site-packages/pony/orm/core.py", line 917, in _exec_sql
    connection = cache.reconnect(e)
  File "/home/john/.virtualenvs/hw/lib/python3.6/site-packages/pony/orm/core.py", line 1621, in reconnect
    if not provider.should_reconnect(exc): reraise(*sys.exc_info())
  File "/home/john/.virtualenvs/hw/lib/python3.6/site-packages/pony/utils/utils.py", line 95, in reraise
    try: raise exc.with_traceback(tb)
  File "/home/john/.virtualenvs/hw/lib/python3.6/site-packages/pony/orm/core.py", line 915, in _exec_sql
    try: new_id, duration = provider.execute(cursor, sql, arguments, returning_id)
  File "<string>", line 2, in execute
  File "/home/john/.virtualenvs/hw/lib/python3.6/site-packages/pony/orm/dbapiprovider.py", line 59, in wrap_dbapi_exceptions
    except dbapi_module.ProgrammingError as e: raise ProgrammingError(e)
pony.orm.dbapiprovider.ProgrammingError: cannot cast type jsonb to integer
LINE 1: ...ALTER COLUMN "records" TYPE INTEGER USING "records"::INTEGER

```

**Comment by sashaaero** [comment]
Should work now if column was empty or it has integers only
