### ISSUE TITLE
"db_session required" exception when working with aync def coroutines

### ISSUE THREAD

**Issue by amireldor** [ponyorm/pony#380]
Hey there. I'm having an issue that reminds #126 which should've been resolved. I'm also using tornado. I've managed to reproduce it with this minimal code:

https://gist.github.com/amireldor/3c7f1701761d6c92855b868e5df07af0

I wrap a coroutine (`async def`) with `db_session` but an exception is thrown when doing a database action inside the coroutine. Regular wrapped functions or with blocks are fine.

This is Python 3.6.5 and pony 0.7.6; getting "pony.orm.core.TransactionError: db_session is required when working with the database".

**Comment by kozlovsky** [comment]
Thanks for reporting, it should work now!

**Comment by ranisalt** [comment]
It does not. The following code:

```python
class AuthCheckHandler(BaseHandler):
    @orm.db_session
    async def get(self):
        user = self.current_user
        if user:
            self.finish({
                'user': user.to_dict(only=['first_name', 'last_name']),
            })
```
throws
```
Traceback (most recent call last):
      File "/home/rsa/swartz/.venv/lib/python3.7/site-packages/pony/orm/core.py", line 544, in new_gen_func
        output = wrapped_interact(iterator)
      File "/home/rsa/swartz/.venv/lib/python3.7/site-packages/pony/orm/core.py", line 531, in wrapped_interact
        rollback_and_reraise(sys.exc_info())
      File "/home/rsa/swartz/.venv/lib/python3.7/site-packages/pony/orm/core.py", line 327, in rollback_and_reraise
        reraise(*exc_info)
      File "/home/rsa/swartz/.venv/lib/python3.7/site-packages/pony/utils/utils.py", line 118, in reraise
        try: raise exc.with_traceback(tb)
      File "/home/rsa/swartz/.venv/lib/python3.7/site-packages/pony/orm/core.py", line 521, in wrapped_interact
        output = interact(iterator, input, exc_info)
      File "/home/rsa/swartz/.venv/lib/python3.7/site-packages/pony/orm/core.py", line 494, in interact
        return next(iterator) if input is None else iterator.send(input)
    StopIteration
    
    The above exception was the direct cause of the following exception:
    
    Traceback (most recent call last):
      File "/home/rsa/swartz/.venv/lib/python3.7/site-packages/tornado/web.py", line 1592, in _execute
        result = yield result
      File "/home/rsa/swartz/.venv/lib/python3.7/site-packages/tornado/gen.py", line 1133, in run
        value = future.result()
    RuntimeError: generator raised StopIteration
```

I guess db_session decorator is consuming the return value in a way that Tornado can't handle.

**Comment by ranisalt** [comment]
Here's a different, longer traceback of the same issue:

```
    Traceback (most recent call last):
      File "/home/rsa/swartz/.venv/lib/python3.7/site-packages/tornado/web.py", line 1592, in _execute
        result = yield result
      File "/home/rsa/swartz/.venv/lib/python3.7/site-packages/tornado/gen.py", line 1133, in run
        value = future.result()
      File "/home/rsa/swartz/.venv/lib/python3.7/site-packages/pony/orm/core.py", line 544, in new_gen_func
        output = wrapped_interact(iterator)
      File "/home/rsa/swartz/.venv/lib/python3.7/site-packages/pony/orm/core.py", line 531, in wrapped_interact
        rollback_and_reraise(sys.exc_info())
      File "/home/rsa/swartz/.venv/lib/python3.7/site-packages/pony/orm/core.py", line 327, in rollback_and_reraise
        reraise(*exc_info)
      File "/home/rsa/swartz/.venv/lib/python3.7/site-packages/pony/utils/utils.py", line 118, in reraise
        try: raise exc.with_traceback(tb)
      File "/home/rsa/swartz/.venv/lib/python3.7/site-packages/pony/orm/core.py", line 525, in wrapped_interact
        'You need to manually commit() changes before exiting from the generator')
      File "/home/rsa/swartz/.venv/lib/python3.7/site-packages/pony/utils/utils.py", line 129, in throw
        raise exc
    pony.orm.core.TransactionError: You need to manually commit() changes before exiting from the generator
```

**Comment by sashaaero** [comment]
This should solve the last problem. Please respond if it doesn't.

**Comment by ranisalt** [comment]
It does not:

```
Traceback (most recent call last):
      File "/home/rsa/swartz/.venv/lib/python3.7/site-packages/tornado/web.py", line 1592, in _execute
        result = yield result
      File "/home/rsa/swartz/.venv/lib/python3.7/site-packages/tornado/gen.py", line 1133, in run
        value = future.result()
      File "/home/rsa/swartz/.venv/lib/python3.7/site-packages/pony/orm/core.py", line 544, in new_gen_func
        output = wrapped_interact(iterator)
      File "/home/rsa/swartz/.venv/lib/python3.7/site-packages/pony/orm/core.py", line 511, in wrapped_interact
        '@db_session-wrapped generator cannot be used inside another db_session')
      File "/home/rsa/swartz/.venv/lib/python3.7/site-packages/pony/utils/utils.py", line 129, in throw
        raise exc
    pony.orm.core.TransactionError: @db_session-wrapped generator cannot be used inside another db_session
```

**Comment by sashaaero** [comment]
Can you provide an example?

**Comment by kozlovsky** [comment]
What exception says is true: "@db_session-wrapped generator cannot be used inside another db_session"

**Comment by kozlovsky** [comment]
Well, actually we can temporarily switch outer db session to generator db session on resuming generator, but I'm not sure is it correct usage or not

**Comment by ranisalt** [comment]
> Can you provide an example?

I will try to isolate the issue in a gist

**Comment by kozlovsky** [comment]
In my understanding, it looks incorrect when someone directly call async (db_session-decorated) function from a normal (db_session-decorated function). There should be some dispatcher from which async functions are actually called

**Comment by ranisalt** [comment]
Ok, @kozlovsky helped me find the issue. While my code works fine, tests are also wrapped with db_session so there is a nested db_session function call. Something like this:

**Comment by ranisalt** [comment]
Ok, @kozlovsky helped me find the issue. While my code works fine, tests are also wrapped with db_session so there is a nested db_session function call. Something like this:

```
@db_session
async def get():
  u = self.db.User[self.id]
  do_something(u)

@db_session
def test_get(http_client):
  res = http_client.get('https://localhost/path/to/get()')
```

So it opens another db_session while the previous was already open.

Is there a way to make db_session reentrant or at least a known way to work around this scenario?

**Comment by trelljaret** [comment]
Is async support added finally?

**Comment by afkLuna** [comment]
Is it working now?
