### ISSUE TITLE
pony.orm.dbapiprovider.OperationalError: no such table: user

### ISSUE THREAD

**Issue by nadermx** [ponyorm/pony#384]
Trying to create a new Sqlite database using migrations and getting this error
```
$ python run.py
GET NEW CONNECTION
RELEASE CONNECTION
GET CONNECTION FROM THE LOCAL POOL
PRAGMA foreign_keys = false
BEGIN IMMEDIATE TRANSACTION
CREATE TABLE pony_version (id INT PRIMARY KEY, pony_version VARCHAR(20) NOT NULL)

insert into pony_version values (1, '0.8-dev')

SELECT "user"."id", "user"."username", "user"."password_hash", "user"."email", "user"."dt_registered", "user"."dt_last_visit", "user"."verified", "user"."failed_login", "user"."last_failed_login"
FROM "user" "user"
WHERE 0 = 1

ROLLBACK
PRAGMA foreign_keys = true
CLOSE CONNECTION
Traceback (most recent call last):
  File "/home/john/.virtualenvs/ship/lib/python3.6/site-packages/pony/orm/dbapiprovider.py", line 56, in wrap_dbapi_exceptions
    try: return func(provider, *args, **kwargs)
  File "/home/john/.virtualenvs/ship/lib/python3.6/site-packages/pony/orm/dbapiprovider.py", line 322, in execute
    new_id = provider._execute(cursor, sql, arguments, returning_id)
  File "/home/john/.virtualenvs/ship/lib/python3.6/site-packages/pony/orm/dbapiprovider.py", line 330, in _execute
    if arguments is None: cursor.execute(sql)
sqlite3.OperationalError: no such table: user

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run.py", line 6, in <module>
    models.db.connect(allow_auto_upgrade=True, **app.config['DB_PARAMS'])
  File "/home/john/.virtualenvs/ship/lib/python3.6/site-packages/pony/orm/core.py", line 714, in connect
    self.generate_mapping(check_tables=check_tables, create_tables=create_tables, allow_auto_upgrade=auto_upgrade)
  File "<string>", line 2, in generate_mapping
  File "/home/john/.virtualenvs/ship/lib/python3.6/site-packages/pony/orm/core.py", line 472, in new_func
    result = func(*args, **kwargs)
  File "/home/john/.virtualenvs/ship/lib/python3.6/site-packages/pony/orm/core.py", line 996, in generate_mapping
    if check_tables: schema.check_tables(connection)
  File "/home/john/.virtualenvs/ship/lib/python3.6/site-packages/pony/orm/dbschema.py", line 102, in check_tables
    provider.execute(cursor, sql)
  File "<string>", line 2, in execute
  File "/home/john/.virtualenvs/ship/lib/python3.6/site-packages/pony/orm/dbapiprovider.py", line 64, in wrap_dbapi_exceptions
    raise OperationalError(e)
pony.orm.dbapiprovider.OperationalError: no such table: user

```
config looks like so
```
DB_PARAMS = {
    'provider': 'sqlite',
    'filename': 'db.sqlite',
    'create_db': True
}

```

models.py looks like so
```
from pony.orm import *
from passlib.hash import bcrypt_sha256
from flask_login import UserMixin
from datetime import datetime

db = Database()

class User(UserMixin, db.Entity):
    username = Optional(unicode, unique=True)
    password_hash = Optional(unicode)
    email = Required(unicode, unique=True)
    dt_registered = Optional(datetime, default=datetime.utcnow)
    dt_last_visit = Optional(datetime, default=datetime.utcnow)
    verified = Optional(bool, default=False)
    failed_login = Optional(int)
    last_failed_login = Optional(datetime, default=datetime.utcnow)

    def hash_password(self, password):
        self.password_hash = bcrypt_sha256.hash(password)

    def verify_password(self, password):
        return bcrypt_sha256.verify(password, self.password_hash)

sql_debug(True)
```

when I run `python migrate.py make` and `python migrate.py apply` I get no errors and it makes the migrations file in the folder.  But when I put `python migrate.py list` I get 
```python migrate.py list
GET NEW CONNECTION
RELEASE CONNECTION
GET CONNECTION FROM THE LOCAL POOL
SWITCH TO AUTOCOMMIT MODE
SELECT "m"."id", "m"."name", "m"."applied"
FROM "migration" "m"
LIMIT 1

No Migration table. Please apply the initial migration.
RELEASE CONNECTION
DISCONNECT
```

**Comment by sashaaero** [comment]
Hi, nadermx! Thanks for reporting. Should work now.
