### ISSUE TITLE
'Release unlocked lock' error after 'delete'.

### ISSUE THREAD

**Issue by ichorid** [ponyorm/pony#386]
This code:
```python
from pony import orm
from pony.orm import db_session

db = orm.Database()

class TestClass1(db.Entity):
    rowid = orm.PrimaryKey(int, auto=True)
    val = orm.Optional(int, default=0)

db.bind(provider='sqlite', filename=":memory:", create_db=True)
db.generate_mapping(create_tables=True)

@db_session
def fun1():
    TestClass1.exists(val=12)
    return TestClass1()

@db_session
def fun2():
    a = TestClass1()
    a.delete()
    q = fun1()
    print q

def main():
    with db_session:
        fun2()

if __name__ == "__main__":
    main()
```

produces this error:
```python
Traceback (most recent call last):
  File "./pony_bug_get.py", line 34, in <module>
    main()
  File "./pony_bug_get.py", line 30, in main
    fun2()
  File "<auto generated wrapper of fun2() function>", line 2, in fun2
  File "/home/vader/.local/lib/python2.7/site-packages/pony/orm/core.py", line 480, in new_func
    reraise(exc_type, exc, tb)
  File "/home/vader/.local/lib/python2.7/site-packages/pony/orm/core.py", line 467, in new_func
    result = func(*args, **kwargs)
  File "./pony_bug_get.py", line 24, in fun2
    q = fun1()
  File "<auto generated wrapper of fun1() function>", line 2, in fun1
  File "/home/vader/.local/lib/python2.7/site-packages/pony/orm/core.py", line 480, in new_func
    reraise(exc_type, exc, tb)
  File "/home/vader/.local/lib/python2.7/site-packages/pony/orm/core.py", line 468, in new_func
    commit()
  File "/home/vader/.local/lib/python2.7/site-packages/pony/orm/core.py", line 349, in commit
    transact_reraise(CommitException, exceptions)
  File "/home/vader/.local/lib/python2.7/site-packages/pony/orm/core.py", line 319, in transact_reraise
    reraise(exc_class, new_exc, tb)
  File "/home/vader/.local/lib/python2.7/site-packages/pony/orm/core.py", line 343, in commit
    primary_cache.commit()
  File "/home/vader/.local/lib/python2.7/site-packages/pony/orm/core.py", line 1727, in commit
    cache.database.provider.commit(cache.connection, cache)
  File "/home/vader/.local/lib/python2.7/site-packages/pony/orm/dbproviders/sqlite.py", line 315, in commit
    provider.transaction_lock.release()
pony.orm.core.CommitException: error: release unlocked lock
```

**Comment by ichorid** [comment]
FYI: if we put `select` with `[:]` before `exists`, the bug is not triggered.

**Comment by ichorid** [comment]
`orm.flush()` has the same bug-nullifying effect.

**Comment by kozlovsky** [comment]
Simplified code to reproduce:
```python
from pony.orm import *

db = Database('sqlite', ':memory:')

class TestClass1(db.Entity):
    val = Required(int)

db.generate_mapping(create_tables=True)

with db_session:
    a = TestClass1(val=1)
    a.delete()
    TestClass1.exists(val=2)
    b = TestClass1(val=3)
```

**Comment by kozlovsky** [comment]
Should work now
