### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by nadermx** [ponyorm/pony#387]
I'm trying to upgrade 2 databases to pony migration tool.  When I run `migrate.py apply --fake-initial` I'm getting this error.
```
python migrate.py apply --fake-initial
Applied:
Traceback (most recent call last):
  File "migrate.py", line 7, in <module>
    models.db.migrate(**app.config['DB_PARAMS'])
  File "/home/john/.virtualenvs/yout27/local/lib/python2.7/site-packages/pony/orm/core.py", line 728, in migrate
    return migrate(self, command)
  File "/home/john/.virtualenvs/yout27/local/lib/python2.7/site-packages/pony/migrate/command.py", line 61, in migrate
    return _migrate(db, cmd, **kwargs)
  File "/home/john/.virtualenvs/yout27/local/lib/python2.7/site-packages/pony/migrate/command.py", line 102, in _migrate
    graph.apply(db=db, is_fake=fake_initial, dry_run=dry, name_start=start, name_end=end)
  File "/home/john/.virtualenvs/yout27/local/lib/python2.7/site-packages/pony/migrate/migration.py", line 383, in apply
    upgrade_db(new_db, dic)
  File "/home/john/.virtualenvs/yout27/local/lib/python2.7/site-packages/pony/migrate/migration.py", line 53, in upgrade_db
    op.apply(db)
  File "/home/john/.virtualenvs/yout27/local/lib/python2.7/site-packages/pony/migrate/diagram_ops.py", line 143, in apply
    entity._remove_relation_(op.attr_name)
  File "/home/john/.virtualenvs/yout27/local/lib/python2.7/site-packages/pony/orm/core.py", line 4003, in _remove_relation_
    entity._remove_attr_(attr_name)
  File "/home/john/.virtualenvs/yout27/local/lib/python2.7/site-packages/pony/orm/core.py", line 3909, in _remove_attr_
    assert attr.pk_offset is None
AssertionError


```

my models look like this, note I have 2 databases (sqlite, but prod ones are postgres so should try on both?)

```
from flask import current_app
from pony.orm import *
from passlib.apps import custom_app_context as pwd_context
from itsdangerous import (TimedJSONWebSignatureSerializer
                          as Serializer, BadSignature, SignatureExpired)
from flask_login import UserMixin
from datetime import datetime, timedelta
db = Database()
smalldb = Database()


class User(db.Entity, UserMixin):
    id = PrimaryKey(int, auto=True)
    photo_url = Optional(unicode)
    username = Required(unicode, 25, unique=True)
    name = Optional(unicode, 255)
    email = Optional(unicode, 255, unique=True)
    password_hash = Optional(unicode, 255)
    videos = Set(lambda: Video)
    verified = Required(bool, default=False)
    premium = Required(bool, default=False)
    following = Set(lambda: Following, reverse="follower")
    followers = Set(lambda: Following, reverse="followee")
    bio = Optional(unicode, 255)
    gifs = Set(lambda: Gif)
    newsletter = Optional(unicode, 255)
    created_at = Required(datetime, default=datetime.utcnow())
    promoted_videos = Set(lambda: PromotedVideo)
    budget = Optional(float, default=0)
    premium_expires = Optional(datetime)
    paypal = Set(lambda: PayPal)
    info = Optional(Json)
    payments = Set(lambda: Payment)
    timeline = Set(lambda: Timeline)


class Video(db.Entity):
    video_id = Required(unicode)
    users = Set(lambda: User)
    title = Optional(unicode)


class Gif(db.Entity):
    name = Required(unicode)
    gif_id = Required(unicode)
    users = Set(lambda: User)


class Following(db.Entity):
    follower = Required(User, reverse="following")
    followee = Required(User, reverse="followers")
    PrimaryKey(follower, followee)


class Text(smalldb.Entity):
    key = Optional(unicode)
    lang = Optional(unicode, 255)
    content = Optional(unicode)


class Timeline(db.Entity):
    user = Optional(lambda: User)
    username = Optional(unicode, 255)
    video_id = Optional(unicode, 11)
    title = Optional(unicode, 255)
    date_created = Required(datetime, default=datetime.utcnow())
    content = Optional(unicode, 219)



class Hotness(db.Entity):
    video_id = Optional(unicode, 11, unique=True)
    title = Optional(unicode, 255)
    first_submitter = Optional(unicode, 255)
    date_created = Optional(datetime)
    votes = Optional(int)
    hot_score = Optional(float)

class PromotedVideo(db.Entity):
    video_id = Optional(unicode, 11)
    title = Optional(unicode, 255)
    created_at = Required(datetime, default=datetime.utcnow())
    user = Required(lambda: User)
    video_budget = Optional(float)
    max_bid = Optional(float)
    mp3 = Optional(int)
    mp4 = Optional(int)
    plays = Optional(int)
    impressions = Optional(int)
    clicks = Optional(int)
    expires = Optional(datetime)
    photo_url = Optional(unicode, 255)
    run_time = Set(lambda: RunTime)
    status = Optional(bool, default=False)
    running = Optional(bool, default=False)
    location = Optional(unicode, 255)


class RunTime(db.Entity):
    promoted_video = Optional(lambda: PromotedVideo)
    status = Optional(bool)
    start_time = Optional(datetime)
    end_time = Optional(datetime)
    bid = Optional(float)


class PayPal(db.Entity):
    payer_email = Optional(unicode)
    payment_date = Required(datetime, default=datetime.utcnow())
    username = Optional(unicode)
    last_name = Optional(unicode)
    user_id = Optional(unicode)
    user = Optional(lambda: User)


class Stripe(db.Entity):
    username = Optional(unicode)
    email = Optional(unicode)
    user_id = Optional(unicode)
    payment_date = Required(datetime, default=datetime.utcnow())


class Payment(db.Entity):
    user = Optional(lambda: User)
    paypal = Optional(Json)
    authorize = Optional(Json)
    coinbase = Optional(Json)
    payment_date = Required(datetime, default=datetime.utcnow())


class Anon(db.Entity):
    title = Optional(unicode)
    content = Optional(LongUnicode)
    date_created = Required(datetime, default=datetime.utcnow())

```

**Comment by sashaaero** [comment]
Hi, @nadermx! Can you post your migration file?
It seems that you have migrations for different databases in the same folder so they are mixing between databases (since you said you have two). 
I think you should separate migration folders for each database.

**Comment by nadermx** [comment]
So you suggest I break up the models.py into 2 separate files? If not I'm unsure as to how to make it so migrations are only reading of each.

here is the migrations file that have been made

```# -*- coding: utf-8 -*-
# Generated by Pony ORM 0.8-dev on 2018-10-09 20:24
from __future__ import unicode_literals

import datetime
from pony import orm
import pony.orm.ormtypes

dependencies = []

def define_entities(db):
    class User(db.Entity):
        photo_url = orm.Optional(unicode)
        username = orm.Required(unicode, 25, unique=True)
        name = orm.Optional(unicode, 255)
        email = orm.Optional(unicode, 255, unique=True)
        password_hash = orm.Optional(unicode, 255)
        videos = orm.Set('Video')
        verified = orm.Required(bool)
        premium = orm.Required(bool)
        following = orm.Set('Following', reverse='follower')
        followers = orm.Set('Following', reverse='followee')
        bio = orm.Optional(unicode, 255)
        gifs = orm.Set('Gif')
        newsletter = orm.Optional(unicode, 255)
        created_at = orm.Required(datetime.datetime)
        promoted_videos = orm.Set('PromotedVideo')
        budget = orm.Optional(float)
        premium_expires = orm.Optional(datetime.datetime)
        paypal = orm.Set('PayPal')
        info = orm.Optional(pony.orm.ormtypes.Json)
        payments = orm.Set('Payment')
        timeline = orm.Set('Timeline')

    class Video(db.Entity):
        video_id = orm.Required(unicode)
        users = orm.Set('User')
        title = orm.Optional(unicode)

    class Gif(db.Entity):
        name = orm.Required(unicode)
        gif_id = orm.Required(unicode)
        users = orm.Set('User')

    class Following(db.Entity):
        follower = orm.Required(db.User, reverse='following')
        followee = orm.Required(db.User, reverse='followers')
        orm.PrimaryKey(follower, followee)

    class Timeline(db.Entity):
        user = orm.Optional('User')
        username = orm.Optional(unicode, 255)
        video_id = orm.Optional(unicode, 11)
        title = orm.Optional(unicode, 255)
        date_created = orm.Required(datetime.datetime)
        content = orm.Optional(unicode, 219)

    class Hotness(db.Entity):
        video_id = orm.Optional(unicode, 11, unique=True)
        title = orm.Optional(unicode, 255)
        first_submitter = orm.Optional(unicode, 255)
        date_created = orm.Optional(datetime.datetime)
        votes = orm.Optional(int)
        hot_score = orm.Optional(float)

    class PromotedVideo(db.Entity):
        video_id = orm.Optional(unicode, 11)
        title = orm.Optional(unicode, 255)
        created_at = orm.Required(datetime.datetime)
        user = orm.Required('User')
        video_budget = orm.Optional(float)
        max_bid = orm.Optional(float)
        mp3 = orm.Optional(int)
        mp4 = orm.Optional(int)
        plays = orm.Optional(int)
        impressions = orm.Optional(int)
        clicks = orm.Optional(int)
        expires = orm.Optional(datetime.datetime)
        photo_url = orm.Optional(unicode, 255)
        run_time = orm.Set('RunTime')
        status = orm.Optional(bool)
        running = orm.Optional(bool)
        location = orm.Optional(unicode, 255)

    class RunTime(db.Entity):
        promoted_video = orm.Optional('PromotedVideo')
        status = orm.Optional(bool)
        start_time = orm.Optional(datetime.datetime)
        end_time = orm.Optional(datetime.datetime)
        bid = orm.Optional(float)

    class PayPal(db.Entity):
        payer_email = orm.Optional(unicode)
        payment_date = orm.Required(datetime.datetime)
        username = orm.Optional(unicode)
        last_name = orm.Optional(unicode)
        user_id = orm.Optional(unicode)
        user = orm.Optional('User')

    class Stripe(db.Entity):
        username = orm.Optional(unicode)
        email = orm.Optional(unicode)
        user_id = orm.Optional(unicode)
        payment_date = orm.Required(datetime.datetime)

    class Payment(db.Entity):
        user = orm.Optional('User')
        paypal = orm.Optional(pony.orm.ormtypes.Json)
        authorize = orm.Optional(pony.orm.ormtypes.Json)
        coinbase = orm.Optional(pony.orm.ormtypes.Json)
        payment_date = orm.Required(datetime.datetime)

    class Anon(db.Entity):
        title = orm.Optional(unicode)
        content = orm.Optional(pony.orm.ormtypes.LongUnicode)
        date_created = orm.Required(datetime.datetime)
```

And the other is 

```
# -*- coding: utf-8 -*-
# Generated by Pony ORM 0.8-dev on 2018-10-09 20:24
from __future__ import unicode_literals

from pony import orm
from pony.migrate import diagram_ops as op

dependencies = ['0001_initial']

operations = [
    op.RemoveRelation('Following', 'followee'),
    op.RemoveRelation('Following', 'follower'),
    op.RemoveRelation('Gif', 'users'),
    op.RemoveRelation('PayPal', 'user'),
    op.RemoveRelation('Payment', 'user'),
    op.RemoveRelation('PromotedVideo', 'run_time'),
    op.RemoveRelation('PromotedVideo', 'user'),
    op.RemoveRelation('Timeline', 'user'),
    op.RemoveRelation('User', 'videos'),
    op.RemoveEntity('Anon'),
    op.RemoveEntity('Following'),
    op.RemoveEntity('Gif'),
    op.RemoveEntity('Hotness'),
    op.RemoveEntity('PayPal'),
    op.RemoveEntity('Payment'),
    op.RemoveEntity('PromotedVideo'),
    op.RemoveEntity('RunTime'),
    op.RemoveEntity('Stripe'),
    op.RemoveEntity('Timeline'),
    op.RemoveEntity('User'),
    op.RemoveEntity('Video'),
    op.AddEntity('Text', ['Entity'], [('content', orm.Optional(unicode)), ('id', orm.PrimaryKey(int, auto=True)), ('key', orm.Optional(unicode)), ('lang', orm.Optional(unicode, 255))])]
```

**Comment by nadermx** [comment]
Seems breaking it into 2 forlders solved the issue, thank you
