### ISSUE TITLE
to_json raising pony.orm.core.PermissionError

### ISSUE THREAD

**Issue by martmists** [ponyorm/pony#389]
My application is fully able to create tables and insert, but when calling to_json I get the following:
```py
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/mart/git/server/framework/route.py", line 37, in switch
    return routes[path][request.method](*args, **kwargs)
  File "/home/mart/git/server/framework/route_wrappers.py", line 21, in inner
    response = func(*args, **kwargs)
  File "/home/mart/git/server/routes/mods.py", line 136, in post_users
    return jsonify(database_handle.new_user(**user).json)
  File "/home/mart/git/server/framework/models.py", line 20, in json
    return self.to_json()  # pylint: disable=no-member
  File "/usr/lib/python3.7/site-packages/pony/orm/core.py", line 5158, in to_json
    return obj._database_.to_json(obj, include, exclude, converter, with_schema, schema_hash)
  File "/usr/lib/python3.7/site-packages/pony/orm/core.py", line 1195, in to_json
    data_json = json.dumps(data, default=obj_converter)
  File "/usr/lib/python3.7/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.7/site-packages/pony/orm/core.py", line 1189, in obj_converter
    user_has_no_rights_to_see(obj)
  File "/usr/lib/python3.7/site-packages/pony/orm/core.py", line 1178, in user_has_no_rights_to_see
    % (user, sorted(user_groups), obj))
  File "/usr/lib/python3.7/site-packages/pony/utils/utils.py", line 106, in throw
    raise exc
pony.orm.core.PermissionError: The current user None which belongs to groups ['anybody'] has no rights to see the object User['4970935609449217548'] on the frontend
```

**Comment by kozlovsky** [comment]
`to_json` was an experimental method, don't use it. You can use `to_dict` instead, and then convert its result to JSON:
https://docs.ponyorm.com/api_reference.html?highlight=to_dict#Entity.to_dict

**Comment by mosesontheweb** [comment]
Is this still valid? Got the same error while trying my first steps using PonyORM.

Regards, Thomas

**Comment by belmarca** [comment]
@mosesontheweb If you want an array of jsonified dicts, do:

```python
import json
from datetime import datetime
# other imports

def datetime_converter(o):
    if isinstance(o, datetime):
        return o.__str__()

s = select(s for s in S).order_by(lambda p: desc(p.x)).page(1)[:]
_s = [i.to_dict() for i in s]
json = json.dumps(_s, default=datetime_converter)
```

**Comment by larsks** [comment]
I just hit the same problem. If `to_json` is broken, why not remove it (or have it raise a `DeprecationWarning`)?
