### ISSUE TITLE
pony.orm.core.BindingError: Database object was already bound to PostgreSQL provider

### ISSUE THREAD

**Issue by nadermx** [ponyorm/pony#395]
I'm currently trying to do upgrade 2 postgres db's.  When I do `migrate.py make` and `migrate.py apply --fake-initial` it works fine.  But as soon as I try and actually run my `python run.py` that looks like this 

```
# -*- coding: utf-8 -*-
#!/usr/bin/env python
from app import app, models
from gevent.pywsgi import WSGIServer


app.config.from_object('app_config')
#set a global db session for the app
app.wsgi_app = models.db_session(app.wsgi_app)
#Pony ORM database config

models.db.connect(allow_auto_upgrade=True, **app.config['DB_PARAMS'])

models.smalldb.connect(allow_auto_upgrade=True, **app.config['DB_TEXT_PARAMS'])


if __name__ == '__main__':
    # app.run(host='0.0.0.0', port=5000, debug=True, threaded=True)
    # app.run(debug = True)
    http_server = WSGIServer(('', 5000), app)
    http_server.serve_forever()

```

I end up getting this error

```
Traceback (most recent call last):
  File "run.py", line 18, in <module>
    models.db.connect(allow_auto_upgrade=True, **app.config['DB_TEXT_PARAMS'])
  File "/home/www/wtf/local/lib/python2.7/site-packages/pony/orm/core.py", line 713, in connect
    self._bind(*args, **kwargs)
  File "/home/www/wtf/local/lib/python2.7/site-packages/pony/orm/core.py", line 736, in _bind
    throw(BindingError, 'Database object was already bound to %s provider' % self.provider.dialect)
  File "/home/www/wtf/local/lib/python2.7/site-packages/pony/utils/utils.py", line 106, in throw
    raise exc
pony.orm.core.BindingError: Database object was already bound to PostgreSQL provider
```

**Comment by nadermx** [comment]
I don't have a bind active, only using connect.  Don't seem to have 2 connect's either
