### ISSUE TITLE
pony.orm.dbapiprovider.ProgrammingError: relation "anon" does not exist

### ISSUE THREAD

**Issue by nadermx** [ponyorm/pony#396]
trying to run migrations on a upgraded db and this error shows after i apply migrations with `fake-initiall`, this is my run.py file

```
# -*- coding: utf-8 -*-
#!/usr/bin/env python
# import sys
# sys.path.insert(0, '/home/www/youtstream')
# Run a test server.
from app import app, models
from gevent.pywsgi import WSGIServer


app.config.from_object('app_config')
#set a global db session for the app
app.wsgi_app = models.db_session(app.wsgi_app)
#Pony ORM database config

models.db.connect(allow_auto_upgrade=True, **app.config['DB_PARAMS'])

models.smalldb.connect(allow_auto_upgrade=True, **app.config['DB_TEXT_PARAMS'])


if __name__ == '__main__':
    # app.run(host='0.0.0.0', port=5000, debug=True, threaded=True)
    # app.run(debug = True)
    http_server = WSGIServer(('', 5000), app)
    http_server.serve_forever()
```
This is the error that shows 

```
Traceback (most recent call last):
  File "run.py", line 15, in <module>
    models.db.connect(allow_auto_upgrade=True, **app.config['DB_PARAMS'])
  File "/home/john/.virtualenvs/yout27/local/lib/python2.7/site-packages/pony/orm/core.py", line 714, in connect
    self.generate_mapping(check_tables=check_tables, create_tables=create_tables, allow_auto_upgrade=auto_upgrade)
  File "<auto generated wrapper of generate_mapping() function>", line 2, in generate_mapping
  File "/home/john/.virtualenvs/yout27/local/lib/python2.7/site-packages/pony/orm/core.py", line 472, in new_func
    result = func(*args, **kwargs)
  File "/home/john/.virtualenvs/yout27/local/lib/python2.7/site-packages/pony/orm/core.py", line 996, in generate_mapping
    if check_tables: schema.check_tables(connection)
  File "/home/john/.virtualenvs/yout27/local/lib/python2.7/site-packages/pony/orm/dbschema.py", line 102, in check_tables
    provider.execute(cursor, sql)
  File "<auto generated wrapper of execute() function>", line 2, in execute
  File "/home/john/.virtualenvs/yout27/local/lib/python2.7/site-packages/pony/orm/dbapiprovider.py", line 59, in wrap_dbapi_exceptions
    except dbapi_module.ProgrammingError as e: raise ProgrammingError(e)
pony.orm.dbapiprovider.ProgrammingError: relation "anon" does not exist
LINE 2: FROM "anon" "anon"
```

Here is the models

```
db = Database()
smalldb = Database()


class User(db.Entity, UserMixin):
    id = PrimaryKey(int, auto=True)
    photo_url = Optional(unicode)
    username = Required(unicode, 25, unique=True)
    name = Optional(unicode, 255)
    email = Optional(unicode, 255, unique=True)
    password_hash = Optional(unicode, 255)
    videos = Set(lambda: Video)
    verified = Required(bool, default=False)
    premium = Required(bool, default=False)
    following = Set(lambda: Following, reverse="follower")
    followers = Set(lambda: Following, reverse="followee")
    bio = Optional(unicode, 255)
    gifs = Set(lambda: Gif)
    newsletter = Optional(unicode, 255)
    created_at = Required(datetime, default=datetime.utcnow())
    promoted_videos = Set(lambda: PromotedVideo)
    budget = Optional(float, default=0)
    premium_expires = Optional(datetime)
    paypal = Set(lambda: PayPal)
    info = Optional(Json)
    payments = Set(lambda: Payment)
    timeline = Set(lambda: Timeline)


class Video(db.Entity):
    video_id = Required(unicode)
    users = Set(lambda: User)
    title = Optional(unicode)


class Gif(db.Entity):
    name = Required(unicode)
    gif_id = Required(unicode)
    users = Set(lambda: User)


class Following(db.Entity):
    follower = Required(User, reverse="following")
    followee = Required(User, reverse="followers")
    PrimaryKey(follower, followee)


class Text(smalldb.Entity):
    key = Optional(unicode)
    lang = Optional(unicode, 255)
    content = Optional(unicode)


class Timeline(db.Entity):
    user = Optional(lambda: User)
    username = Optional(unicode, 255)
    video_id = Optional(unicode, 11)
    title = Optional(unicode, 255)
    date_created = Required(datetime, default=datetime.utcnow())
    content = Optional(unicode, 219)

class Hotness(db.Entity):
    video_id = Optional(unicode, 11, unique=True)
    title = Optional(unicode, 255)
    first_submitter = Optional(unicode, 255)
    date_created = Optional(datetime)
    votes = Optional(int)
    hot_score = Optional(float)



class PromotedVideo(db.Entity):
    video_id = Optional(unicode, 11)
    title = Optional(unicode, 255)
    created_at = Required(datetime, default=datetime.utcnow())
    user = Required(lambda: User)
    video_budget = Optional(float)
    max_bid = Optional(float)
    mp3 = Optional(int)
    mp4 = Optional(int)
    plays = Optional(int)
    impressions = Optional(int)
    clicks = Optional(int)
    expires = Optional(datetime)
    photo_url = Optional(unicode, 255)
    run_time = Set(lambda: RunTime)
    status = Optional(bool, default=False)
    running = Optional(bool, default=False)
    location = Optional(unicode, 255)


class RunTime(db.Entity):
    promoted_video = Optional(lambda: PromotedVideo)
    status = Optional(bool)
    start_time = Optional(datetime)
    end_time = Optional(datetime)
    bid = Optional(float)


class PayPal(db.Entity):
    payer_email = Optional(unicode)
    payment_date = Required(datetime, default=datetime.utcnow())
    username = Optional(unicode)
    last_name = Optional(unicode)
    user_id = Optional(unicode)
    user = Optional(lambda: User)


class Stripe(db.Entity):
    username = Optional(unicode)
    email = Optional(unicode)
    user_id = Optional(unicode)
    payment_date = Required(datetime, default=datetime.utcnow())


class Payment(db.Entity):
    user = Optional(lambda: User)
    paypal = Optional(Json)
    authorize = Optional(Json)
    coinbase = Optional(Json)
    payment_date = Required(datetime, default=datetime.utcnow())


class Anon(db.Entity):
    title = Optional(unicode)
    content = Optional(LongUnicode)
    date_created = Required(datetime, default=datetime.utcnow())
```
Here is both migration files for each db

```
# -*- coding: utf-8 -*-
# Generated by Pony ORM 0.8-dev on 2018-10-18 17:25
from __future__ import unicode_literals

import datetime
from pony import orm
import pony.orm.ormtypes

dependencies = []

def define_entities(db):
    class User(db.Entity):
        photo_url = orm.Optional(unicode)
        username = orm.Required(unicode, 25, unique=True)
        name = orm.Optional(unicode, 255)
        email = orm.Optional(unicode, 255, unique=True)
        password_hash = orm.Optional(unicode, 255)
        videos = orm.Set('Video')
        verified = orm.Required(bool)
        premium = orm.Required(bool)
        following = orm.Set('Following', reverse='follower')
        followers = orm.Set('Following', reverse='followee')
        bio = orm.Optional(unicode, 255)
        gifs = orm.Set('Gif')
        newsletter = orm.Optional(unicode, 255)
        created_at = orm.Required(datetime.datetime)
        promoted_videos = orm.Set('PromotedVideo')
        budget = orm.Optional(float)
        premium_expires = orm.Optional(datetime.datetime)
        paypal = orm.Set('PayPal')
        info = orm.Optional(pony.orm.ormtypes.Json)
        payments = orm.Set('Payment')
        timeline = orm.Set('Timeline')

    class Video(db.Entity):
        video_id = orm.Required(unicode)
        users = orm.Set('User')
        title = orm.Optional(unicode)

    class Gif(db.Entity):
        name = orm.Required(unicode)
        gif_id = orm.Required(unicode)
        users = orm.Set('User')

    class Following(db.Entity):
        follower = orm.Required(db.User, reverse='following')
        followee = orm.Required(db.User, reverse='followers')
        orm.PrimaryKey(follower, followee)

    class Timeline(db.Entity):
        user = orm.Optional('User')
        username = orm.Optional(unicode, 255)
        video_id = orm.Optional(unicode, 11)
        title = orm.Optional(unicode, 255)
        date_created = orm.Required(datetime.datetime)
        content = orm.Optional(unicode, 219)

    class Hotness(db.Entity):
        video_id = orm.Optional(unicode, 11, unique=True)
        title = orm.Optional(unicode, 255)
        first_submitter = orm.Optional(unicode, 255)
        date_created = orm.Optional(datetime.datetime)
        votes = orm.Optional(int)
        hot_score = orm.Optional(float)

    class PromotedVideo(db.Entity):
        video_id = orm.Optional(unicode, 11)
        title = orm.Optional(unicode, 255)
        created_at = orm.Required(datetime.datetime)
        user = orm.Required('User')
        video_budget = orm.Optional(float)
        max_bid = orm.Optional(float)
        mp3 = orm.Optional(int)
        mp4 = orm.Optional(int)
        plays = orm.Optional(int)
        impressions = orm.Optional(int)
        clicks = orm.Optional(int)
        expires = orm.Optional(datetime.datetime)
        photo_url = orm.Optional(unicode, 255)
        run_time = orm.Set('RunTime')
        status = orm.Optional(bool)
        running = orm.Optional(bool)
        location = orm.Optional(unicode, 255)

    class RunTime(db.Entity):
        promoted_video = orm.Optional('PromotedVideo')
        status = orm.Optional(bool)
        start_time = orm.Optional(datetime.datetime)
        end_time = orm.Optional(datetime.datetime)
        bid = orm.Optional(float)

    class PayPal(db.Entity):
        payer_email = orm.Optional(unicode)
        payment_date = orm.Required(datetime.datetime)
        username = orm.Optional(unicode)
        last_name = orm.Optional(unicode)
        user_id = orm.Optional(unicode)
        user = orm.Optional('User')

    class Stripe(db.Entity):
        username = orm.Optional(unicode)
        email = orm.Optional(unicode)
        user_id = orm.Optional(unicode)
        payment_date = orm.Required(datetime.datetime)

    class Payment(db.Entity):
        user = orm.Optional('User')
        paypal = orm.Optional(pony.orm.ormtypes.Json)
        authorize = orm.Optional(pony.orm.ormtypes.Json)
        coinbase = orm.Optional(pony.orm.ormtypes.Json)
        payment_date = orm.Required(datetime.datetime)

    class Anon(db.Entity):
        title = orm.Optional(unicode)
        content = orm.Optional(pony.orm.ormtypes.LongUnicode)
        date_created = orm.Required(datetime.datetime)

```
and the other
```
# -*- coding: utf-8 -*-
# Generated by Pony ORM 0.8-dev on 2018-10-18 17:25
from __future__ import unicode_literals

from pony import orm

dependencies = []

def define_entities(db):
    class Text(db.Entity):
        key = orm.Optional(unicode)
        lang = orm.Optional(unicode, 255)
        content = orm.Optional(unicode)
```

**Comment by sashaaero** [comment]
Hello, @nadermx. Is there any chance that your database is empty or you added class `Anon` after applying initial migration?

**Comment by nadermx** [comment]
The class isn't added, it is possible the db is empty, but was made with pony 7, I tried it on the production DB but it broke as well that has things in it
