### ISSUE TITLE
ERDiagramError: Mapping is not generated for entity 'Text'

### ISSUE THREAD

**Issue by nadermx** [ponyorm/pony#399]
Referencing these two issues, [`395`](https://github.com/ponyorm/pony/issues/395) and [`396`](https://github.com/ponyorm/pony/issues/396), I tried making a database with the newest version of pony avaible via pip.  Then made a postgres database, filled it with some information.  I then tried with pony orm migrations, to upgrade the database to the migration branch and got this error 

```
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 150-925-677
127.0.0.1 - - [22/Oct/2018 15:57:07] "GET / HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/john/.virtualenvs/yout27/lib/python2.7/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/john/.virtualenvs/yout27/lib/python2.7/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/home/john/.virtualenvs/yout27/lib/python2.7/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/john/.virtualenvs/yout27/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/john/.virtualenvs/yout27/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/john/.virtualenvs/yout27/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/john/.virtualenvs/yout27/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/john/.virtualenvs/yout27/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "<auto generated wrapper of home_page() function>", line 2, in home_page
    
  File "/home/john/.virtualenvs/yout27/lib/python2.7/site-packages/pony/orm/core.py", line 472, in new_func
    result = func(*args, **kwargs)
  File "/home/john/PycharmProjects/youtstream/app/frontends/views.py", line 548, in home_page
    settings = get_page_settings()
  File "/home/john/PycharmProjects/youtstream/app/frontends/views.py", line 73, in get_page_settings
    lang, translation = get_translations()
  File "/home/john/PycharmProjects/youtstream/app/frontends/views.py", line 41, in get_translations
    lang_text = models.select(t for t in models.Text if t.lang == lang)[:]
  File "/home/john/.virtualenvs/yout27/lib/python2.7/site-packages/pony/orm/core.py", line 5560, in select
    return make_query(args, frame_depth=cut_traceback_depth+1)
  File "/home/john/.virtualenvs/yout27/lib/python2.7/site-packages/pony/orm/core.py", line 5556, in make_query
    return Query(code_key, tree.code, globals, locals, cells, left_join)
  File "/home/john/.virtualenvs/yout27/lib/python2.7/site-packages/pony/orm/core.py", line 5696, in __init__
    if database.schema is None: throw(ERDiagramError, 'Mapping is not generated for entity %r' % origin.__name__)
  File "/home/john/.virtualenvs/yout27/lib/python2.7/site-packages/pony/utils/utils.py", line 106, in throw
    raise exc
ERDiagramError: Mapping is not generated for entity 'Text'
```

**Comment by sashaaero** [comment]
Hello. You closed all three your last issues. Did you solve your problem by yourself?
