### ISSUE TITLE
Writing a select query with mistyped parameters results in unreadable error message

### ISSUE THREAD

**Issue by meritasix** [ponyorm/pony#407]
If you accidentally capitalize some parts of a select line like so:

`for thing in orm.select(Thing for thing in Thing):` 

You end up with the following error message: 

> Traceback (most recent call last):
>    for thing in orm.select(Thing for thing in Thing):
>  File "python3.7/site-packages/pony/orm/core.py", line 5232, in select
>    return make_query(args, frame_depth=cut_traceback_depth+1)
>  File "python3.7/site-packages/pony/orm/core.py", line 5228, in make_query
>    return Query(code_key, tree.code, globals, locals, cells, left_join)
>  File "python3.7/site-packages/pony/orm/core.py", line 5392, in __init__
>    translator = translator_cls(tree_copy, None, code_key, filter_num, extractors, vars, vartypes.copy(), left_join=left_join)
>  File "python3.7/site-packages/pony/orm/sqltranslation.py", line 198, in __init__
>    translator.init(tree, parent_translator, code_key, filter_num, extractors, vars, vartypes, left_join, optimize)
>  File "python3.7/site-packages/pony/orm/sqltranslation.py", line 414, in init
>    else: assert False  # pragma: no cover
>AssertionError

Using latest pony (0.7.6) on python 3.7 on OSX with a local sqlite database.

**Comment by sashaaero** [comment]
`select(thing fot thing in Thing)`
