### ISSUE TITLE
pony.orm.dbapiprovider.ProgrammingError: index "unq_hotness__video_id" does not exist

### ISSUE THREAD

**Issue by nadermx** [ponyorm/pony#410]
I'm currently using the ponyorm migrations, and in changing the video_id unicode length from 11 to 100
```
class Hotness(db.Entity):
    video_id = Optional(unicode, 11, unique=True)
    title = Optional(unicode, 255)
    first_submitter = Optional(unicode, 255)
    date_created = Optional(datetime)
    votes = Optional(int)
    hot_score = Optional(float)
```
to this
```
class Hotness(db.Entity):
    video_id = Optional(unicode, 100, unique=True)
    title = Optional(unicode, 255)
    first_submitter = Optional(unicode, 255)
    date_created = Optional(datetime)
    votes = Optional(int)
    hot_score = Optional(float)
```
I get this error when trying to run `python migrate.py apply`

```
python migrate.py apply
Applied:
Traceback (most recent call last):
  File "migrate.py", line 7, in <module>
    models.db.migrate(allow_auto_upgrade=True, migration_dir='migrations', **app.config['DB_PARAMS'])
  File "/home/www/wtf2/local/lib/python2.7/site-packages/pony/orm/core.py", line 728, in migrate
    return migrate(self, command)
  File "/home/www/wtf2/local/lib/python2.7/site-packages/pony/migrate/command.py", line 61, in migrate
    return _migrate(db, cmd, **kwargs)
  File "/home/www/wtf2/local/lib/python2.7/site-packages/pony/migrate/command.py", line 102, in _migrate
    graph.apply(db=db, is_fake=fake_initial, dry_run=dry, name_start=start, name_end=end)
  File "/home/www/wtf2/local/lib/python2.7/site-packages/pony/migrate/migration.py", line 408, in apply
    prev_db.execute(sql)
  File "/home/www/wtf2/local/lib/python2.7/site-packages/pony/orm/core.py", line 884, in execute
    return database._exec_raw_sql(sql, globals, locals, frame_depth=cut_traceback_depth+1, start_transaction=True)
  File "/home/www/wtf2/local/lib/python2.7/site-packages/pony/orm/core.py", line 896, in _exec_raw_sql
    return database._exec_sql(adapted_sql, arguments, False, start_transaction)
  File "/home/www/wtf2/local/lib/python2.7/site-packages/pony/orm/core.py", line 957, in _exec_sql
    connection = cache.reconnect(e)
  File "/home/www/wtf2/local/lib/python2.7/site-packages/pony/orm/core.py", line 1666, in reconnect
    if not provider.should_reconnect(exc): reraise(*sys.exc_info())
  File "/home/www/wtf2/local/lib/python2.7/site-packages/pony/orm/core.py", line 955, in _exec_sql
    try: new_id, duration = provider.execute(cursor, sql, arguments, returning_id)
  File "<auto generated wrapper of execute() function>", line 2, in execute
  File "/home/www/wtf2/local/lib/python2.7/site-packages/pony/orm/dbapiprovider.py", line 59, in wrap_dbapi_exceptions
    except dbapi_module.ProgrammingError as e: raise ProgrammingError(e)
pony.orm.dbapiprovider.ProgrammingError: index "unq_hotness__video_id" does not exist
```

**Comment by sashaaero** [comment]
Hi, nadermx! You are using PostgreSQL?

**Comment by nadermx** [comment]
@sashaaero postgres, correct

**Comment by sashaaero** [comment]
@nadermx sorry for long time. Should work now.
