### ISSUE TITLE
0.7.7 fails with complex prefetch

### ISSUE THREAD

**Issue by andreymal** [ponyorm/pony#414]
```python
from pony.orm import *

db = Database()

class TagCategory(db.Entity):
    tags = Set('Tag')

class Tag(db.Entity):
    category = Optional(TagCategory)
    posts = Set('PostTag')

class PostTag(db.Entity):
    post = Required('Post')
    tag = Required('Tag')
    position = Required(int, default=0)

class Post(db.Entity):
    name = Required(str, 128, autostrip=False)
    tags = Set(PostTag)

db.bind('sqlite', ':memory:')
db.generate_mapping(create_tables=True)
sql_debug(True)

with db_session:
    tag = Tag()
    tag.flush()
    post = Post(name='foo')
    post.flush()
    PostTag(post=post, tag=tag).flush()

with db_session:
    Post.select().prefetch(Post.tags, PostTag.tag, Tag.category).first()
```

```
Traceback (most recent call last):
  File "ponyfail_077.py", line 33, in <module>
    Post.select().prefetch(Post.tags, PostTag.tag, Tag.category).first()
  File "lib/python3.4/site-packages/pony/orm/core.py", line 5888, in first
    objects = query.without_distinct()[:1]
  File "lib/python3.4/site-packages/pony/orm/core.py", line 6131, in __getitem__
    return query._fetch(limit=stop-start, offset=start)
  File "lib/python3.4/site-packages/pony/orm/core.py", line 6133, in _fetch
    return QueryResult(query, limit, offset, lazy=lazy)
  File "lib/python3.4/site-packages/pony/orm/core.py", line 6240, in __init__
    self._items = None if lazy else self._query._actual_fetch(limit, offset)
  File "lib/python3.4/site-packages/pony/orm/core.py", line 5794, in _actual_fetch
    if query._prefetch: query._do_prefetch(items)
  File "lib/python3.4/site-packages/pony/orm/core.py", line 5861, in _do_prefetch
    objects_to_prefetch_dict[obj.__class__._root_].add(obj)
AttributeError: type object 'NoneType' has no attribute '_root_'
```

**Comment by kozlovsky** [comment]
Thanks for reporting!
