### ISSUE TITLE
SET NULL is not set for many-to-many self-relationship tables

### ISSUE THREAD

**Issue by ichorid** [ponyorm/pony#430]
While trying to delete an entry with `bulk=True`, there is a `FOREIGN KEY constraint failed` message.
Apparently, Pony does not set the `SET NULL` action in the intermediate table.
That is peculiar because it sets this for regular (not intermediate) tables, as can be seen with 
`PRAGMA foreign_key_list(db_name)`;

Minimal example:
```python
from pony import orm
from pony.orm import db_session


db = orm.Database()

class TestClass1(db.Entity):
    rowid = orm.PrimaryKey(int, auto=True)
    friend = orm.Set("TestClass1", reverse="friend")

db.bind(provider='sqlite', filename=":memory:", create_db=True)
db.generate_mapping(create_tables=True)

if __name__ == "__main__":
    with db_session:
        c1 = TestClass1()
        c2 = TestClass1(friend=c1)

    with db_session:
        print TestClass1.select()[:]
        TestClass1.select().delete(bulk=True)
```              
Results in
```python
Traceback (most recent call last):
  File "./pony_bug_self.py", line 21, in <module>
    TestClass1.select().delete(bulk=True)
  File "/home/user/.local/lib/python2.7/site-packages/pony/orm/core.py", line 5922, in delete
    cursor = database._exec_sql(sql, arguments)
  File "/home/user/.local/lib/python2.7/site-packages/pony/orm/core.py", line 941, in _exec_sql
    connection = cache.reconnect(e)
  File "/home/user/.local/lib/python2.7/site-packages/pony/orm/core.py", line 1771, in reconnect
    if not provider.should_reconnect(exc): reraise(*sys.exc_info())
  File "/home/user/.local/lib/python2.7/site-packages/pony/orm/core.py", line 939, in _exec_sql
    try: new_id = provider.execute(cursor, sql, arguments, returning_id)
  File "<auto generated wrapper of execute() function>", line 2, in execute
  File "/home/user/.local/lib/python2.7/site-packages/pony/orm/dbapiprovider.py", line 58, in wrap_dbapi_exceptions
    except dbapi_module.IntegrityError as e: raise IntegrityError(e)
pony.orm.dbapiprovider.IntegrityError: FOREIGN KEY constraint failed
```

**Comment by ichorid** [comment]
:tada:
