### ISSUE TITLE
[Reproducible Bug] "updated outside of current transaction" even though it wasn't

### ISSUE THREAD

**Issue by Elijas** [ponyorm/pony#434]
Test code:
```
from datetime import datetime

from pony.orm import *

db = Database()


class Order(db.Entity):
    id = PrimaryKey(int, auto=True)
    id_in_shop = Required(int, size=64, unique=True)
    created_at_in_shop = Required(datetime)


db.bind(provider='sqlite', filename=':memory:')
db.generate_mapping(create_tables=True)

with db_session:
    Order(id_in_shop=123, created_at_in_shop=datetime.fromisoformat('2018-12-03T17:18:14+02:00'))
    if Order.get(lambda so: so.id_in_shop == 123) is not None:
        print("There is an order 123 already")
```

Output:
```
C:\Users\user\.virtualenvs\pony-orm-bug-test\Scripts\python.exe C:/X9/pony-orm-bug-test/q.py
Traceback (most recent call last):
  File "C:/X9/pony-orm-bug-test/q.py", line 19, in <module>
    if ShopifyOrder.get(lambda so: so.id_in_shop == 123) is not None:
  File "C:\Users\user\.virtualenvs\pony-orm-bug-test\lib\site-packages\pony\orm\core.py", line 3949, in get
    if args: return entity._query_from_args_(args, kwargs, frame_depth=cut_traceback_depth+1).get()
  File "C:\Users\user\.virtualenvs\pony-orm-bug-test\lib\site-packages\pony\orm\core.py", line 5874, in get
    objects = query[:2]
  File "C:\Users\user\.virtualenvs\pony-orm-bug-test\lib\site-packages\pony\orm\core.py", line 6130, in __getitem__
    return query._fetch(limit=stop-start, offset=start)
  File "C:\Users\user\.virtualenvs\pony-orm-bug-test\lib\site-packages\pony\orm\core.py", line 6132, in _fetch
    return QueryResult(query, limit, offset, lazy=lazy)
  File "C:\Users\user\.virtualenvs\pony-orm-bug-test\lib\site-packages\pony\orm\core.py", line 6239, in __init__
    self._items = None if lazy else self._query._actual_fetch(limit, offset)
  File "C:\Users\user\.virtualenvs\pony-orm-bug-test\lib\site-packages\pony\orm\core.py", line 5777, in _actual_fetch
    used_attrs=translator.get_used_attrs())
  File "C:\Users\user\.virtualenvs\pony-orm-bug-test\lib\site-packages\pony\orm\core.py", line 4247, in _fetch_objects
    obj._db_set_(avdict)
  File "C:\Users\user\.virtualenvs\pony-orm-bug-test\lib\site-packages\pony\orm\core.py", line 4871, in _db_set_
    % (obj.__class__.__name__, attr.name, obj, old_dbval, new_dbval))
  File "C:\Users\user\.virtualenvs\pony-orm-bug-test\lib\site-packages\pony\utils\utils.py", line 106, in throw
    raise exc
pony.orm.core.UnrepeatableReadError: Value of ShopifyOrder.created_at_in_shop for ShopifyOrder[1] was updated outside of current transaction (was: datetime.datetime(2018, 12, 3, 17, 18, 14, tzinfo=datetime.timezone(datetime.timedelta(seconds=7200))), now: '2018-12-03 17:18:14+02:00')

Process finished with exit code 1

```

Happens for both, SQLite PostgreSQL, Pony v0.7.9

**Comment by craftyguy** [comment]
@Elijas were you able to implement your workaround in a hybrid method/@property in the entity? Seems like there might be an unrelated bug with accessing external modules/methods from within a hybrid method (everything is an 'invalid type').. but I may not be doing it correctly.

**Comment by Elijas** [comment]
@craftyguy Disclaimer, just my opinion ahead, I'm not a dev or Pony pro and most likely be wrong :)

Pony works by "[hijacking](https://docs.python.org/3/library/ast.html)" python code from the interpreter itself in order to translate it to SQL. The limitation is that only a limited subset of python works, and only in a limited way (For example, if I remember correctly, I could not move a lambda function out of a query to an external variable).

Entity methods/properties might be under this trade-off too, so that you'd be able to use your custom made one-liner* Entity properties in queries, for example.

I'd recommend either moving the functionality to other class/function or using a wrapper function, with the additional methods added here, because when they won't be picked up by the Pony's translation-to-SQL and you'll still be able to use all of the other Entity properties/functions.

```
class Wrapper(object):
    '''
    Object wrapper class.
    This a wrapper for objects. It is initialiesed with the object to wrap
    and then proxies the unhandled getattribute methods to it.
    Other classes are to inherit from it.
    '''
    def __init__(self, obj):
        '''
        Wrapper constructor.
        @param obj: object to wrap
        '''
        # wrap the object
        self._wrapped_obj = obj

    def __getattr__(self, attr):
        # see if this object has attr
        # NOTE do not use hasattr, it goes into
        # infinite recurrsion
        if attr in self.__dict__:
            # this object has it
            return getattr(self, attr)
        # proxy to the wrapped object
        return getattr(self._wrapped_obj, attr)
```
[source](https://code.activestate.com/recipes/577555-object-wrapper-class/)

* Entity properties are limited to one python code line, if I remember correctly

**Comment by craftyguy** [comment]
@Elijas 

Thanks for the response/details, I appreciate it. Yet this is the exact issue I hit when trying to use a 'hybrid method' (interestingly enough, sqlalchemy's hybrid_method stuff seems to provide exactly what I want?).

I was hoping to avoid wrapping entities, but I guess I have no choice until this issue is resolved.

**Comment by jamie--stewart** [comment]
Hey both, I ran into this exact same issue earlier, and found another possible workaround:

In my Pony Entity class I've updated my attribute like so:

```
price_timestamp = Required(datetime, sql_type='TIMESTAMP WITH TIME ZONE')
```

☝️ [@kozlovsky's comment in #9](https://github.com/ponyorm/pony/issues/9#issuecomment-18498923) points out that you can add a `sql_type` to your attribute definition. [Docs reference here too](https://docs.ponyorm.org/api_reference.html#cmdoption-arg-sql-type)

Doing that, and also migrating my column in the DB to a `TIMESTAMP WITH TIME ZONE` has fixed my issue (which was creating an entity with the timezone stored in the first place, and then my code thinking that field required an update because it was comparing unaware/aware `datetime`s)

I know that you cite SQLite in your original issue, and I'm using PostgreSQL so not sure if it will ultimately be of any use to you. I like your workaround too 👍

**Comment by Elijas** [comment]
> **EDIT** I _may_ have spoken too soon, I was just testing with UTC. Testing with a different timezone is now failing (the timezone isn't reaching the DB), though my code doesn't fall over in the same way that you describe in the original post any more
> 
> Hey both, I ran into this exact same issue earlier, and found another possible workaround:
> 
> In my Pony Entity class I've updated my attribute like so:
> 
> ```
> price_timestamp = Required(datetime, sql_type='TIMESTAMP WITH TIME ZONE')
> ```
> 
> ☝️ [@kozlovsky's comment in #9](https://github.com/ponyorm/pony/issues/9#issuecomment-18498923) points out that you can add a `sql_type` to your attribute definition. [Docs reference here too](https://docs.ponyorm.org/api_reference.html#cmdoption-arg-sql-type)
> 
> Doing that, and also migrating my column in the DB to a `TIMESTAMP WITH TIME ZONE` has fixed my issue (which was creating an entity with the timezone stored in the first place, and then my code thinking that field required an update because it was comparing unaware/aware `datetime`s)
> 
> I know that you cite SQLite in your original issue, and I'm using PostgreSQL so not sure if it will ultimately be of any use to you. I like your workaround too 👍

I was using PostgreSQL too, SQLite test was just there to illustrate the point that it isn't an issue with *only* a certain database back-end.

Let us know if you'll find a workaround! Great work so far, regardless🙌

**Comment by lambda-xyz** [comment]
This bug should be fixed because in some situation, PonyORM is not able to give you back a `datetime`. When the function [`sql2py()`](https://github.com/ponyorm/pony/blob/b991846669f58fc71a6c6ba2f03633ad2606809d/pony/orm/dbproviders/sqlite.py#L220) of `SQLiteDatetimeConverter` is called, it returns `str` in specific case.

The code below allows to reproduce the bug:

```python
from datetime import datetime, timezone

from pony.orm import Database, Optional, db_session


db = Database('sqlite', 'test.sqlite', create_db=True)

class Product(db.Entity):
    name = Optional(str)
    creation_date = Optional(datetime, volatile=True)

db.generate_mapping(create_tables=True)


with db_session:
    dt = datetime(2019, 8, 12, 17, 26, 3)
    dt_with_ms = datetime(2019, 8, 12, 17, 26, 3, 1332)
    dt_with_tz = datetime(2019, 8, 12, 17, 26, 3, tzinfo=timezone.utc)
    dt_with_ms_and_tz = datetime(2019, 8, 12, 17, 26, 3, 1332, tzinfo=timezone.utc)

    coca = Product(name='coca-cola', creation_date=dt)
    pepsi = Product(name='pepsi', creation_date=dt_with_ms)
    fanta = Product(name='fanta', creation_date=dt_with_tz)
    schweppes = Product(name='schweppes', creation_date=dt_with_ms_and_tz)

    print(coca.to_dict())
    print(pepsi.to_dict())
    print(fanta.to_dict())
    print(schweppes.to_dict())

    db.Product.select()[:].show(500)
```

It will output:
```python
{'id': 1, 'name': 'coca-cola', 'creation_date': datetime.datetime(2019, 8, 12, 17, 26, 3)}
{'id': 2, 'name': 'pepsi', 'creation_date': datetime.datetime(2019, 8, 12, 17, 26, 3, 1332)}
{'id': 3, 'name': 'fanta', 'creation_date': '2019-08-12 17:26:03+00:00'}
{'id': 4, 'name': 'schweppes', 'creation_date': datetime.datetime(2019, 8, 12, 17, 26, 3, 1332)}
```
I think a quick fix could be to write [`datetime2timestamp`](https://github.com/ponyorm/pony/blob/b991846669f58fc71a6c6ba2f03633ad2606809d/pony/utils/utils.py#L245) and [`timestamp2datetime`](https://github.com/ponyorm/pony/blob/b991846669f58fc71a6c6ba2f03633ad2606809d/pony/utils/utils.py#L250) like this:

```python
def datetime2timestamp(d):
    # unfortunately d.isoformat(' ', timespec='microseconds') works only with python>=3.6
    return d.strftime("%Y-%m-%d %H:%M:%S.%f%z")  # always write microseconds and timezone if any

def timestamp2datetime(t):
    try:
        return datetime.strptime(t, '%Y-%m-%d %H:%M:%S.%f%z')  # timezone
    except ValueError:
        return datetime.strptime(t, '%Y-%m-%d %H:%M:%S.%f')  # no timezone
```

**Comment by rokclimb15** [comment]
In MySQL prior to 8.0.19 it is very common to convert dates with timezones to UTC for storage which makes the quick fix in https://github.com/ponyorm/pony/issues/434#issue-420632554 a decent solution. It doesn't very elegantly handle conversion/display when this value is retrieved again, which is available in 8.0.19.

Would anyone be interested in a patch to enable TZ storage of datetime if the server is new enough to support it?

**Comment by nm17** [comment]
Any ETA on this? This is a very important issue.

**Comment by j4hangir** [comment]
This one just came to my attention when doing a datetime comparison using lambdas. All date in the database are stored in UTC, and the given datetime in a timezone-aware datetime, yet the comparison ignores it and hence some weird bugs.

**Comment by j4hangir** [comment]
I have this weird bug, when I do this:

Attribute:
```py
from datetime import datetime as DT
    edited: DT = Optional(DT, nullable=True)
```

Tx:
```py
ret.edited = DT.now()
```

That works, but this throws the following error:

```py
ret.edited = DT.now(datetime.UTC)
```
**Value of MessageText.edited for MessageText[1227] was updated outside of current transaction (was: datetime.datetime(2024, 5, 27, 0, 55, 41, tzinfo=datetime.timezone.utc), now: datetime.datetime(2024, 5, 27, 0, 55, 41))**


The `edited` is of course never set or modified elsewhere and visibly something goes off when datetime has UTC timezone.

**Comment by motel480** [comment]
@nm17 https://pythondev.space/questions/exploring-the-world-of-timezones-in-python-and-sql
