### ISSUE TITLE
AssertionError error trying to change Required relation to Optional

### ISSUE THREAD

**Issue by xzitlou** [ponyorm/pony#442]
I'm getting `AssertionError: Not implemented` when I tried to change a relation between 2 models to Required to Optional.

Steps to reproduce:
I got in my model `user = Required(lambda: User` and then change it to `user = Optional(lambda: User, default=None, nullable=True)`
`python migrate.py make`, no errors
`python migrate.py apply`:

`Applied:
Traceback (most recent call last):
  File "migrate.py", line 8, in <module>
    models.db.migrate(**app.config['DB_PARAMS'])
  File "/home/www/env/lib/python3.6/site-packages/pony/orm/core.py", line 728, in migrate
    return migrate(self, command)
  File "/home/www/env/lib/python3.6/site-packages/pony/migrate/command.py", line 61, in migrate
    return _migrate(db, cmd, **kwargs)
  File "/home/www/env/lib/python3.6/site-packages/pony/migrate/command.py", line 102, in _migrate
    graph.apply(db=db, is_fake=fake_initial, dry_run=dry, name_start=start, name_end=end)
  File "/home/www/env/lib/python3.6/site-packages/pony/migrate/migration.py", line 383, in apply
    upgrade_db(new_db, dic)
  File "/home/www/env/lib/python3.6/site-packages/pony/migrate/migration.py", line 53, in upgrade_db
    op.apply(db)
  File "/home/www/env/lib/python3.6/site-packages/pony/migrate/diagram_ops.py", line 154, in apply
    assert False, 'Not implemented'
AssertionError: Not implemented`

**Comment by xzitlou** [comment]
Any help on this issue?
