### ISSUE TITLE
pony.orm.dbapiprovider.OperationalError: FATAL:  sorry, too many clients already

### ISSUE THREAD

**Issue by nadermx** [ponyorm/pony#457]
I'm currently running pony migrations on a production server.  I have increased the number of connections up to 300, but still seem to have this error happen a lot.  I feel I will have to increase the server to 1000 connections and configure or install `PgBouncer`.
As I had understood, I thought pony had a built in connection pool?
```
Traceback (most recent call last):
  File "/home/www/env/lib/python3.7/site-packages/pony/orm/dbapiprovider.py", line 53, in wrap_dbapi_exceptions
    return func(provider, *args, **kwargs)
  File "/home/www/env/lib/python3.7/site-packages/pony/orm/dbapiprovider.py", line 276, in connect
    return provider.pool.connect()
  File "/home/www/env/lib/python3.7/site-packages/pony/orm/dbapiprovider.py", line 406, in connect
    pool._connect()
  File "/home/www/env/lib/python3.7/site-packages/pony/orm/dbproviders/postgres.py", line 230, in _connect
    pool.con = pool.dbapi_module.connect(*pool.args, **pool.kwargs)
  File "/home/www/env/lib/python3.7/site-packages/psycopg2/__init__.py", line 126, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: FATAL:  sorry, too many clients already
FATAL:  sorry, too many clients already


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/www/env/lib/python3.7/site-packages/rq/worker.py", line 799, in perform_job
    rv = job.perform()
  File "/home/www/env/lib/python3.7/site-packages/rq/job.py", line 600, in perform
    self._result = self._execute()
  File "/home/www/env/lib/python3.7/site-packages/rq/job.py", line 606, in _execute
    return self.func(*self.args, **self.kwargs)
  File "./search.py", line 15, in youtube_search
    db.connect(allow_auto_upgrade=True, **app_config.DB_PARAMS)
  File "/home/www/env/lib/python3.7/site-packages/pony/orm/core.py", line 713, in connect
    self._bind(*args, **kwargs)
  File "/home/www/env/lib/python3.7/site-packages/pony/orm/core.py", line 750, in _bind
    self.provider = provider_cls(self, *args, **kwargs)
  File "/home/www/env/lib/python3.7/site-packages/pony/orm/dbapiprovider.py", line 126, in __init__
    connection, is_new_connection = provider.connect()
  File "<string>", line 2, in connect
  File "/home/www/env/lib/python3.7/site-packages/pony/orm/dbapiprovider.py", line 64, in wrap_dbapi_exceptions
    raise OperationalError(e)
pony.orm.dbapiprovider.OperationalError: FATAL:  sorry, too many clients already
FATAL:  sorry, too many clients already
```

**Comment by nadermx** [comment]
It seemd to be my flask app that had the issue.

**Comment by nadermx** [comment]
Nevermind, the error still occurs

**Comment by justonlyyo** [comment]
Try to edit it 
![image](https://user-images.githubusercontent.com/20040033/97950044-8b282880-1dd0-11eb-86e6-204bef2dac7e.png)
