### ISSUE TITLE
Issue installing pony migrations

### ISSUE THREAD

**Issue by nadermx** [ponyorm/pony#475]
Before I was able to install pony migrations branch via 

```
pip install git+git://github.com/ponyorm/pony.git@orm-migrations
```
But it seems since the newest update, that this is no longer the case, it instead causes this error

```
Collecting git+git://github.com/ponyorm/pony.git@orm-migrations
  Cloning git://github.com/ponyorm/pony.git (to revision orm-migrations) to /tmp/pip-req-build-rm8mkph9
  Running command git clone -q git://github.com/ponyorm/pony.git /tmp/pip-req-build-rm8mkph9
  Running command git checkout -b orm-migrations --track origin/orm-migrations
  Switched to a new branch 'orm-migrations'
  Branch 'orm-migrations' set up to track remote branch 'orm-migrations' from 'origin'.
    ERROR: Command errored out with exit status 1:
     command: /home/john/.virtualenvs/doc/bin/python3.6 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-rm8mkph9/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-rm8mkph9/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-req-build-rm8mkph9/pip-egg-info
         cwd: /tmp/pip-req-build-rm8mkph9/
    Complete output (6 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-rm8mkph9/setup.py", line 137
        install_requires=REQUIRES,
                       ^
    SyntaxError: invalid syntax
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by kozlovsky** [comment]
Thanks, should work now
