### ISSUE TITLE
Getting a KeyError trying to delete an entity

### ISSUE THREAD

**Issue by NiklasRosenstein** [ponyorm/pony#480]
Hey, I'm using pony==0.7.11

My `Token` model looks like this:

```python
class Token(db.Entity):
  user = orm.Required(User)
  value = orm.Required(str, unique=True, default=lambda: str(uuid.uuid4()))
  expires_at = orm.Required(datetime, default=lambda: datetime.utcnow() + timedelta(days=2))
  orm.PrimaryKey(user, value)
```

When I try to delete a token I get a `KeyError` from `core.py` in `_delete_()` (full traceback below).

Code that deletes the token:

```python
    with orm.db_session(sql_debug=True):
      token = Token.get(value=args.revoke_token)
      print(token)
      if not token:
        parser.error('token does not exist or already revoked')
      token.delete()
    return 0
```

Outputs

```
GET NEW CONNECTION
SWITCH TO AUTOCOMMIT MODE
SELECT "user", "value", "expires_at"
FROM "Token"
WHERE "value" = ?
['140deac9-e38c-4ea8-938f-a1bd641628c8']

Token[User['admin'],'140deac9-e38c-4ea8-938f-a1bd641628c8']
ROLLBACK
RELEASE CONNECTION
Traceback (most recent call last):
  File "/Users/nrosenstein/miniconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/nrosenstein/miniconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/nrosenstein/Projects/bbplay/bbplay-server/src/bbplay/server/app.py", line 67, in <module>
    main()
  File "/Users/nrosenstein/Projects/bbplay/bbplay-server/src/bbplay/server/app.py", line 53, in main
    token.delete()
  File "/Users/nrosenstein/Projects/.venv/lib/python3.7/site-packages/pony/orm/core.py", line 5038, in delete
    obj._delete_()
  File "/Users/nrosenstein/Projects/.venv/lib/python3.7/site-packages/pony/orm/core.py", line 4997, in _delete_
    obj2 = cache_index.pop(val)
KeyError: '140deac9-e38c-4ea8-938f-a1bd641628c8'
```

Am I doing something wrong or is this a bug?

Thank you

**Comment by jafet-gonzalez** [comment]
im having the same issue , does anyone knows how to solve it ?
