### ISSUE TITLE
Assertion error with Flask integration

### ISSUE THREAD

**Issue by zgoda** [ponyorm/pony#481]
Pony throws `AssertionError` upon any subsequent operation after Flask raises exception:

```
127.0.0.1 - - [28/Dec/2019 14:37:52] "POST /api/poll/2/vote HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/jarek/work/polls/venv/lib/python3.8/site-packages/flask/app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/jarek/work/polls/venv/lib/python3.8/site-packages/flask/app.py", line 2449, in wsgi_app
    response = self.handle_exception(e)
  File "/home/jarek/work/polls/venv/lib/python3.8/site-packages/flask/app.py", line 1866, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/jarek/work/polls/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/jarek/work/polls/venv/lib/python3.8/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/jarek/work/polls/venv/lib/python3.8/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/jarek/work/polls/venv/lib/python3.8/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/jarek/work/polls/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/jarek/work/polls/venv/lib/python3.8/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jarek/work/polls/venv/lib/python3.8/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "<string>", line 2, in vote
    from pony.orm import db_session
  File "/home/jarek/work/polls/venv/lib/python3.8/site-packages/pony/orm/core.py", line 515, in new_func
    return func(*args, **kwargs)
  File "/home/jarek/work/polls/src/polls/api/views.py", line 30, in vote
    option.votes.create()
AttributeError: 'NoneType' object has no attribute 'votes'
```

Normal unhandled error in view function code that results in HTTP 500. And then any further operation ends with:

```
127.0.0.1 - - [28/Dec/2019 14:37:56] "GET / HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/jarek/work/polls/venv/lib/python3.8/site-packages/flask/app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/jarek/work/polls/venv/lib/python3.8/site-packages/flask/app.py", line 2449, in wsgi_app
    response = self.handle_exception(e)
  File "/home/jarek/work/polls/venv/lib/python3.8/site-packages/flask/app.py", line 1866, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/jarek/work/polls/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/jarek/work/polls/venv/lib/python3.8/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/jarek/work/polls/venv/lib/python3.8/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/jarek/work/polls/venv/lib/python3.8/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/jarek/work/polls/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/jarek/work/polls/venv/lib/python3.8/site-packages/flask/app.py", line 1947, in full_dispatch_request
    rv = self.preprocess_request()
  File "/home/jarek/work/polls/venv/lib/python3.8/site-packages/flask/app.py", line 2241, in preprocess_request
    rv = func()
  File "/home/jarek/work/polls/venv/lib/python3.8/site-packages/pony/flask/__init__.py", line 7, in _enter_session
    session.__enter__()
  File "/home/jarek/work/polls/venv/lib/python3.8/site-packages/pony/orm/core.py", line 459, in __enter__
    db_session._enter()
  File "/home/jarek/work/polls/venv/lib/python3.8/site-packages/pony/orm/core.py", line 462, in _enter
    assert not local.db_context_counter
AssertionError
```

Integration is done as described in https://docs.ponyorm.org/integration_with_flask.html.

**Comment by sashaaero** [comment]
Hello, @zgoda! Thank for reporting.
Can you provide simple example to reproduce the error?

**Comment by zgoda** [comment]
See https://github.com/zgoda/issues/blob/master/pony/assert-after-500/src/polls/app.py

After request to `/unhandled` the request to `/` fails with this exact error:

```
127.0.0.1 - - [09/Jan/2020 15:26:12] "GET /unhandled HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/jazg/work/issues/venv/lib/python3.8/site-packages/flask/app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/jazg/work/issues/venv/lib/python3.8/site-packages/flask/app.py", line 2449, in wsgi_app
    response = self.handle_exception(e)
  File "/home/jazg/work/issues/venv/lib/python3.8/site-packages/flask/app.py", line 1866, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/jazg/work/issues/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/jazg/work/issues/venv/lib/python3.8/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/jazg/work/issues/venv/lib/python3.8/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/jazg/work/issues/venv/lib/python3.8/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/jazg/work/issues/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/jazg/work/issues/venv/lib/python3.8/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jazg/work/issues/venv/lib/python3.8/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/jazg/work/issues/pony/assert-after-500/src/polls/app.py", line 17, in unhandled
    p.to_dict(with_collections=True) for p in Poll.select().order_by(Poll.x)
AttributeError: type object 'Poll' has no attribute 'x'
127.0.0.1 - - [09/Jan/2020 15:26:24] "GET / HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/jazg/work/issues/venv/lib/python3.8/site-packages/flask/app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/jazg/work/issues/venv/lib/python3.8/site-packages/flask/app.py", line 2449, in wsgi_app
    response = self.handle_exception(e)
  File "/home/jazg/work/issues/venv/lib/python3.8/site-packages/flask/app.py", line 1866, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/jazg/work/issues/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/jazg/work/issues/venv/lib/python3.8/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/jazg/work/issues/venv/lib/python3.8/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/jazg/work/issues/venv/lib/python3.8/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/jazg/work/issues/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/jazg/work/issues/venv/lib/python3.8/site-packages/flask/app.py", line 1947, in full_dispatch_request
    rv = self.preprocess_request()
  File "/home/jazg/work/issues/venv/lib/python3.8/site-packages/flask/app.py", line 2241, in preprocess_request
    rv = func()
  File "/home/jazg/work/issues/venv/lib/python3.8/site-packages/pony/flask/__init__.py", line 7, in _enter_session
    session.__enter__()
  File "/home/jazg/work/issues/venv/lib/python3.8/site-packages/pony/orm/core.py", line 459, in __enter__
    db_session._enter()
  File "/home/jazg/work/issues/venv/lib/python3.8/site-packages/pony/orm/core.py", line 462, in _enter
    assert not local.db_context_counter
AssertionError
```

**Comment by tonyc-blastpoint** [comment]
@zgoda , I'm seeing this as well when running Flask in debug mode.  A solution I found via pallets/flask#2563 is to set `PRESERVE_CONTEXT_ON_EXCEPTION` to `False` in Flask config.  Since `teardown_request` isn't called, I'm not sure there's anything Pony can do to fix.

**Comment by tonycpsu** [comment]
@zgoda , I'm seeing this as well when running Flask in debug mode. A solution I found via pallets/flask#2563 is to set PRESERVE_CONTEXT_ON_EXCEPTION to False in Flask config. Since teardown_request isn't called, I'm not sure there's anything Pony can do to fix.

**Comment by zgoda** [comment]
Thanks @tonycpsu !
