### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'entity'

### ISSUE THREAD

**Issue by nadermx** [ponyorm/pony#507]
Hey all, I'm trying to set up a new box with migrations but using `pip install git+git://github.com/ponyorm/pony.git@orm-migrations` it installs fine, but when I try and run `python migrate.py make` it spits out this error.

It happens on both sqlite and psql

```
Traceback (most recent call last):
  File "migrate.py", line 7, in <module>
    models.db.migrate(**app.config['DB_PARAMS'])
  File "/home/john/.virtualenv/word/lib/python3.6/site-packages/pony/orm/core.py", line 728, in migrate
    return migrate(self, command)
  File "/home/john/.virtualenv/word/lib/python3.6/site-packages/pony/migrate/command.py", line 61, in migrate
    return _migrate(db, cmd, **kwargs)
  File "/home/john/.virtualenv/word/lib/python3.6/site-packages/pony/migrate/command.py", line 96, in _migrate
    return graph.make(db=db, empty=empty, custom=custom, description=name)
  File "/home/john/.virtualenv/word/lib/python3.6/site-packages/pony/migrate/migration.py", line 289, in make
    generated = writer.as_string()
  File "/home/john/.virtualenv/word/lib/python3.6/site-packages/pony/migrate/writer.py", line 351, in as_string
    body = self._get_operations_block(imports)
  File "/home/john/.virtualenv/word/lib/python3.6/site-packages/pony/migrate/writer.py", line 316, in _get_operations_block
    self.operations = self._get_ops()
  File "/home/john/.virtualenv/word/lib/python3.6/site-packages/pony/migrate/writer.py", line 251, in _get_ops
    if attr.entity is not entity: assert False, 'Not implemented'
AttributeError: 'NoneType' object has no attribute 'entity'
```

My models look like this

```

db = Database()


class User(UserMixin, db.Entity):
    password_hash = Optional(unicode)
    email = Required(unicode, unique=True)
    dt_registered = Optional(datetime, default=datetime.utcnow())
    dt_last_visit = Optional(datetime, default=datetime.utcnow())
    verified = Optional(bool, default=False)
    failed_login = Optional(int)
    last_failed_login = Optional(datetime, default=datetime.utcnow())
    payments = Set(lambda: Payment)
    first_name = Optional(unicode)
    last_name = Optional(unicode)
    phone = Optional(unicode)
    address = Optional(unicode)
    address_extra = Optional(unicode)
    city = Optional(unicode)
    postal_code = Optional(unicode)
    state = Optional(unicode)
    plan_subscribed = Optional(unicode)
    suscribed_card = Optional(unicode)
    is_plan_active = Optional(bool, default=False)
    used_card_brand = Optional(unicode)
    used_card_exp_month = Optional(unicode)
    used_card_exp_year = Optional(unicode)
    used_card_last_digits = Optional(unicode)
    next_bill_at = Optional(datetime, nullable=True)
    uuid = Optional(unicode)

class Payment(db.Entity):
    FAILED = 'failed'
    COMPLETED = 'completed'
    PENDING = 'pending'

    user = Optional(lambda: User)
    payment_token = Optional(unicode)
    customer_token = Optional(unicode)
    card_token = Optional(unicode)
    payment_comment = Optional(unicode, nullable=True)
    status = Optional(unicode, default=PENDING)
    day = Optional(datetime, default=datetime.utcnow())
    plan = Optional(unicode)
    amount = Optional(int)
    used_card_brand = Optional(unicode)
    used_card_exp_month = Optional(unicode)
    used_card_exp_year = Optional(unicode)
    used_card_last_digits = Optional(unicode)
    paypal_info = Optional(Json)


class TranslationBase(db.Entity):
    value = Required(unicode, unique=True)
    content = Required(unicode)
    translated = Required(bool, default=False)



class Translation(db.Entity):
    value = Required(unicode)
    content = Optional(unicode, nullable=True)
    language = Required(unicode)



class Lang(db.Entity):
    iso = Required(unicode, unique=True)
    text = Required(unicode)


class LangCode(db.Entity):
    code = Required(unicode, unique=True)

class Conversion(db.Entity):
    format = Optional(unicode)
    ip_address = Optional(unicode)


class Rating(db.Entity):
    format = Optional(unicode)
    value = Optional(int)
    ip_address = Optional(unicode)


sql_debug(False)
```

**Comment by nadermx** [comment]
nvm, had old migrations files
