### ISSUE TITLE
Pony complains about db_session in interactive mode?

### ISSUE THREAD

**Issue by larsks** [ponyorm/pony#557]
According to the documentation:

> When you work with Python’s interactive shell you don’t need to worry about the database session, because it is maintained by Pony automatically.

But when I start an interactive shell like this:

```
python -i stub.py
```

Where `stub.py` contains:

```
from paprika import models

db = models.db
db.bind(provider='sqlite', filename=':memory:', create_db=True)
db.generate_mapping(create_tables=True)
```

Any attempt to instantiate a an entity fails:

```
>>> r1 = models.RecipeIndex(hash='1', uid='1')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/lars/.local/share/virtualenvs/paprika-afSPngZJ/lib/python3.7/site-packages/pony/orm/core.py", line 4702, in __init__
    cache = entity._database_._get_cache()
  File "/home/lars/.local/share/virtualenvs/paprika-afSPngZJ/lib/python3.7/site-packages/pony/orm/core.py", line 855, in _get_cache
    ): throw(TransactionError, 'db_session is required when working with the database')
  File "/home/lars/.local/share/virtualenvs/paprika-afSPngZJ/lib/python3.7/site-packages/pony/utils/utils.py", line 106, in throw
    raise exc
pony.orm.core.TransactionError: db_session is required when working with the database
```

There's a disconnect here between my experience and the documentation. What am I doing wrong?

**Comment by cmacht** [comment]
I don't think you are creating the database in the interactive session, you are creating it in `paprika.py`, correct?

I played around with your example and the problem seems to be executing the scripts with `-i`. Using both, a `models.py` and a `stub.py` file I can get it to work just fine, when I import them after opening the shell:

```
[cmacht@hal]$ python
Python 3.9.7 (default, Oct 10 2021, 15:13:22) 
[GCC 11.1.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from models import *
>>> from stub import *
>>> r1 = Person(name='Hans', age=5)
>>> r1
Person[new:1]
>>> db.commit()
>>> r1
Person[1]
>>> 
```
