### ISSUE TITLE
pony.orm.core.TransactionError when calling aiohttp

### ISSUE THREAD

**Issue by nomme** [ponyorm/pony#610]
Test code
```python
% cat test.py                                 
import aiohttp
import asyncio
from pony.orm import Database, Required, db_session, commit

db = Database()

class DbTest(db.Entity):
    string = Required(str)

@db_session
async def http_first():
    await call_aiohttp("http_first")
    db_test = DbTest(
        string="hello_http",
    )

@db_session
async def db_first():
    db_test = DbTest(
        string="hello_db",
    )
    await call_aiohttp("db_first")

async def call_aiohttp(first):
    async with aiohttp.ClientSession() as session:
        async with session.get('http://httpbin.org/get') as resp:
            print(first, resp.status)

async def start():
    await http_first()
    await db_first()

db.bind("sqlite", filename=":memory:")
db.generate_mapping(create_tables=True)

loop = asyncio.get_event_loop()
loop.run_until_complete(start())
```

will give you the following output.

```bash
% python test.py                                                                                       
http_first 200
Traceback (most recent call last):
  File "test.py", line 37, in <module>
    loop.run_until_complete(start())
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "test.py", line 31, in start
    await db_first()
  File "/home/hogklint/tmp/pony_test/venv/lib/python3.8/site-packages/pony/orm/core.py", line 615, in new_gen_func
    output = wrapped_interact(iterator)
  File "/home/hogklint/tmp/pony_test/venv/lib/python3.8/site-packages/pony/orm/core.py", line 601, in wrapped_interact
    rollback_and_reraise(sys.exc_info())
  File "/home/hogklint/tmp/pony_test/venv/lib/python3.8/site-packages/pony/orm/core.py", line 375, in rollback_and_reraise
    reraise(*exc_info)
  File "/home/hogklint/tmp/pony_test/venv/lib/python3.8/site-packages/pony/utils/utils.py", line 95, in reraise
    try: raise exc.with_traceback(tb)
  File "/home/hogklint/tmp/pony_test/venv/lib/python3.8/site-packages/pony/orm/core.py", line 598, in wrapped_interact
    if cache.modified or cache.in_transaction: throw(TransactionError,
  File "/home/hogklint/tmp/pony_test/venv/lib/python3.8/site-packages/pony/utils/utils.py", line 106, in throw
    raise exc
pony.orm.core.TransactionError: You need to manually commit() changes before suspending the generator
```
If the call to aiohttp is done first, everything seems to work as expected. But when the database object is instantiated first, this exception occurs. I assume something messes with the database transaction, but I haven't found anything useful yet.
Does someone have any idea what might be wrong?

```bash
% python -m pip freeze
aiohttp==3.7.4.post0
async-timeout==3.0.1
attrs==21.2.0
chardet==4.0.0
idna==3.2
multidict==5.1.0
pony==0.7.14
typing-extensions==3.10.0.2
yarl==1.6.3
% python --version
Python 3.8.8
```

**Comment by thexcw** [comment]
> Pony was not developed for async usage, and it may be tricky to use it correctly in an async environment. However, if only part of your application is async, you will be fine if you stick to these two rules: You cannot use the @db_session decorator on async functions, use a context manager for wrapping lines of code that really work with the database. Secondly, do not call async functions inside a db_session, only normal function calls are possible.

[pony docs - async and db session](https://docs.ponyorm.org/integration_with_fastapi.html#async-and-db-session)

**Comment by nomme** [comment]
Thanks @thexcw! A reminder to myself to read the documentation more carefully.
