### ISSUE TITLE
0.7.15rc1 IndexError: list index out of range

### ISSUE THREAD

**Issue by andreymal** [ponyorm/pony#626]
```python
from datetime import datetime, timedelta
from pony.orm import *

db = Database()

class TestPost(db.Entity):
    dt = Required(datetime)

db.bind('sqlite', ':memory:')
db.generate_mapping(create_tables=True)

with db_session:
    TestPost.select(
        lambda x: x.dt > datetime.utcnow() - timedelta(days=1)
    )
```

---

```
Traceback (most recent call last):
  File "ponytest.py", line 13, in <module>
    TestPost.select(
  File "site-packages/pony/orm/core.py", line 4035, in select
    if args: query = entity._query_from_args_(args, kwargs, frame_depth=cut_traceback_depth+1)
  File "site-packages/pony/orm/core.py", line 4409, in _query_from_args_
    return Query(code_key, inner_expr, globals, locals, cells)
  File "site-packages/pony/orm/core.py", line 5686, in __init__
    tree, extractors = create_extractors(code_key, tree, globals, locals, special_functions, const_functions)
  File "site-packages/pony/orm/asttranslation.py", line 446, in create_extractors
    src = node.src = ast2src(node)
  File "site-packages/pony/orm/asttranslation.py", line 75, in ast2src
    PythonTranslator(tree)
  File "site-packages/pony/orm/asttranslation.py", line 89, in __init__
    translator.dispatch(tree)
  File "site-packages/pony/orm/asttranslation.py", line 40, in dispatch
    translator.dispatch(child)
  File "site-packages/pony/orm/asttranslation.py", line 47, in dispatch
    translator.call(post_method, node)
  File "site-packages/pony/orm/asttranslation.py", line 91, in call
    node.src = method(translator, node)
  File "site-packages/pony/orm/asttranslation.py", line 212, in postCall
    if len(args) == 1 and isinstance(node.args[0], ast.GeneratorExp):
IndexError: list index out of range
```

**Comment by sashaaero** [comment]
Hello, thanks for opening an issue.

**Comment by andreymal** [comment]
Oops, I didn't notice this is a duplicate of #625
