### ISSUE TITLE
SQL syntax error with some queries with pony but works fine outside pony (MariaDB)

### ISSUE THREAD

**Issue by Zocker1999NET** [ponyorm/pony#656]
For a specific purpose, I need to execute a SQL query created manually. Running it with `db.execute` (`db = orm.Database()`), it fails after updating the query. However, the exact same query does not fail if executed manually inside `mysql` CLI and phpMyAdmin.

~~And what makes this error more weird, is that if I replace both `* IN (2)` statements (which is the most recent introduced change), it works in pony as well.~~ EDIT: another change seems to introduce this weird error because manually reverting the `IN` statement does not make it work again, need to look into what I've also changed …

Is there anything what pony configures in its DB connection which might interfere with the [`IN` statement](https://mariadb.com/kb/en/in/) I recently introduced?

<details>
<summary>The query</summary>

original query (with trailing whitespaces):
```sql

        START TRANSACTION;
        DELETE QUICK FROM element_lookup_cache
        WHERE collection IN (2);
        INSERT INTO element_lookup_cache (collection, element1, element2) SELECT
            c.id AS collection,
            l1.element AS element1,
            l2.element AS element2
        FROM
            mediacollection c
        INNER JOIN mediacollectionlink l1 ON
            c.id = l1.collection
        INNER JOIN mediacollectionlink l2 ON
            c.id = l2.collection
        INNER JOIN mediaelement e1 ON
            l1.element = e1.id
        INNER JOIN mediaelement e2 ON
            l2.element = e2.id
        WHERE
            (
                l1.season,
                l1.episode,
                e1.release_date,
                e1.id
            ) <(
                l2.season,
                l2.episode,
                e2.release_date,
                e2.id
            ) AND c.watch_in_order
            AND c.id IN (2)
        GROUP BY
            collection,
            element1,
            element2;
        COMMIT;
    
```

in base64-encoded (why is explained below):
```
CiAgICAgICAgU1RBUlQgVFJBTlNBQ1RJT047CiAgICAgICAgREVMRVRFIFFVSUNLIEZST00gZWxlbWVudF9sb29rdXBfY2FjaGUKICAgICAgICBXSEVSRSBjb2xsZWN0aW9uIElOICgyKTsKICAgICAgICBJTlNFUlQgSU5UTyBlbGVtZW50X2xvb2t1cF9jYWNoZSAoY29sbGVjdGlvbiwgZWxlbWVudDEsIGVsZW1lbnQyKSBTRUxFQ1QKICAgICAgICAgICAgYy5pZCBBUyBjb2xsZWN0aW9uLAogICAgICAgICAgICBsMS5lbGVtZW50IEFTIGVsZW1lbnQxLAogICAgICAgICAgICBsMi5lbGVtZW50IEFTIGVsZW1lbnQyCiAgICAgICAgRlJPTQogICAgICAgICAgICBtZWRpYWNvbGxlY3Rpb24gYwogICAgICAgIElOTkVSIEpPSU4gbWVkaWFjb2xsZWN0aW9ubGluayBsMSBPTgogICAgICAgICAgICBjLmlkID0gbDEuY29sbGVjdGlvbgogICAgICAgIElOTkVSIEpPSU4gbWVkaWFjb2xsZWN0aW9ubGluayBsMiBPTgogICAgICAgICAgICBjLmlkID0gbDIuY29sbGVjdGlvbgogICAgICAgIElOTkVSIEpPSU4gbWVkaWFlbGVtZW50IGUxIE9OCiAgICAgICAgICAgIGwxLmVsZW1lbnQgPSBlMS5pZAogICAgICAgIElOTkVSIEpPSU4gbWVkaWFlbGVtZW50IGUyIE9OCiAgICAgICAgICAgIGwyLmVsZW1lbnQgPSBlMi5pZAogICAgICAgIFdIRVJFCiAgICAgICAgICAgICgKICAgICAgICAgICAgICAgIGwxLnNlYXNvbiwKICAgICAgICAgICAgICAgIGwxLmVwaXNvZGUsCiAgICAgICAgICAgICAgICBlMS5yZWxlYXNlX2RhdGUsCiAgICAgICAgICAgICAgICBlMS5pZAogICAgICAgICAgICApIDwoCiAgICAgICAgICAgICAgICBsMi5zZWFzb24sCiAgICAgICAgICAgICAgICBsMi5lcGlzb2RlLAogICAgICAgICAgICAgICAgZTIucmVsZWFzZV9kYXRlLAogICAgICAgICAgICAgICAgZTIuaWQKICAgICAgICAgICAgKSBBTkQgYy53YXRjaF9pbl9vcmRlcgogICAgICAgICAgICBBTkQgYy5pZCBJTiAoMikKICAgICAgICBHUk9VUCBCWQogICAgICAgICAgICBjb2xsZWN0aW9uLAogICAgICAgICAgICBlbGVtZW50MSwKICAgICAgICAgICAgZWxlbWVudDI7CiAgICAgICAgQ09NTUlUOwogICAg
```

To ensure I try to execute the same query (from using indented f-strings, the query contains many spaces & new lines, which should not modify the query), I log the query base64-encoded with `base64.b64encode(sql.encode("utf-8")`, copy the raw base64 string from the log and decode it in the clipboard (`wl-paste | base64 -d | wl-copy` in Wayland on Linux).

</details>

<details>
<summary>Full error message</summary>

Full error message copied from the output of `docker-compose logs`:
```
main_1  | During handling of the above exception, another exception occurred:
main_1  | Traceback (most recent call last):
main_1  |   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 2077, in wsgi_appmain_1  |     response = self.full_dispatch_request()
main_1  |   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1525, in full_dispatch_requestmain_1  |     rv = self.handle_user_exception(e)
main_1  |   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1523, in full_dispatch_requestmain_1  |     rv = self.dispatch_request()
main_1  |   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1509, in dispatch_requestmain_1  |     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
main_1  |   File "/usr/src/app/app.py", line 873, in force_refresh_collectionmain_1  |     update_element_lookup_cache([coll.id])
main_1  |   File "/usr/src/app/entertainment_decider/models.py", line 1078, in update_element_lookup_cachemain_1  |     db.execute(sql)
main_1  |   File "/usr/local/lib/python3.10/site-packages/pony/orm/core.py", line 870, in executemain_1  |     return database._exec_raw_sql(sql, globals, locals, frame_depth=cut_traceback_depth+1, start_transaction=True)
main_1  |   File "/usr/local/lib/python3.10/site-packages/pony/orm/core.py", line 882, in _exec_raw_sql
main_1  |     return database._exec_sql(adapted_sql, arguments, False, start_transaction)main_1  |   File "/usr/local/lib/python3.10/site-packages/pony/orm/core.py", line 945, in _exec_sql
main_1  |     connection = cache.reconnect(e)
main_1  |   File "/usr/local/lib/python3.10/site-packages/pony/orm/core.py", line 1779, in reconnect
main_1  |     if not provider.should_reconnect(exc): reraise(*sys.exc_info())main_1  |   File "/usr/local/lib/python3.10/site-packages/pony/utils/utils.py", line 88, in reraise
main_1  |     try: raise exc.with_traceback(tb)main_1  |   File "/usr/local/lib/python3.10/site-packages/pony/orm/core.py", line 943, in _exec_sql
main_1  |     try: new_id = provider.execute(cursor, sql, arguments, returning_id)main_1  |   File "<string>", line 2, in execute
main_1  |   File "/usr/local/lib/python3.10/site-packages/pony/orm/dbapiprovider.py", line 64, in wrap_dbapi_exceptionsmain_1  |     raise ProgrammingError(e)
main_1  | pony.orm.dbapiprovider.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'DELETE QUICK FROM element_lookup_cache\n        WHERE collection IN (2);\n     ...' at line 2")
```

**Comment by Zocker1999NET** [comment]
Sorry for the issue report, I discovered that similar to other methods from other libraries, `db.execute` seems to not support multiple queries (properly or at all?). I'm assuming I remembered incorrectly that multiple queries with a method call worked before. I fixed it very simple by splitting the original SQL request: (but will rewrite it know so no split is required)
```python
for q in sql.split(";"):
        q = q.strip()
        if q:
            db.execute(q)
```
