### ISSUE TITLE
test_json fails with sqlite 3.45

### ISSUE THREAD

**Issue by antonio-rojas** [ponyorm/pony#704]
With sqlite 3.45, `test_json` fails with multiple errors like
```
ERROR: test_query_float (test_json.TestJson.test_query_float)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "<string>", line 2, in test_query_float
  File "/build/python-pony/src/pony-0.7.17/pony/orm/core.py", line 519, in new_func
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/build/python-pony/src/pony-0.7.17/pony/orm/tests/test_json.py", line 91, in test_query_float
    self.assertAlmostEqual(val, 9.7)
  File "/usr/lib/python3.11/unittest/case.py", line 904, in assertAlmostEqual
    diff = abs(first - second)
               ~~~~~~^~~~~~~~
TypeError: unsupported operand type(s) for -: 'NoneType' and 'float'
```

**Comment by kozlovsky** [comment]
Thanks for the reporting, it is fixed now.
