### ISSUE TITLE
pony.orm.decompiling.DecompileError: Unsupported operation: POP_JUMP_IF_NOT_NONE

### ISSUE THREAD

**Issue by luup2k** [ponyorm/pony#725]
Script Example on Python 3.12 and ponyorm 0.7.19:

```
from pony.orm import (
    Database,
    Required,
    Set,
    Optional,
    PrimaryKey,
    set_sql_debug,
    commit,
)
import pony.orm as pny

db = Database()
db.bind(provider="sqlite", filename=":memory:")


class Metric(db.Entity):
    id = PrimaryKey(int, auto=True)
    spec = Required(str)
    links = Set("MetricLink")


class Identifier(db.Entity):
    id = PrimaryKey(int, auto=True)
    name = Required(str)
    links = Set("MetricLink")


class MetricLink(db.Entity):
    id = PrimaryKey(int, auto=True)
    metric = Required(Metric, column="metric_id")
    identifier = Required(Identifier, column="identifier_id")
    ident = Optional(str, nullable=True)

set_sql_debug(True)
db.generate_mapping(create_tables=True)

with pny.db_session:
    i1 = Identifier(name="IdentName1")
    m1 = Metric(spec="MetricSpec1")
    commit()
    m1 = MetricLink(metric=m1, identifier=i1, ident="key")
    commit()

    ident_id = i1.id
    ident_value = "key"

    query_req = pny.select(
        (m.id, m.name, m.spec)
        for m in Metric
        for l in m.links
        if l.identifier.id == ident_id and (l.ident == ident_value or l.ident is None)
    ).without_distinct()
```

**Output:**

> Traceback (most recent call last):
>   File "/app/pony_bug.py", line 49, in <module>
>     query_req = pny.select(
>                 ^^^^^^^^^^^
>   File "/app/.venv/lib/python3.12/site-packages/pony/orm/core.py", line 5560, in select
>     return make_query(args, frame_depth=cut_traceback_depth+1)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/app/.venv/lib/python3.12/site-packages/pony/orm/core.py", line 5546, in make_query
>     tree, external_names, cells = decompile(gen)
>                                   ^^^^^^^^^^^^^^
>   File "/app/.venv/lib/python3.12/site-packages/pony/orm/decompiling.py", line 43, in decompile
>     decompiler = Decompiler(codeobject)
>                  ^^^^^^^^^^^^^^^^^^^^^^
>   File "/app/.venv/lib/python3.12/site-packages/pony/orm/decompiling.py", line 162, in __init__
>     decompiler.decompile()
>   File "/app/.venv/lib/python3.12/site-packages/pony/orm/decompiling.py", line 313, in decompile
>     throw(DecompileError('Unsupported operation: %s' % opname))
>   File "/app/.venv/lib/python3.12/site-packages/pony/utils/utils.py", line 99, in throw
>     raise exc
> pony.orm.decompiling.DecompileError: Unsupported operation: POP_JUMP_IF_NOT_NONE

**Comment by benmod** [comment]
I am experiencing the same issue, but in my case I get the `POP_JUMP_IF_NONE` Decompile error.

**Comment by j4hangir** [comment]
Same error on Python 3.12:

`pony.orm.decompiling.DecompileError: Unsupported operation: POP_JUMP_IF_NONE`

Here's the snippet:

```py
select(md for md in MessageData if md.message is self and (md.user is None or md.user == current_user.user))
```

**Comment by cam-mh** [comment]
> Same error on Python 3.12:
> 
> `pony.orm.decompiling.DecompileError: Unsupported operation: POP_JUMP_IF_NONE`
> 
> Here's the snippet:
> 
> ```python
> select(md for md in MessageData if md.message is self and (md.user is None or md.user == current_user.user))
> ```

I encountered this issue as well. I was able to solve it by doing:

```
select(md for md in MessageData if md.message is self and (md.user == None or md.user == current_user.user))
```

I believe it has something to do with how Python evaluates the abstract syntax tree when constructing the sql statement.

**Comment by tehron** [comment]
I've encountered this issue, too. Worked around it with if/else, thereby doubling the queries.
Thanks @cam-mh for this workaround!

But I think the devs should take a closer look on this despite. Seems no one cared so far. :/
Seems those two instructions (POP_JUMP_IF_NONE/POP_JUMP_IF_NOT_NONE) are not/not correctly handled in [decompiling.py](../blob/main/pony/orm/decompiling.py)

**Comment by nburns** [comment]
got a branch here that seems to fix part of the issue, could use testing since I'm not very familiar with pony's decompilation process: https://github.com/ponyorm/pony/pull/741
